### ISSUE TITLE
Could not init class for device type - Error gets shown too many times

### ISSUE THREAD

**Issue by mbierman** [milo526/homebridge-tuya-web#1]
When loading homebridge with this plugin installed and configured, I get this message: 
![image](https://user-images.githubusercontent.com/1205471/82159529-a5cb0d00-9843-11ea-9e0c-45c6e01d093c.png)

`Could not init class for device type [scene]` shows even after removing all scenes from the Smart Life app and restarting homebridge.

Scenes are currently not supported in this plugin so this error message should be ignored (and whatever is generating it.) Ideally the plugin would allow scenes in Smart Life/Tuya apps and just ignore them but barring that, this error message should not appear even when there are no scenes as the user can't do anything about it. 

Another option is to keep an alert, but change it to give the user guidance about deleting scenes in the Tuya app. I don't think this is a better solution however because this plugin should just ignore any scenes in Tuya. At most, it should let the user know that senes aren't automatically "ported" from Tuya > homebridge in any sense. That is a reasonable caveat to provide users I suppose.

**Comment by mbierman** [comment]
I guess this would go away if merged with @fratton's fork were merged in. :)

**Comment by milo526** [comment]
We discussed integrating scenes in some other issues already but just to be clear here - 

Scenes are not supported at the moment, the warning shown here is shown for any device (Tuya exposes scenes as devices) that this library does not support, I added these warnings as an indicator for the user (the library is "aware" that a device is "not working") and as a guidance for me to troubleshoot problems for others.
You should only get this warning at startup, afterwards they are fully ignored, the do not impact the working of the library at all.

So everything you see here is "by-design".

**Comment by mbierman** [comment]
I understand. I'm just not a fan of the message asis. 

Simply putting in the readme that scenes aren't supported or having a single line reminding users is sufficient in my view. It seems to repeat for every scene which looks like the user should be concerned about.

**Comment by milo526** [comment]
I agree; just showing it one time (per non-supported device type) seems like a good idea to reduce the number of log entries.

**Comment by milo526** [comment]
This has been implemented in the upcoming typescript rewrite, expect to release that one in about a month.

**Comment by mbierman** [comment]
@milo526 was this implemented?

**Comment by milo526** [comment]
Not yet sadly

**Comment by mbierman** [comment]
No worries. I just did t want it to close. :)

**Comment by milo526** [comment]
Hello, could you see if the current beta version solves this problem for you? install `@milo526/homebridge-tuya-web@beta`

**Comment by mbierman** [comment]
Installed the beta. Will monitor for a day or too and report back.

**Comment by mbierman** [comment]
Something with the beta isn’t right. 
![85CF0BB6-A692-4995-B862-520C08861887](https://user-images.githubusercontent.com/1205471/89812687-5c622500-daf5-11ea-8b44-e28a89c6acc1.png)

**Comment by milo526** [comment]
That might be because of alterations in the discovery process; could you try restarting homebridge? It should solve itself.

**Comment by mbierman** [comment]
nope. 

![2BCCE3EA-2290-4D8C-B896-878F4747419B](https://user-images.githubusercontent.com/1205471/89814055-6a18aa00-daf7-11ea-831c-3f8559a394b5.png)

**Comment by milo526** [comment]
This issue has been fixed in the [v0.4.2 release](https://github.com/milo526/homebridge-tuya-web/releases/tag/v0.4.2) if you are still experiencing this issue, or are experiencing other issues, please open a new bug report.

Thank you once again for this bug report, reports like these help make the plugin better!
