### ISSUE TITLE
Dual dimmer

### ISSUE THREAD

**Issue by avronn2** [milo526/homebridge-tuya-web#101]
**Describe the bug**
Dimmer for 2 switches works great in tuya app. In homekit only one switch dimmer available. 

**Steps To Reproduce**

**Plugin Version**
0.4.8
 
 
 **Homebridge Config**

 "name": "TuyaWebPlatform",
            "options": {
                "username": "xxx@gmail.com",
                "password": "xxxxxxxxx",
                "countryCode": "972",
                "platform": "smart_life"
            },
            "defaults": [
                {
                    "device_type": "form"
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        

 
 
 ```json

```
 
 **Device Config**
 
 
 **Additional Context**
 
![736D1D89-8584-4F3A-A58C-CC1F48D8E81B](https://user-images.githubusercontent.com/59398701/97049051-b5354b80-1583-11eb-89d7-95130e8799ab.png)
![49A29751-9860-4EF5-B5C6-9C8D4B0D667C](https://user-images.githubusercontent.com/59398701/97049062-b9f9ff80-1583-11eb-8f5c-e0da09f048dd.png)

**Comment by milo526** [comment]
Well isn't that great, Tuya will always find a new way to surprise me.

I think you accidentally missed 1 step in the issue template, adding the Device Config.

Could you please add that step for me and then I'll be able to look into this for you.

**Comment by avronn2** [comment]
Here it is.
we are talking about the "Living Room Dimmer"

thanks

-------------------

Getting credentials
Got credentials
{   'access_token': 'EUheu1594748396255lYV5G7f03fWmF6G',
    'expires_in': 864000,
    'refresh_token': 'EUheu1594748396255lYV5GfWFliTedx8',
    'token_type': 'bearer'}
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {   'color_mode': 'colour',
                                                  'online': True,
                                                  'state': 'false'},
                                      'dev_type': 'light',
                                      'ha_type': 'light',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/ay1531122507771gALCb/1597119453d0126fd4c91.png',
                                      'id': 'bf263fb0a2d576cf9epuj0',
                                      'name': 'Balcony led'},
                                  {   'data': {   'brightness': '62',
                                                  'online': True,
                                                  'state': 'true'},
                                      'dev_type': 'light',
                                      'ha_type': 'light',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/ay15327721968035jwx9/158754172045f19c21b2e.jpg',
                                      'id': '38341275c82b9648ac56',
                                      'name': 'Living room dimmer'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/001460162698766TR4v1/1589957291d0c8f5cb465.png',
                                      'id': 'bf6f7c87479d31ec4baesj',
                                      'name': 'Garden light'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/product_icon2/kg_1.png',
                                      'id': '34511070ecfabc566449',
                                      'name': 'מבואת שירותים'},
                                  {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/product_icon2/kg_1.png',
                                      'id': '34511070ecfabc566bd5',
                                      'name': 'WIFI Switch Module'},
                                  {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': 'Vh4pvbI5j0aLFLns',
                                      'name': '\\"לד מרפסת\\" ON/OFF:ON'},
                                  {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': '6UJc28Lc1o2IXoD6',
                                      'name': 'לפתוח סלון'},
                                  {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': 'tPkXE0Oj60Ff27zY',
                                      'name': 'לסגור סלון'}],
                   'scenes': []}}
!!! NOW REMOVE THIS FILE, SO YOUR CREDENTIALS (username, password) WON'T LEAK !!!


**Comment by milo526** [comment]
Thank you for this information.

As you might be able to see, the following information is present about the living room dimmer:

```json
{
   "data":{
      "brightness":"62",
      "online":true,
      "state":"true"
   },
   "dev_type":"light",
   "ha_type":"light",
   "icon":"https://images.tuyaeu.com/smart/icon/ay15327721968035jwx9/158754172045f19c21b2e.jpg",
   "id":"38341275c82b9648ac56",
   "name":"Living room dimmer"
}
```

There is only one exposed device here.

Sadly I will not be able to support your devices, this is a limitation by Tuya who chooses to expose only one of your dimmers.
You might want to look into one of the other tuya plugins (not Tuya-web, Tuya-lan would probably work) they are a bitter harder to setup but they are also more flexible.
