### ISSUE TITLE
Unable to login using credentials for the Smart Life app

### ISSUE THREAD

**Issue by philk30** [milo526/homebridge-tuya-web#107]
**Describe the bug**
I tried logging in using my Smart Life app credentials but I get a " Authentication error: Get accesstoken failed. Username or password error!" error. I am not using an apple login so I ruled that out.

**Steps To Reproduce**
1. Login using Smart Life credentials. 
2. Changed the password. 
3. Tried again using the Smart Life credentials.

**Plugin Version**
 v0.4.8 

 
 **Homebridge Config**

 
 
 ```json
{
            "name": "TuyaWebPlatform",
            "options": {
                "username": "##########",
                "password": "#########",
                "countryCode": "1",
                "platform": "smart_life"
            },
            "defaults": [
                {
                    "device_type": "form"
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        }
```
 
 **Device Config**
Getting credentials
Got credentials
{   'errorMsg': 'Get accesstoken failed. Username or password error!',
    'responseStatus': 'error'}
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    payload = {"accessToken": auth_response["access_token"]}
KeyError: 'access_token'
 
 
 **Additional Context**

**Comment by milo526** [comment]
I just verified the process with my own account and it works as expected.
Is your country code correct? (is your account US based?)
Did you create your account on the correct smart life app?

The correct one can be found [in the App Store](https://apps.apple.com/nl/app/smart-life-smart-living/id1115101477).

**Comment by philk30** [comment]
Yes. It is a US based account created with the right app. 

I originally created it with an Apple login and then added my email after the fact. Could that cause an issue ?

**Comment by philk30** [comment]
I like that idea. Thank you Milo

**Comment by milo526** [comment]
🤷 Could be.

I am sorry I can't help you further but this is clearly not a problem with the plugin when following the instructions.

I am not affiliated with Tuya and I am not a support help line. I am just a student in his bedroom, trying to code a plugin.

The best advice I can offer you is trying to create a new account using username and password combo and seeing if that works for you. If it does you can migrate your devices to the new account. I've heard many people who managed to get their setups working when doing this.
