### ISSUE TITLE
[NEW DEVICE] Is TanTan WiFi Plugs supported?

### ISSUE THREAD

**Issue by simplenotezy** [milo526/homebridge-tuya-web#108]
I have these WiFi plugs but I am not sure if this library supports them? I was told they might do.

https://www.amazon.com/TanTan-Assistant-Required-Anywhere-Upgraded/dp/B071LLWLLP

**Comment by milo526** [comment]
And might I suggest you try it?
In the read me is some documentation on how to check if this api works with your plugin

**Comment by simplenotezy** [comment]
I see. I can try to test it. Just thought it would be easier to ask; as you might know beforehand. I need to buy some adapters before I can test them though

**Comment by milo526** [comment]
There are about 11000 different tuya products (reported by tuya).
I have exactly 3 of them.

It seems like these will work. But I can give you no guarantee on this.
