### ISSUE TITLE
[Accessory Request] (Climate) Herschel XLS T-MT Thermostat

### ISSUE THREAD

**Issue by davidjroos** [milo526/homebridge-tuya-web#109]
Hi there

Happy to contribute to getting this to work, but I know diddly about Homebridge specifically, so let me know how best to help - figured it was best to try and get this added through the (most) official Tuya plugin than trying to branch off my own thing.

The device details are here: [herschel-infrared.co.nz](https://www.herschel-infrared.co.nz/product/t-mt-wifi-thermostat/) and the [manual](https://www.herschel-infrared-technology-center.com/wp-content/portal/tds/xls-controls/T-MT%20Mains-powered%20WiFi%20Thermostat%20Instructions%20Booklet.pdf)

Operations available on the App:
- Power On / Off (turns off the T-MT and the heater)
- Temperature override (Orange circle with + and – buttons)
- Manual Operation
- “Smart” Operation (Program Mode)
- Holiday Mode
- Settings
- Controller Keypad lock

Not much useful in the debug logs, just:
`[11/1/2020, 8:32:44 AM] [TuyaWebPlatform] Could not init class for device type [climate]`

```json
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {'online': True, 'state': 'true'},
                                      'dev_type': 'climate',
                                      'ha_type': 'climate',
                                      'icon': 'https://images.tuyaus.com/smart/product_icon/qn.png',
                                      'id': '83273424fcf5c484c598',
                                      'name': 'Thermostat'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/1540200140j8qgitaok2l_0.jpg',
                                      'id': '68228606ecfabcbedeef',
                                      'name': 'Reading Light'},
                                  {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/program_category_icon/cz.png',
                                      'id': '740125532462ab280ebe',
                                      'name': 'Fridge'}],
                   'scenes': []}}
```
![2 - 1](https://user-images.githubusercontent.com/15630844/97788657-6f315500-1c1f-11eb-8e3e-26ebbb661cb7.jpeg)
![2 - 2](https://user-images.githubusercontent.com/15630844/97788658-72c4dc00-1c1f-11eb-9eb7-a02e0af4e6b5.jpeg)
![2 - 3](https://user-images.githubusercontent.com/15630844/97788659-735d7280-1c1f-11eb-9255-2235ba48ca6b.jpeg)
![2 - 4](https://user-images.githubusercontent.com/15630844/97788660-73f60900-1c1f-11eb-8696-1401087ffa60.jpeg)
![2 - 5](https://user-images.githubusercontent.com/15630844/97788661-73f60900-1c1f-11eb-9baf-0699d79ea338.jpeg)

**Comment by milo526** [comment]
Hello and thank you for your expressed interest.

This feature is currently being tracked in #63 (it is for general climate support)

Please follow that issue for updates.
