### ISSUE TITLE
RGBW bulb can’t be set to light mode only rgb

### ISSUE THREAD

**Issue by Vannixxo** [milo526/homebridge-tuya-web#110]
Hello my tuya smart bulb by HomeKit can only be set to color, when I go to temperature and click orange or blue shades it changes color..
Is this normal?

My bulb in smartlife only support 4000k white for white mode (brightness control exclusively) and color plus saturation for rgb mode, is this the reason? Do all made for HomeKit bulbs require to support warm plus cold “white” setting?

I can’t see how to go back to “pure white” setting from HomeKit, I must use tuya app.

I tried override setting to: form, lightbulb, light, rgbw, and finally removed the device override section completely, no change.

**Comment by milo526** [comment]
Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

Without this it is hard for me to help you with regards to this specific issue.

**Comment by milo526** [comment]
Closing due to no response
