### ISSUE TITLE
Can't connect to new account created by Google ID or Apple ID

### ISSUE THREAD

**Issue by LiranETN** [milo526/homebridge-tuya-web#111]
**Describe the bug**

**Plugin Version**
 
 
 **Homebridge Config**
 
 
 ```json

```
 
 **Device Config**
 
 
 **Additional Context**

**Comment by milo526** [comment]
Same problem as with apple also applies to google.

This is not supported.
This will not be supported.
This can not be supported.

Please create an account using username and password.
