### ISSUE TITLE
Outlets show double switches in one device but only one actually works, cannot remove the other

### ISSUE THREAD

**Issue by bboy11501** [milo526/homebridge-tuya-web#114]
It is one switch showing up twice. [](https://imgur.com/a/uomg2A0)

https://imgur.com/a/uomg2A0

**Comment by milo526** [comment]
Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

Without this it is hard for me to help you with regards to this specific issue.

Furthermore I'd like for you to post your configuration entries.

These two steps were also posted in the issue template, they are there with a reason. 
I'm voluntarily spending a lot of time, creating and maintaining this plugin.
Please help me by providing me with the requested information, otherwise there is nothing I can do for you.

My blind guess would be that this is solved by resetting your accessory cache.

**Comment by bboy11501** [comment]
the plugin works fine i can turn stuff on and off, it just thinks there are 2 switches for the smart outlet, how do i change it from thinking its an outlet to just a light switch, that should fix the problem.

**Comment by milo526** [comment]
Please see [the documentation on Overruling device types](https://github.com/milo526/homebridge-tuya-web#overruling-device-types) on how to switch the device type that is exposed to HomeKit.

However I do not think that this will solve your issue.
The device is (or was) exposed to HomeKit wrongly. You will probably need to reset your accessory cache to fix this.

If this does not work, please read my comment above and supply me with the information that is requested of you in the issue template and that I requested in said comment.

**Comment by soukron** [comment]
Same issue here, Oukitel smart plugs are exposed as a switch and as outlet, and only one (the switch) works. I tried to split them in two different accessories but taht doesn't work.

See here the output of debug_discovery:
```
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1531205282bwjtfqlfmbp_0.jpg',
                                      'id': '02010326807d3a7a1c8e',
                                      'name': 'Oukitel 2'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1531205282bwjtfqlfmbp_0.jpg',
                                      'id': '78487660840d8e89444a',
                                      'name': 'Oukitel 1'},
                                  {   'data': {   'color_mode': 'colour',
                                                  'online': True,
                                                  'state': 'false'},
                                      'dev_type': 'light',
                                      'ha_type': 'light',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/ay1545812972898u8wAi/1558591387a5b9f41dbe7.jpg',
                                      'id': '31536181ecfabc73dae9',
                                      'name': 'Luz Diana'}],
                   'scenes': []}}
```

**Comment by soukron** [comment]
Okay, not sure what has happened but I needed to remove the cachedAccessories for a second and the next time the outlets were detected they were added as single switches. So I am good...
