### ISSUE TITLE
Oil Diffuser Support

### ISSUE THREAD

**Issue by saiajin** [milo526/homebridge-tuya-web#115]
**Is your feature request related to a problem? Please describe.**
Hello I would like to get support or my oil diffuser. It does not appear via the web api at all and I have emailed Tuya and requested homeassistant api support. 

**Describe the solution you'd like**
 support or my oil diffuser

**Describe alternatives you've considered**
It does does appear via Web Api and I have emailed Tuya and requested homeassistant api support. 

**Additional context**
https://www.amazon.com/Brilex-Aromatherapy-Ultrasonic-Humidifier-Adjustable/dp/B07YD5DDPC/ref=pd_nav_hcs_rp_2/146-2334479-6791162?_encoding=UTF8&pd_rd_i=B07YD5DDPC&pd_rd_r=bbb90434-768a-4067-ac14-6f6b5963ab74&pd_rd_w=V49PO&pd_rd_wg=0EqZl&pf_rd_p=b90f7456-95ee-4d98-80f8-00c4e91c331c&pf_rd_r=NA996DKK34A5TG59WR2W&psc=1&refRID=NA996DKK34A5TG59WR2W

Just want to get the ball rolling! Thank You!

![Screenshot 2020-11-14 at 10 44 56 AM](https://user-images.githubusercontent.com/71667075/99156396-5ab87800-2675-11eb-99aa-7a8d88d25aae.png)

**Comment by milo526** [comment]
Hey,
Thank you for opening an issue and taking the time to read to the template.
You filled in the issue almost perfectly. 
I'm afraid you missed one little piece.

> If they are not - _don't open an issue_. Ask Tuya support to support your device in their /homeassistant API

There is nothing I can do at the moment to add great support for this.

The only thing I can advice you to do is to create a scene and expose that scene via this plugin. That should be able to at least give you some support.

**Comment by saiajin** [comment]
Ugh ,I'm Sorry, yes I did send  the request.. I didn't see that part. I'll wait to hear back... thank you and sorry again.

**Comment by saiajin** [comment]
And thanks for what u do!!!!...Donated....

**Comment by milo526** [comment]
Haha, no problem, thank you for opening the issue and helping to improve the plugin, the donation is much appreciated.

**Comment by saiajin** [comment]
HI Sounds good I'll research some more and retry the steps….perhaps Tyua will reply soon.

Thank you for your help!

Miles Reetz
