### ISSUE TITLE
Feit Strip Lights

### ISSUE THREAD

**Issue by rajababu1223** [milo526/homebridge-tuya-web#120]
Hi Milo,

Thanks a lot for writing these code, this helps others a lot.

I got a costco Feit Strip Light and would like to connect to Homebridge. I have added the strip to TUYA App on my ios but unable to see the same in the Homekit app. COuld you pls help

**Comment by milo526** [comment]
Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

It might be that Tuya does not allow your specific light strip to be exposed. If you manage to get this request to show your light strip I can probably add it.

**Comment by davemacdo** [comment]
Sorry to reopen this issue. I have gotten the Feit Electric Strip Light added to Homebridge (via Tuya Smart app) and can control it from the Homebridge web UI, but it is not working in the Home app on my phone. The device shows up correctly as a light with dimming, color, and temperature controls, but it is always "updating" or "no response", which is frequently what I see for the Feit Electric Smart Bulbs as well. Not sure if there's much the Tuya plugin can do about this or if it's an issue with the API.

**Comment by milo526** [comment]
Hello, could you please provide me with the output that was also request earlier, this is an essential first step to discovering any possible issues.

**Comment by davemacdo** [comment]
Here's the response. The second item 'Strip Light' is the device in question. 


```
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {   'brightness': '255',
                                                  'color_mode': 'colour',
                                                  'color_temp': 1000,
                                                  'online': True,
                                                  'state': 'true'},
                                      'dev_type': 'light',
                                      'ha_type': 'light',
                                      'icon': 'https://images.tuyaus.com/smart/icon/ay1547545924859HGF4T/1589593757fb4d5dd1685.png',
                                      'id': 'eb64c0e097a2566ef12jqf',
                                      'name': 'Color Lights'},
                                  {   'data': {   'brightness': '500',
                                                  'color_mode': 'white',
                                                  'online': True,
                                                  'state': 'true'},
                                      'dev_type': 'light',
                                      'ha_type': 'light',
                                      'icon': 'https://images.tuyaus.com/smart/icon/ay1547545924859HGF4T/1603268822cb2f94a0ae7.png',
                                      'id': 'eb84cea34f83e55ed4gayv',
                                      'name': 'Strip Light'},
                                  {   'data': {   'brightness': '255',
                                                  'color_mode': 'white',
                                                  'color_temp': 1000,
                                                  'online': True,
                                                  'state': 'true'},
                                      'dev_type': 'light',
                                      'ha_type': 'light',
                                      'icon': 'https://images.tuyaus.com/smart/icon/ay1547545924859HGF4T/1589593757fb4d5dd1685.png',
                                      'id': 'eb3b360f57c8b69f6awlfk',
                                      'name': 'Color Lights 1'}],
                   'scenes': []}}
```

**Comment by adventuresuchen** [comment]
Had the same issue -  Under 'Device Name or id*', tried using 'name' (I used 'Strip Light') instead of 'id' and all is well now on the iOS Home app.

**Comment by pcm1ke** [comment]
I have an issue where my Feit strip and bulbs were originally added to the Feit app (instead of Tuya) and now if I try to add them to the Tuya app I can’t access all their functionality. They only show up as bulbs and the app complains about how they won’t work fully with this version of the Tuya app and to update to the latest, but I already have the latest Tuya app. I suspect this is because the firmware on the bulbs/strip is older than the current firmware that is pushed via the Tuya app. I don’t see a way to sign into a “Feit” account… only “Tuya, Smart Life, and another” … is there a way to sign into The “Feit” (smart321.com) account via this plug-in? Or a way to get the bulbs and strip added to the latest Tuya app with all the features available?

**Comment by milo526** [comment]
> I have an issue where my Feit strip and bulbs were originally added to the Feit app (instead of Tuya) and now if I try to add them to the Tuya app I can’t access all their functionality. They only show up as bulbs and the app complains about how they won’t work fully with this version of the Tuya app and to update to the latest, but I already have the latest Tuya app. I suspect this is because the firmware on the bulbs/strip is older than the current firmware that is pushed via the Tuya app. 


>I don’t see a way to sign into a “Feit” account… only “Tuya, Smart Life, and another” … is there a way to sign into The “Feit” (smart321.com) account via this plug-in? 

No, this is not possible due to limitations on Tuya's side

>Or a way to get the bulbs and strip added to the latest Tuya app with all the features available?

I don't know this; please contact Feits customer service if that exists to ask this.
