### ISSUE TITLE
Hue feature for LED Strips

### ISSUE THREAD

**Issue by yruah** [milo526/homebridge-tuya-web#121]
Hey, thank you for investing so much time to help us all.
I have bought me a new LED strip but i cant get the colours to work with hoobs or HomeKit. I tried overruling the device to light, but the colours i set arent working.  Also the dimming function is not listed in HomeKit when overruling it as dimmer. 

Would be great if this would work someday

Anyway the PlugIn is great.

**Comment by milo526** [comment]
Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

Without this it is hard for me to help you with regards to this specific issue.

**Comment by yruah** [comment]
Thank you for that fast reply 
Here the result:

Getting credentials
Got credentials
{   'access_token': 'EUheu1606064187114MwpjLYMoTLlK1IK',
    'expires_in': 864000,
    'refresh_token': 'EUheu1606064187114MwpjL1ug59C14Qe',
    'token_type': 'bearer'}
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1550751312j51om81lrcl_0.jpg',
                                      'id': '56312004c82b9601ba80',
                                      'name': 'Nachtlicht'},
                                  {   'data': {   'color_mode': 'colour',
                                                  'online': True,
                                                  'state': 'true'},
                                      'dev_type': 'light',
                                      'ha_type': 'light',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/001460162698766TR4v1/15902172291eb12c59706.png',
                                      'id': 'bf7c9681d6a8f07c7fepok',
                                      'name': 'LED Streifen'},
                                  {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/ay1509430484182dhmed/1568711567fd83656b47e.png',
                                      'id': '054008478caab5019b5f',
                                      'name': 'Licht'}],
                   'scenes': []}}

**Comment by milo526** [comment]
And thank you for your fast response.

So your led strip is giving a mixed signal to my plugin 😛 On the one hand it says that its `color_mode: "colour"` which indicates that it does support colors. On the other hand it does not provide said color data (which other products often do).

I'll look into some way to overwrite the plugins assumptions and allow you to configure this.

**Comment by yruah** [comment]
thank you very much!

**Comment by yruah** [comment]
Hello, 
I know its a bit early to ask but i cant wait for it so: How’s it going?

**Comment by dhhuston** [comment]
Thank you @milo526, I was just running into the same problem with some LED strips I just received.  You rock for working on this!

**Comment by milo526** [comment]
v0.5.4 is released as a pre-release version and has support for overwriting plugin decision.

You can now force hue to be enabled.

Overwrite your device to a lightbulb and enable color.

Please open another issue if you are still experiencing problems.
