### ISSUE TITLE
[TuyaWebPlatform] Authentication error: Get accesstoken failed. Username or password error!

### ISSUE THREAD

**Issue by SliVeBurnA** [milo526/homebridge-tuya-web#123]
**Describe the bug**
I can log in to iot.tuya.com with my username and password and I've linked my tuya-iOs-app with the web-platform.
The plugin still produces the error stated in the subject line.
The email address does not contain any dots (sliveburna@gmail.com).
I am a little desperate, since I don't know what I've done wrong.

**Steps To Reproduce**
I am sorry, I don't know what to write here.
I took the error from the log after restarting homebridge and making sure that everything is up and running without any further errors.

**Plugin Version**
That is the exact problem. I don't see my devices. The firmware of the plugin, however, is v0.4.8
 
**Homebridge Config** 
{
            "name": "TuyaWebPlatform",
            "options": {
                "username": "sliveburna@gmail.com",
                "password": "REDACTED",
                "countryCode": "49",
                "platform": "tuya",
                "pollingInterval": 10
            },
            "defaults": [
                {
                    "device_type": "form"
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        }
 
 
 ```json

```
 
 **Device Config**
Getting credentials
Got credentials
{   'errorMsg': 'Get accesstoken failed. Username or password error!',
    'responseStatus': 'error'}
Traceback (most recent call last):
  File "/var/folders/p3/fmhqw3gd63s_9__hj7ts8prr0000gn/T/pythonInTerm.AMvGvklg", line 35, in <module>
    payload = {"accessToken": auth_response["access_token"]}
KeyError: 'access_token' 

 
 **Additional Context**

**Comment by thecodegoddess** [comment]
I am having the same issue.

**Comment by milo526** [comment]
The common things to check:

Are you using sign-in with Apple/Facebook/Google/Whatever?
Did you set the correct country-code?
Did you set the correct platform?
Are there any dots in your email (you already said this is not the case).

Furthermore I have no clue.
It works for my personal instance, it works for a lot of other people, therefor I assume that the code for the plugin is correct.
I am not an employee of Tuya, I cannot look into this further.

**Comment by slntopp** [comment]
Had the same issue, @SliVeBurnA, also with German region, fixed by using phone number instead of email

**Comment by ApopheniaPays** [comment]
Same issue. 
Are you using sign-in with Apple/Facebook/Google/Whatever?
-no
Did you set the correct country-code?
-yes
Did you set the correct platform?
-yes
Are there any dots in your email (you already said this is not the case).
-no

**Comment by fabiohblage** [comment]
Hello @milo526, thanks for your contribution,

do you know if www.ismartlife.me is compatible with your plugin?

**Comment by RyogaVee** [comment]
I fixed my issue. But it was a weird fix.
My password is a mix of Upper and Lower case letters. I know for certain I typed in in the correct way. When I looked at the code, only the first letter was in caps. I manually changed in and rebooted homebridge and it worked perfectly.

I hope this helps someone else.

**Comment by milo526** [comment]
@RyogaVee what do you mean with "the code"? The configuration.json file? or the configuration in the config editor?

**Comment by RyogaVee** [comment]
Yes, the config.

**Comment by dtrouton** [comment]
I had a similar issue with an account that was created with a password but ALSO Google linked.  I created a new account with another email alias and shared the home with that account and it worked fine

**Comment by hemersonmf** [comment]
> 
> 
> I had a similar issue with an account that was created with a password but ALSO Google linked. I created a new account with another email alias and shared the home with that account and it worked fine

work for me.
thanks.

**Comment by rmsoaa** [comment]
guys I have checked on everything but the problem still exists.

**Comment by rubenlangeweg** [comment]
The same issue, made an account with username and password, after that linked with google. Then trying this integration was giving me the error with this account. After creating a new account on a different email address without linking to Google, no problems, and linking was done!

**Comment by Rpickp** [comment]
Can confirm. Creating a new account and adding it as Admin works. My older account was linked to Google which seems to be causing the issue.

**Comment by aljeks87** [comment]
Can confirm, too. First, I tried to login and got the same error "Authentication error: Get accesstoken failed. Username or password error!".
Then, I have created a new email account without "." character and then set up a new Smart Life account (added the device, again, but to the new account) and linked the new account to the Tuya IoT Platform. Now, it works fine. :-)

**Comment by wizardofozzie** [comment]
@aljeks87 

So do I need to delete the Smart Life binding from the broken account and bind to new account, or can it just bind to both?
Also, in the settings, is username and password the user/pass for the IOT-Tuya account or the Smart Life app account?

> Can confirm, too. First, I tried to login and got the same error "Authentication error: Get accesstoken failed. Username or password error!".
> Then, I have created a new email account without "." character and then set up a new Smart Life account (added the device, again, but to the new account) and linked the new account to the Tuya IoT Platform. Now, it works fine. :-)

**Comment by nhatnguyen95** [comment]
I think we should have a note having an issue with account linked 3rd service (Google, Alexa,...) and can be resolved by create another account and invite it to home.

**Comment by tanaponggithub** [comment]
I fix by change password to all lowercase character

**Comment by nuriofernandez** [comment]
Unable to authenticate.

- Tried with phone number
- Tried changing password to all lower case (both in smartlife app & config)
