### ISSUE TITLE
Devices reset to default on system reboot

### ISSUE THREAD

**Issue by Pelagious** [milo526/homebridge-tuya-web#124]
**Describe the bug**

Upon system reboot (not homebridge reboot) all devices from this plugin are returned to their default state (placed in the default room and ungrouped). This only seems to affect devices from this plugin and only happens when I reboot my raspberry pi. Interestingly enough, automations seem to be unaffected. 

**Steps To Reproduce**

1. Restart/reboot the system

**Plugin Version**
 
 0.4.8
 
 
 **Homebridge Config**

{
            "platform": "TuyaWebPlatform",
            "name": "TuyaWebPlatform",
            "options": {
                "username": "",
                "password": "",
                "countryCode": "1",
                "platform": "tuya"
            },
            "defaults": [
                {
                    "id": "20406812807d3a04b6a0",
                    "device_type": "switch"
                }
            ],
            "scenes": true
        },

     
 

 **Additional Context**
This seems to affect both devices from this plugin (actual devices) and devices created from scenes in the Tuya app.

**Comment by milo526** [comment]
I cannot reproduce this issue.

Could there be a problem with some sectors of your SD card?
Do you properly power down your pi instead of just pulling the plug?
