### ISSUE TITLE
tuya devices not showing up

### ISSUE THREAD

**Issue by gavinkleckner** [milo526/homebridge-tuya-web#128]
my Tuya devices using Tuyawebplatform won't show up even after restarting i've tried uninstalling and reinstalling it but nothing works my 4 devices won't show up

**Comment by milo526** [comment]
Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

Without this it is hard for me to help you with regards to this specific issue.

**Comment by bubez81** [comment]
same here...:
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {'devices': [], 'scenes': []}}

no devices but I have a device configured!
![IMG_0113](https://user-images.githubusercontent.com/19486458/101411928-0a35e280-38e2-11eb-8858-93524c203d2f.PNG)

**Comment by milo526** [comment]
@bubez81 sadly it seems like your device is not supported by the API that this plugin uses.

Since I'm not at all affiliated with Tuya there is nothing I can do, hopefully you will be able to find another plugin that works for you.

**Comment by bubez81** [comment]
what a pity...thank you, i will search around but i don't know what to look for, this device doesn't have a name or a model...
