### ISSUE TITLE
[NEW DEVICE] Tuya Vacplus Dehumidifier

### ISSUE THREAD

**Issue by witherel** [milo526/homebridge-tuya-web#129]
**Device type**

TuyaSmart Vacplus Dehumidifer

**Device information**

Running v0.5.2.  Device ID:  06571771bcddc2769f06

Looking for support for dehumidifier on or off, humidity set % and humidity room %
![image](https://user-images.githubusercontent.com/74502054/101416463-ecec1e80-38b7-11eb-8bac-8e67eccc2540.jpeg)

![image](https://user-images.githubusercontent.com/74502054/101416298-8a931e00-38b7-11eb-93d2-a4e3126c186c.jpeg)

```json

```

**Comment by milo526** [comment]
Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

Without this it is hard for me to help you with regards to this specific issue.

**Comment by witherel** [comment]
I am uncertain how to check if the api is supported.

**Comment by milo526** [comment]
In my previous comments there is a step-by-step explanation on how to do this.

I am not affiliated with Tuya. I don't work for them. I cannot magically fix all your problem, you have to give me some information before I can try to help you
