### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by mbierman** [milo526/homebridge-tuya-web#13]
After installing @fratton's fork things aren't working. (I can't report bugs there because he hasn't enabled that, sorry!) So... 

1. @fratton please enable bug reporting unless you and @milo526 would prefer to consolidate here, of course. Not sure what you prefer.
1. @fratton fork installs into "@fratton" instead of what I think is more standard `homebridge-tuna-web` or something similar. 
1. I can no longer control my Tuya accessories with HomeKit. I will try installing an older version of the plugin and see if things work and update the bug. 

If you would like these broken into separate bugs, of course let me know.

**Comment by mbierman** [comment]
O.K. I switched back to @milo526's fork and latest is now working for me. However, the install gives minor errors: 

	/homebridge # npm install @milo526/homebridge-tuya-web@0.3.2
	+ @milo526/homebridge-tuya-web@0.3.2
	added 4 packages from 7 contributors, removed 47 packages, updated 1 package and audited 583 packages in 27.095s

	33 packages are looking for funding
	  run `npm fund` for details

	found 2 vulnerabilities (1 low, 1 moderate)
	  run `npm audit fix` to fix them, or `npm audit` for details
	/homebridge # npm audit
	npm ERR! code ELOCKVERIFY
	npm ERR! Errors were found in your package-lock.json, run  npm install  to fix them.
	npm ERR!     Invalid: lock file's @milo526/homebridge-tuya-web@0.2.0 does not satisfy @milo526/homebridge-tuya-web@^0.3.2

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /root/.npm/_logs/2020-06-18T19_37_38_822Z-debug.log

**Comment by milo526** [comment]
Hello, I tried quite some things and for the life of me can't reproduce this issue.

It looks like you have a `package-lock.json` file (why? this shouldn't be necessary) and said file seems not to be updating when running `npm install` which is also strange.

The latest version of this library seems not to have any security issues if I run `npm audit` locally`

Could you please see if moving your lock-file and having npm generate a new one helps to solve this problem?

**Comment by mbierman** [comment]
I’d be happy to if I could find it.

![1F993196-5E77-4F44-8050-CEF06CB53C4C](https://user-images.githubusercontent.com/1205471/85212346-a48b7500-b306-11ea-9c60-0f863ffacb72.jpeg)

**Comment by milo526** [comment]
I think the file you are looking for is in `/homebridge/package-lock.json` (are you using `homebridge-config-ui-x`?)

**Comment by mbierman** [comment]
That file doesn't exist. 

yes, I'm using `homebridge-config-ui-x`.

**Comment by mbierman** [comment]
So I just tried it again and got the same thing. 

	/homebridge # npm install @milo526/homebridge-tuya-web@0.3.3
	+ @milo526/homebridge-tuya-web@0.3.3
	updated 1 package and audited 635 packages in 23.307s

	31 packages are looking for funding
	  run `npm fund` for details

	found 2 vulnerabilities (1 low, 1 moderate)
	  run `npm audit fix` to fix them, or `npm audit` for details
	/homebridge # 
	/homebridge # npm audit
	npm ERR! code EAUDITNOLOCK
	npm ERR! audit Neither npm-shrinkwrap.json nor package-lock.json found: Cannot audit a project without a lockfile
	npm ERR! audit Try creating one first with: npm i --package-lock-only

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /root/.npm/_logs/2020-06-20T22_43_13_973Z-debug.log
	/homebridge #

**Comment by milo526** [comment]
So i am kind of surprised by the fact that nobody else received this error (no issues mentioned on gitlab, reddit or directly to me). I also cannot reproduce this with a clean install.

For now I'll close this issue, if you can reproduce this on a clean install; please mention all steps you took to setup your homebridge + this plugin.

**Comment by mbierman** [comment]
FYI https://github.com/oznu/homebridge-config-ui-x/issues/767
