### ISSUE TITLE
Cannot get Treatlife combo Fan/Dimmer switch to expose dimmer to home bridge.

### ISSUE THREAD

**Issue by dscheck** [milo526/homebridge-tuya-web#130]
I am trying to get a Treatlife Combination Fan/Dimmer light switch to work properly in home bridge.   Only the fan seems to be visible.  I spent hours trying different combinations of device overrides but can never get the dimmer light to be visible to homekit.

How can I do this ??

**Comment by milo526** [comment]
Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

Without this it is hard for me to help you with regards to this specific issue.

**Comment by dscheck** [comment]
Milo, 

Thanks for helping, below is the output from the script.  There is now two of the same Treatlife Fan/Dimmer combo switches since I installed a 2nd one today.

The TuyaSmart iOS App shows both Fan and Dimmer Light controls and they operate perfectly via that app.

I haven't been able to get the dimmer light to be visible to the home bridge plugin.

-David
![TuyaSmart](https://user-images.githubusercontent.com/1689366/101722290-e4dadd00-3a77-11eb-916f-8df2908c245f.jpeg)
![TuyaSmartComboSwitchControls](https://user-images.githubusercontent.com/1689366/101722291-e5737380-3a77-11eb-85b8-9faa1853155e.png)




Getting credentials
Got credentials
{   u'access_token': ***removed***',
    u'expires_in': 864000,
    u'refresh_token': ***removed***',
    u'token_type': u'bearer'}
Getting devices
Got devices
{   u'header': {   u'code': u'SUCCESS', u'payloadVersion': 1},
    u'payload': {   u'devices': [   {   u'data': {   u'online': True,
                                                     u'speed': u'1',
                                                     u'speed_level': 4,
                                                     u'state': u'false'},
                                        u'dev_type': u'fan',
                                        u'ha_type': u'fan',
                                        u'icon': u'https://images.tuyaus.com/smart/icon/ay14906729310721fNjn/1568862398d42329fe9d0.jpg',
                                        u'id': u'53117844f4cfa27f588e',
                                        u'name': u'Fan'},
                                    {   u'data': {   u'online': True,
                                                     u'speed': u'1',
                                                     u'speed_level': 4,
                                                     u'state': u'false'},
                                        u'dev_type': u'fan',
                                        u'ha_type': u'fan',
                                        u'icon': u'https://images.tuyaus.com/smart/icon/ay14906729310721fNjn/1568862398d42329fe9d0.jpg',
                                        u'id': u'53117844f4cfa27f64a6',
                                        u'name': u'Fan'},
                                    {   u'data': {   u'online': True,
                                                     u'state': False},
                                        u'dev_type': u'switch',
                                        u'ha_type': u'switch',
                                        u'icon': u'https://images.tuyaus.com/smart/icon/ay1519551146071pEnBd/15909812603a95a0440e0.png',
                                        u'id': u'21560122f4cfa23a6ba5',
                                        u'name': u'Night light'}],
                    u'scenes': []}}

**Comment by dscheck** [comment]
FYI.  The "Night light" is a 3rd smart plug that is on the Tuya account...

**Comment by milo526** [comment]
Sadly the API only exposes 1 device for each of your fans.

Support for your light is not gonna be possible on any short notice.

**Comment by dscheck** [comment]
The device has Alexa and google assistant support, I wonder if I was to use the Alexa plugin for homekit if I can get both the fan and lights working as expected.    Wouldn't you think they only have one api that all the companies are using?

**Comment by milo526** [comment]
There are many different ways of controlling these Tuya devices.

There are multiple APIs and there are ways that require no API at all.
All have their advantages and dis-advantages.

I cannot help you with this plugin cause of the api that I am using here.
I do not know wether or not an Alexa based plugin will work, it is worth the shot since they are using a different API.

**Comment by dscheck** [comment]
ok, thank you for your help... Do you think if I was able to sniff the network packets of the TUYA app and recorded what is being sent to control it it could help ?

**Comment by milo526** [comment]
No that wouldn't work sadly.

The Tuya app is once again a different API from the API that this plugin is using.

There is enough documentation about this library for us to know what does and doesn't work.
Sadly your request belongs in the latter category.

**Comment by rreckhardt** [comment]
@dscheck did you find a solution?  I’m having the same issue.

**Comment by dscheck** [comment]
No, not really...  Treatlife told me to create siri shortcuts on my phone that respond to different commands and sends them to their app.   That works ok but my HomePods in the room usually takes over and it doesnt know the short cuts.

I would really love to have a fix for this..  

-dave

**Comment by paullj1** [comment]
You could use a format with native HomeKit support:
https://github.com/paullj1/TreatLife-HomeKit

**Comment by rreckhardt** [comment]
No way, that's awesome...  I'll check this out.  I swear that didn't exist a couple of weeks ago.  Unless my searching skills are terrible, which is probably the case.

Thank you very much.

**Comment by slavvka** [comment]
> No that wouldn't work sadly.
> 
> The Tuya app is once again a different API from the API that this plugin is using.
> 
> There is enough documentation about this library for us to know what does and doesn't work.
> Sadly your request belongs in the latter category.

Does it make sense to change the api to the one tuya app uses? Do you need help to do that?

**Comment by slavvka** [comment]
BTW treatlife fan switch isn’t exposed by the current api at all. Curious why

**Comment by milo526** [comment]
> > No that wouldn't work sadly.
> > The Tuya app is once again a different API from the API that this plugin is using.
> > There is enough documentation about this library for us to know what does and doesn't work.
> > Sadly your request belongs in the latter category.
> 
> @milo526 Does it make sense to change the api to the one tuya app uses? Do you need help to do that?

That is exactly what https://github.com/iRayanKhan/homebridge-tuya#readme does, however that definitely has its own different problems (most notably it is rather hard to get the access control tokens used in that plugin).

**Comment by stuffmattdoes** [comment]
Hey all, I have opened a GitHub issue with a request to support Treatlife 2-in-1 Dimmer Switch.

[View it here](https://github.com/tuya/tuya-home-assistant/issues/16)
