### ISSUE TITLE
Icon issue

### ISSUE THREAD

**Issue by Mikellas** [milo526/homebridge-tuya-web#134]
![109B6717-9720-463A-B98B-261685D6CCC8](https://user-images.githubusercontent.com/62306024/102003053-4cf52180-3d0b-11eb-9b9e-d64d14f3e5a0.jpeg)

Attached image shows the accessory that has issues.In the example the living room xmas light reverts to the original light i on when i restart homebridge.Is there a way to save the icon so it doesnt change per reboot?(Normally the accessory has the same icon as the one next to it (kitchen side xmas))

**Comment by milo526** [comment]
Works for me 😛 

Multiple reboots later, my icon keeps the correct state.

Please fill out all the steps from the issue template. There is probably an error somewhere else in your configuration.

**Comment by Mikellas** [comment]
Sorry for that didnt notice the template.

-Config below

{
            "name": "TuyaWebPlatform",
            "options": {
                "username": "xxxxx@xxxxxxx.xxx",
                "password": "xxxxxxxxx",
                "countryCode": "CY",
                "platform": "tuya",
                "pollingInterval": 600
            },
            "defaults": [
                {
                    "id": "bf30f083b75b62007byec3",
                    "device_type": "light"
                }
            ],
            "scenes": true,
            "platform": "TuyaWebPlatform"


-Plugin version is on the latest 0.4.8

-Device config below after running code

Python 3.8.2 (default, Feb 26 2020, 02:56:10)
Assistant API endpoint.ded to get a list of all devices available via Tuya Home A
 import requests
 import pprint
 
 # CHANGE THIS - BEGINNING
 USERNAME = "xxxxx@xxxxxxx.xxx"
 PASSWORD = "xxxxxxxx"
 REGION = "eu" 
 COUNTRY_CODE = "357" # Your account country code, e.g., 1 for USA or 86 for Chi
 BIZ_TYPE = "tuya" 
 FROM = "tuya" # you likely don't need to touch this
 # CHANGE THIS - END
 
 # NO NEED TO CHANGE ANYTHING BELOW
 TUYACLOUDURL = "https://px1.tuya{}.com"
 
 pp = pprint.PrettyPrinter(indent=4)
 
 print("Getting credentials")
Getting credentials
 auth_response = requests.post(
...     (TUYACLOUDURL + "/homeassistant/auth.do").format(REGION),
...     data={
...         "userName": USERNAME,
...         "password": PASSWORD,
...         "countryCode": COUNTRY_CODE,
...         "bizType": BIZ_TYPE,
...         "from": FROM,
...     },
... )
 print("Got credentials")
Got credentials
 auth_response = auth_response.json()
 pp.pprint(auth_response)
{   'access_token': 'EUheu16075359769245WHYBZmsGMqcJzS',
    'expires_in': 864000,
    'refresh_token': 'EUheu16075359769245WHYBT5S9JgMaKA',
    'token_type': 'bearer'}
 
 header = {"name": "Discovery", "namespace": "discovery", "payloadVersion": 1}
 payload = {"accessToken": auth_response["access_token"]}
 data = {"header": header, "payload": payload}
 print("Getting devices")
Getting devices
 discovery_response = requests.post(
...     (TUYACLOUDURL + "/homeassistant/skill").format(REGION), json=data
... )
 print("Got devices")
Got devices
 discovery_response = discovery_response.json()
 pp.pprint(discovery_response)
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1534306274gqn7iuvlbs5_0.jpg',
                                      'id': 'bf30f083b75b62007byec3',
                                      'name': 'Living room Xmas Lights'}],
                   'scenes': []}}
T LEAK !!!") NOW REMOVE THIS FILE, SO YOUR CREDENTIALS (username, password) WON'T


THANKS

**Comment by Mikellas** [comment]
Additionally the device is removed by all automations when Hoembridge is restarted
