### ISSUE TITLE
Thermostat Temperatures A Bit Wonky

### ISSUE THREAD

**Issue by mattxjones** [milo526/homebridge-tuya-web#137]
Hi Milo!

First off, thank you so much for all your hard work. Will make a donation to your Christmas fund shortly!

Following your response to my post in the discussion, I updated to 0.5.2 and happy days - my thermostat controlling underfloor heating showed up! However, it's telling me my kitchen floor is current 35 degrees celsius, which I'm fairly confident is incorrect ;D

I did the API call you asked for and got this:

{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {   'current_temperature': 41,
                                                  'max_temper': 35,
                                                  'min_temper': 5,
                                                  'online': True,
                                                  'state': 'true',
                                                  'temperature': 40},
                                      'dev_type': 'climate',
                                      'ha_type': 'climate',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/15264583415nnlzwfs1qd2wqz6i937op3nmi_0.png',
                                      'id': '53300726a4cf12addab1',
                                      'name': 'thermostat'}],
                   'scenes': []}}

Also I _think_ this is the thing you've asked for from the home bridge config but tell me if I'm wrong and how to get what you need:

        {
            "name": "TuyaWebPlatform",
            "options": {
                "username": "*****",
                "password": "*****",
                "countryCode": "44",
                "platform": "smart_life"
            },
            "defaults": [
                {
                    "device_type": "form"
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        },

And finally, if it helps, this is the device I'm using: https://www.amazon.co.uk/MOES-Thermostat-Temperature-Controller-Programmable/dp/B07PFNLPJP/ref=sr_1_3?crid=1LOWCM707T10Q&dchild=1&keywords=moes+smart+thermostat&qid=1608408223&s=diy&sprefix=moes+smar%2Cdiy%2C732&sr=1-3

**Comment by milo526** [comment]
Hey! Glad to hear that it is somewhat working or at least starting to work 🙂
Let's see what we can do to get it working even better!

What do you expect the current temperature to be?

The API output you post (which is the correct one happily), contains 4 key pieces of information.

```json
{
  "current_temperature": 41,
  "max_temper": 35,
  "min_temper": 5,
  "temperature": 40
}
```

Normally that means that the target temperature is 41 degree celsius and the current temperature is 40 degree.

This indeed seems quite toasty 😛.

Homekit is reporting 35 degree since your max_temperature is 35.

Are you using Config-UI-X?
Then you should be able to set the min and max temperature from the configuration:
<img width="888" alt="Schermafbeelding 2020-12-19 om 21 10 46" src="https://user-images.githubusercontent.com/5261909/102698589-e0b07b80-423e-11eb-8906-e6243d7d253d.png">

What is the smart life app reporting as current and target temperatures?

**Comment by mattxjones** [comment]
Hi Milo!

I think I’ve worked it out from the UX device settings page - I believe the temperature is being doubled. The target is 17.5, and the actual is 20.5 - 35 and 41 makes sense.

I’ve use the factoring on device settings to iron it out. Perfect! You’d already pre-emoted my problem 😅

Thanks,

Matthew Jones

On 19 Dec 2020, at 20:13, Milo Cesar <notifications@github.com> wrote:

﻿
Hey! Glad to hear that it is somewhat working or at least starting to work 🙂
Let's see what we can do to get it working even better!

What do you expect the current temperature to be?

The API output you post (which is the correct one happily), contains 4 key pieces of information.

{
  "current_temperature": 41,
  "max_temper": 35,
  "min_temper": 5,
  "temperature": 40
}
Normally that means that the target temperature is 41 degree celsius and the current temperature is 40 degree.

This indeed seems quite toasty 😛.

Homekit is reporting 35 degree since your max_temperature is 35.

Are you using Config-UI-X?
Then you should be able to set the min and max temperature from the configuration:


What is the smart life app reporting as current and target temperatures?
