### ISSUE TITLE
LED Stip RGBW

### ISSUE THREAD

**Issue by gvchagas** [milo526/homebridge-tuya-web#138]
**Describe the bug**

First I want to congratulate you for the plugin, it is very easy to configure and very well done!  i am using a led strip with 4 colors (rgb + warm white).  
The controller is wifi compatible with tuya and the selector in the HomeKit in the temperature part does not use the white led, only the RGB ones.  I am using a trick to create a scene in Tuya Smart that activates the warm white and in the Homekit it appears as a switch. 
Is it possible to control the 4 leds using the Homekit color control?  or use the white led together with RGB?

**Steps To Reproduce**

1 - Open the Light Bulb control
2 - select a color or color temperature
3 - controls only RGB and Warm White remains off

**Plugin Version**
 
Tuya Web Plataform: version 0.5.4-next 
 
 **Homebridge Config**
 
 

    {
            "name": "TuyaWebPlatform",
            "options": {
                "username": "REDACTED",
                "password": "REDACTED",
                "countryCode": "REDACTED",
                "platform": "tuya"
            },
            "defaults": [
                {
                    "id": "Sanca",
                    "device_type": "light",
                    "light_characteristics": [
                        "Brightness",
                        "Color",
                        "Color Temperature"
                    ]
                }
            ],
            "scenes": true,
            "scenesWhitelist": [
                "Tuya Split On",
                "Tuya Split Off",
                "Tuya Split Turbo",
                "Tuya Sanca Branca"
            ],
            "hiddenAccessories": [
                "Interruptor de luz de fundo"
            ],
            "platform": "TuyaWebPlatform"
        }
    ]
}

 
 **Device Config**
 

    
 
 **Additional Context**

**Comment by milo526** [comment]
Hello, thank you for the encouraging words!

Sadly this is not possible.
This is due to API limitations imposed by Tuya.

The plugin tells your lightbulbs what color they should become, not how they should manage to do that. It is not possible to address individual LEDS or groups of LEDS sadly.
