### ISSUE TITLE
Exposing wattage to HomeKit ("In Use" boolean)

### ISSUE THREAD

**Issue by alexkoenigs** [milo526/homebridge-tuya-web#139]
**Is your feature request related to a problem? Please describe.**

No problem, just an idea.

**Describe the solution you'd like**

I'd love to create HomeKit automations based on whether something is actually drawing a lot of power or not. Think a washing machine which draws a specific wattage when heating the water, and some other wattage when draining. I think this could enable many useful automations like flashing lights when dishwasher is done, notifications for when something stops drawing power when it's not supposed to etc. In my mind this could either be done by having a specific threshold configured in the config.json per device, at which homekit is told that the device is "In use", or by passing the wattage directly to homekit, exposing it as some attribute (in this case i'm not sure if i could base automations off of it tho).

**Describe alternatives you've considered**

no real alternatives exist afaik, relying on you here

**Additional context**

**Comment by milo526** [comment]
Great and lovely idea however it is not gonna work.

The Tuya app (sometimes) has access to this information, however the API that this plugin uses does not.

There is no way for me to get the required information for this functionality.

**Comment by alexkoenigs** [comment]
Hi, well this was a quick answer if I've ever seen one! I don't know if this makes any difference, but my devices are using the smart_life platform, not exactly tuya. But as I understand all platforms are going through the Tuya API anyways right?
Thanks for the quick reply.

**Comment by milo526** [comment]
Haha you were lucky that I was just typing another response here 😜 

You are indeed right - all these platforms: jinvoo, tuya, smart-life; they all use the Tuya api.
