### ISSUE TITLE
Temperature Sensor 

### ISSUE THREAD

**Issue by noma4i** [milo526/homebridge-tuya-web#140]
**Describe the bug**
Temperature sensor thinks it is a Climate controller.
- Current Temperature is incorrect

**Screenshots**
![image](https://user-images.githubusercontent.com/210667/102960251-a2b0a180-4535-11eb-8761-ddd401bb9c71.png)
![image](https://user-images.githubusercontent.com/210667/102960269-b0662700-4535-11eb-8338-6ea904f46ba5.png)
![image](https://user-images.githubusercontent.com/210667/102960328-d7245d80-4535-11eb-8547-2708713ac400.png)

**Steps To Reproduce**

1. Add temperature sensor to Smart Life. 
2. Restart Homebridge

**Plugin Version**
0.6.3
 

 **Homebridge Config**
 

 ```json

```

 **Device Config**
 
```json
"defaults": [
    {
        "id": "REDACTED",
        "device_type": "climate"
    }
],
```
 **Additional Context**
 
Payload extracted from API using debug tool
```json
{
   "current_temperature":2329,
   "max_temper":10000,
   "min_temper":-2000,
   "online":"True",
   "state":"2329",
   "temp_unit":"CELSIUS",
   "temperature":2329,
   "dev_type":"climate",
   "ha_type":"climate",
   "icon":"https://images.tuyaeu.com/smart/icon/1540907310m7lcr25209f_0.png",
   "id":"REDACTED",
   "name":"Temp Living Room"
}
```

**Comment by milo526** [comment]
For real though, what the heck is Tuya doing here....

This device is giving very strange output through the API.
Could it be that the actual temperature at that time was 23.29 degree celsius? That seems the closes to your actual recorded temperature.

In that case please set the `current_temperature_factor` to `0.01`.

The HomeKit tile is showing 150 degrees since I hard-coded that to be the maximum value that it will ever show, it needs some max value and hotter than the hottest ever recorded temperature outside seems reasonable 😉.

I will work on an update that will allow you to overwrite the device type to a temperature sensor so that you will not be able to alter the current temperature.

**Comment by milo526** [comment]
And I released an update that will allow you to overwrite the device type  to a temperature sensor 😉.

Please update the plugin to version 0.7.0 and update your config to reflect the following:

```json
{
   "id":"REDACTED",
   "device_type":"temperature_sensor",
   "current_temperature_factor":"0.01"
}
```

**Comment by noma4i** [comment]
Have updated the plugin. Now it show 150 all the time.
Homebridge
![image](https://user-images.githubusercontent.com/210667/103118326-78d8b580-46c2-11eb-8d2b-498ba9e554d0.png)
Homekit
![image](https://user-images.githubusercontent.com/210667/103118383-ab82ae00-46c2-11eb-9a88-48cb857e0682.png)


Config
```json
  {
            "name": "TuyaWebPlatform",
            "options": {
                "username": "REDACTED",
                "password": "REDACTED",
                "countryCode": "REDACTED",
                "platform": "smart_life"
            },
            "defaults": [
                {
                    "id": "REDACTED",
                    "device_type": "temperature_sensor",
                    "target_temperature_factor": "0.01"
                },
                {
                    "id": "REDACTED",
                    "device_type": "temperature_sensor",
                    "target_temperature_factor": "0.01"
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        }
```

plugin version: `@milo526/homebridge-tuya-web v0.7.0`

**Comment by noma4i** [comment]
Works now. Thank you!

**Comment by noma4i** [comment]
For some reason now temp sensors are grouped. Before they were separate but with incorrect temp. Now they are correct reporting hence grouped.

![image](https://user-images.githubusercontent.com/210667/103118749-63648b00-46c4-11eb-89c7-01f6ce348cec.png)

**Comment by milo526** [comment]
Sadly this is a side-effect of exposing your thermostats as temperature sensors.

Temperature sensors are shown as sensors in the sensor bar of homekit. All sensors that share a characteristic (i.e. current temperature) get grouped into 1 tile.

This is the way Apple designed the Home app. You might find it easier to use a third party app, not all third-party apps group sensors in this way.
