### ISSUE TITLE
[NEW DEVICE] Wifi Door/Window Sensor 

### ISSUE THREAD

**Issue by burakcankose** [milo526/homebridge-tuya-web#144]
Hello,

I bought a Tuya-supported WiFi-enabled door and window sensor, but this did not come on Homebridge, is it possible to make improvements to add it?

**Comment by milo526** [comment]
Hello, could you please fill in the issue template.

You are now providing way too little information for me to give any useful information on this.

**Comment by burakcankose** [comment]
Hello,

Sorry, I read the article thoroughly and tried to gather the necessary information.

I bought a Tuya supported door window sensor, added it to the smartlife app and started using it. I bought a switch before, I added it and used it. I ran the python file you provided and I only see the previous switch device in the result. no door window sensor, what can we do for it?

Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/001460162698766TR4v1/1589957291d0c8f5cb465.png',
                                      'id': 'bfb229b9c1cxxxxxxxxxxx,
                                      'name': 'Salon Priz'}],
                   'scenes': []}}

**Comment by milo526** [comment]
As you noticed already, only your switch is shown. This sadly means that the other device will not be supported.

There is no way for me to get any information on that device from this API.
