### ISSUE TITLE
Stop option for cover devices

### ISSUE THREAD

**Issue by Eladcar** [milo526/homebridge-tuya-web#145]
Currently, window cover only support open and close operations.

It would be nice to add the "stop" option and/or percentage based open.

If there was a possibility to say:
open: 5 sec
close: 15 sec
so you can make your own 50%,30%,15% buttons 

it would be wonderful 

thanks for the plugin

Elad

**Comment by milo526** [comment]
Finally received my own Window covering device 🥳.

Testing the stop option showed that it is working as intended.
Apple is just weird in how you are supposed to use this 😛 

There is no way to use the stop characteristic in Home.app (the official apple home app)

Some third party apps (I tested the Eve app) do have support for this functionality.

If you look at your device in the eve app there is a "Hold Position" option with a "STOP" button next to it. Press that and the curtains will hold their current position.

Percentage based open is tracked in #148.
