### ISSUE TITLE
Diffuser / Humidifier Device Types?

### ISSUE THREAD

**Issue by EdwinJS** [milo526/homebridge-tuya-web#150]
Hi Team,
Not sure of the requirements to be able to have tuya based diffusers/humidifiers as that device/accessory type in the home app?
At the moment it just shows up as a switch, but I’d love to be able to see a diffuser or humidifier icon. Is this at all possible?

**Comment by EdwinJS** [comment]
To add to this enhancement request, please see this [link ](https://www.kogan.com/au/buy/kogan-smarterhome-200ml-smart-aroma-diffuser-black-marble/) as that is the device I'm using.

I am more than happy to assist in getting this working, as you can see the diffuser also has an RGB property as there is a light with it as well. Getting the diffuser and rgb light as separate accessories may be the only easy way perhaps.

**Comment by milo526** [comment]
Hello,

Sadly this will not be supported.
The API that this plugin uses only supports a very limited set of device types, a diffuser/humidifier is not one of those device types.
Furthermore HomeKit requires humidifiers to report the current humidity, as we don't have this information it is not possible to expose humidifiers to HomeKit.

**Comment by saiajin** [comment]
> To add to this enhancement request, please see this [link ](https://www.kogan.com/au/buy/kogan-smarterhome-200ml-smart-aroma-diffuser-black-marble/) as that is the device I'm using.
> 
> 
> 
> I am more than happy to assist in getting this working, as you can see the diffuser also has an RGB property as there is a light with it as well. Getting the diffuser and rgb light as separate accessories may be the only easy way perhaps.
> 
> 

Mine does not show up as available for any integrations except Alexa... I also was hoping this was possible..

**Comment by GoodyGizmos** [comment]
@milo526 Any updates on diffusers being available in the API?

**Comment by milo526** [comment]
> @milo526 Any updates on diffusers being available in the API?

There are no updates, and since Tuya is phasing out this API as well as creating their own homebridge plugin I consider it highly unlikely that this will ever happen.

**Comment by GoodyGizmos** [comment]
OK, thanks
