### ISSUE TITLE
Current Power Consumption of an outlet

### ISSUE THREAD

**Issue by KaylaSiemon** [milo526/homebridge-tuya-web#152]
Hello,

Thank you for creating this wonderful plugin. The TuyaLan plugin has enabled the ability to monitor current power consumption of an outlet. I'm using it with tuya outlets. The plugin would be perfect if it would be possible to add the power consumption feature of the outlets and let HomeKit read the current power consumption. This would be great for creating automation e. g. for a washing machine. So it would be possible to determine the end of the washing process. You even can use fakegato (https://github.com/simont77/fakegato-history) to create a statistic of the power consumption.

Is it possible to have this feature added to this plugin? 

https://github.com/AMoo-Miki/homebridge-tuya-lan/issues/8

**Comment by milo526** [comment]
Thank you for opening this feature request.
This feature has been proposed before in #118.

My reaction there still holds, the API that this plugin uses, does not support the requested features.
Sadly this is not something I can change thus this will not be possible.
