### ISSUE TITLE
[GET] Device Offline

### ISSUE THREAD

**Issue by sterumbelow** [milo526/homebridge-tuya-web#161]
**Describe the bug**

Recently I've been getting a lot of 'No response' messages for devices in the Home app. All my devices are controlled by switches (so just on or off). 

My log shows:

[GET] Device Offline

However, the device is definitely online - I can see it is when I check the Tuya app, and can turn it on and off without an issue. Yet the Homebridge log and Home app still show it as offline/No response. 

This isn't happening on one device, but randomly across my sockets. My internet connection and WiFi reach are solid.

Restarting Homebridge fixes the issue but I'm having to do daily restarts because things keep going offline.

I've seen this happen with all sockets before and a restart fixed it, but never with one or two sockets individually - and never when they're online in the Tuya app. 

![image](https://user-images.githubusercontent.com/68124742/103709803-504a9880-4fab-11eb-83fd-4901b1d6ff54.png)

![image](https://user-images.githubusercontent.com/68124742/103709818-55a7e300-4fab-11eb-9800-8024b761d84f.jpeg)

![image](https://user-images.githubusercontent.com/68124742/103709822-593b6a00-4fab-11eb-847a-de265d918bdd.png)

**Steps To Reproduce**

Nothing has changed in terms of setup. WiFi is the same, Homebridge settings are the same, socket locations haven't changed. 

**Plugin Version**
 

 0.7.1

 **Homebridge Config**
 
 
 ```json

{
            "name": "TuyaWebPlatform",
            "options": {
                "username": "REDACTED",
                "password": "REDACTED",
                "countryCode": "REDACTED",
                "platform": "tuya"
            },
            "defaults": [
                {
                    "device_type": "form"
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        }
```
 
 **Device Config**
 
 
Unfortunately cannot do this step. The Teckin plugs work with Tuya which works with this plugin. All devices have worked but this is an issue I've had recently. 

 **Additional Context**
 

Only thing not set in my config is the polling interval. I believe this was removed as a default setting not too long ago. Would this make a difference?

**Comment by milo526** [comment]
I have not yet seen this happen before, the device offline error indicates that the Tuya Cloud cannot reach this device, this plugin simply forwards that message.
Some things to note - this error gets triggered when there is no wifi connection to the device or when the device is powered off, could the latter be the case for you?
If your devices is registered as offline, it will take at least 5 minutes for it to update so if you remove power from one of your devices, open the home app (and see the device as offline) it can take up to 6 minutes for the home app to show the correct status again (and you might have to reopen the home app to see any change at all)

**Comment by sterumbelow** [comment]
The device definitely isn't powered off, or out of WiFi range.

The Tuya app shows it is online and I can control the device - meanwhile Homebridge and Homekit say it's offline.

Is it possible to have a communication issue between the Tuya app and Tuya web?

**Comment by milo526** [comment]
Yeah a communication issue between the Tuya Cloud and the Plugin is possible (the plugin does nothing with the Tuya App, it talks directly to Tuya's servers).
To check this you will need to provide me with the Device Config.

Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

**Comment by sterumbelow** [comment]
> Yeah a communication issue between the Tuya Cloud and the Plugin is possible (the plugin does nothing with the Tuya App, it talks directly to Tuya's servers).
> 
> To check this you will need to provide me with the Device Config.
> 
> 
> 
> Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

Here you go!

Getting credentials
Got credentials
{   'access_token': 'EUheu159457033899160ap5jVS6fIIWdf',
    'expires_in': 864000,
    'refresh_token': 'EUheu159457033899160ap5tb1H9HYYCZ',
    'token_type': 'bearer'}
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1534306274gqn7iuvlbs5_0.jpg',
                                      'id': 'bfc752327a12ab46bedrkj',
                                      'name': 'Dehumidifier'},
                                  {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1534306274gqn7iuvlbs5_0.jpg',
                                      'id': 'bf4e38e3552b2335a1ke9m',
                                      'name': 'Garage Dehumidifier'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1534306274gqn7iuvlbs5_0.jpg',
                                      'id': 'bfae9bcdbe57e83038rez4',
                                      'name': 'Spare Bedroom Lamp'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1534306274gqn7iuvlbs5_0.jpg',
                                      'id': 'bfd4efd01513d33f27ge75',
                                      'name': 'Tyre'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1534306274gqn7iuvlbs5_0.jpg',
                                      'id': 'bf2c3cb6e70282eed7u8yb',
                                      'name': 'Ste Ice Cube'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1534306274gqn7iuvlbs5_0.jpg',
                                      'id': 'bfaf5b3182c07cf3dauuex',
                                      'name': 'Eli Ice Cube'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1534306274gqn7iuvlbs5_0.jpg',
                                      'id': 'bf53dcc657966dc41alj5l',
                                      'name': 'Fan'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1534306274gqn7iuvlbs5_0.jpg',
                                      'id': 'bf60e5be21f2202dd0nd6r',
                                      'name': 'Marshmallow'}],
                   'scenes': []}}

**Comment by milo526** [comment]
And is at the moment one of your devices mis-behaving (in this case stating that it is offline?) cause then we have a problem 😛 
If all devices are online now; could you please re-do this process and upload the results when one of your devices is shown as offline.

Thanks for your help 😄

**Comment by sterumbelow** [comment]
> And is at the moment one of your devices mis-behaving (in this case stating that it is offline?) cause then we have a problem 😛 
> 
> If all devices are online now; could you please re-do this process and upload the results when one of your devices is shown as offline.
> 
> 
> 
> Thanks for your help 😄 

All good at the moment but I'll repeat it when it happens again!

**Comment by jamesalmeida** [comment]
I'm having this same issue. I can control inside Smart life app but Homekit says No Response…

**Comment by MarioSave** [comment]
The same here, started today at noon

**Comment by stckhlm73** [comment]
Yes, also having this issue.

**Comment by phill-hunt** [comment]
Same for me App works fine for all devices but HomeBridge says offline

**Comment by tmeier82** [comment]
Same error happening for me here as well. 3 Devices offline in HomeBridge but visible on the Tuya app.

**Comment by tmeier82** [comment]
> Same error happening for me here as well. 3 Devices offline in HomeBridge but visible on the Tuya app.
> Also getting a ratelimiterror which I haven't seen before.
> 
> [07/01/2021, 10:37:00] [TuyaWebPlatform] [Kitchen Downlight East] - Renewing cache due to RateLimitError
> [07/01/2021, 10:37:00] [TuyaWebPlatform] [Kitchen Downlight East] - Device Offline
> [07/01/2021, 10:37:00] [TuyaWebPlatform] [Upstairs Hallway Downlight West] - Renewing cache due to RateLimitError
> [07/01/2021, 10:37:00] [TuyaWebPlatform] [Upstairs Hallway Downlight West] - Device Offline
> [07/01/2021, 10:37:00] [TuyaWebPlatform] [Upstairs Hallway Downlight East] - Renewing cache due to RateLimitError
> [07/01/2021, 10:37:00] [TuyaWebPlatform] [Upstairs Hallway Downlight East] - Device Offline

Does not seem to be doing it anymore.

**Comment by stckhlm73** [comment]
Intriguing! Seems to have fixed itself for me too!

**Comment by sterumbelow** [comment]
There have been a couple of Tuya app updated (iOS) recently. I wonder whether one broke the app and the most recent one (pushed _after_ I posted this issue) fixed it again?

I haven't had the problem again...so far. 

![image](https://user-images.githubusercontent.com/68124742/103917993-26f24f80-5106-11eb-80c7-a3a76243b3f3.jpeg)

**Comment by phill-hunt** [comment]
I’m using the Smart Life app not. Tuya and had the same issue seem to be working now though

**Comment by milo526** [comment]
Given the context of this issue and the information I got from other sources (amongst others multiple Reddit threads); it seems like there was a problem at Tuya.

Please keep me updated if this happens more often.

**Comment by sterumbelow** [comment]
> Given the context of this issue and the information I got from other sources (amongst others multiple Reddit threads); it seems like there was a problem at Tuya.
> 
> Please keep me updated if this happens more often.

Ok, so I had it happen again this evening. 

Tuya app showed all devices online and working. Home app showed my 'Tyre' as 'No Response'. Homebridge showed '[Tyre] - [GET] Device Offline' again.

I've pulled the log as you requested - it shows the tyre as online, so I guess Tuya Web _is_ pulling the information correctly after all. That presumably means there's an issue between Tuya Web/Plugin/Homebridge/Home.

Here's the log:

`Getting credentials
Got credentials
{   'access_token': 'EUheu159457033899160ap5vY16jtRDO3',
    'expires_in': 864000,
    'refresh_token': 'EUheu159457033899160ap5vdqOuyh8Xt',
    'token_type': 'bearer'}
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1534306274gqn7iuvlbs5_0.jpg',
                                      'id': 'bfc752327a12ab46bedrkj',
                                      'name': 'Dehumidifier'},
                                  {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1534306274gqn7iuvlbs5_0.jpg',
                                      'id': 'bf4e38e3552b2335a1ke9m',
                                      'name': 'Garage Dehumidifier'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1534306274gqn7iuvlbs5_0.jpg',
                                      'id': 'bfae9bcdbe57e83038rez4',
                                      'name': 'Spare Bedroom Lamp'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1534306274gqn7iuvlbs5_0.jpg',
                                      'id': 'bfd4efd01513d33f27ge75',
                                      'name': 'Tyre'},
                                  {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1534306274gqn7iuvlbs5_0.jpg',
                                      'id': 'bf2c3cb6e70282eed7u8yb',
                                      'name': 'Ste Ice Cube'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1534306274gqn7iuvlbs5_0.jpg',
                                      'id': 'bfaf5b3182c07cf3dauuex',
                                      'name': 'Eli Ice Cube'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1534306274gqn7iuvlbs5_0.jpg',
                                      'id': 'bf53dcc657966dc41alj5l',
                                      'name': 'Fan'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1534306274gqn7iuvlbs5_0.jpg',
                                      'id': 'bf60e5be21f2202dd0nd6r',
                                      'name': 'Marshmallow'}],
                   'scenes': []}}`

**Comment by sterumbelow** [comment]
Further to my post above:

I restarted Homebridge and initially all devices showed as 'No Response' in Home, while Homebridge just continued to show the Tyre as offline. 

Then, it changed to a different device that was offline (the fan). 

I checked the log again and noticed the yellow line of text. 

![image](https://user-images.githubusercontent.com/68124742/103957438-9ede6b00-5142-11eb-8b06-1a5028b0ae91.jpeg)

I decided to remove this line of code that was left over in my config:

`"defaults": [
               {
                   "device_type": "form"
               }
           ], `

After I did that, and restarted again, the issue has completely resolved itself. 

Unsure whether that was causing an issue or not. 

What do you think?

**Comment by milo526** [comment]
The last warning you posted is of no influence (that is also the subtle difference between a warning and an error) in this case the plugin will just ignore that specific part of your configuration.

Regarding the issue - I'll keep an eye on it cause I really don't understand what is going on here...

**Comment by sterumbelow** [comment]
So this happened to me again just now. 

Physical switch was on.
Tuya app - Shows on and is controllable
Homebridge - Shows on but is uncontrollable
Homebridge log - [GET] Device Offline
Home app - shows 'No response'

Screenshots and log below. And thank you for looking over this for me (and the others!). 

![image](https://user-images.githubusercontent.com/68124742/104227638-a3a46700-5441-11eb-81c6-8228bcb1304f.jpeg)
![image](https://user-images.githubusercontent.com/68124742/104227655-a69f5780-5441-11eb-93ec-322e76d52698.jpeg)![image](https://user-images.githubusercontent.com/68124742/104227662-a901b180-5441-11eb-8f6b-e7c8e756ce2e.jpeg)![image](https://user-images.githubusercontent.com/68124742/104227670-ab640b80-5441-11eb-9db6-14906d6cf139.jpeg)

Log

`Getting credentials
Got credentials
{   'access_token': 'EUheu159457033899160ap5uJcXAfFNxT',
    'expires_in': 864000,
    'refresh_token': 'EUheu159457033899160ap5H9pPukNtQR',
    'token_type': 'bearer'}
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1534306274gqn7iuvlbs5_0.jpg',
                                      'id': 'bfc752327a12ab46bedrkj',
                                      'name': 'Dehumidifier'},
                                  {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1534306274gqn7iuvlbs5_0.jpg',
                                      'id': 'bf4e38e3552b2335a1ke9m',
                                      'name': 'Garage Dehumidifier'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1534306274gqn7iuvlbs5_0.jpg',
                                      'id': 'bfae9bcdbe57e83038rez4',
                                      'name': 'Spare Bedroom Lamp'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1534306274gqn7iuvlbs5_0.jpg',
                                      'id': 'bfd4efd01513d33f27ge75',
                                      'name': 'Tyre'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1534306274gqn7iuvlbs5_0.jpg',
                                      'id': 'bf2c3cb6e70282eed7u8yb',
                                      'name': 'Ste Ice Cube'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1534306274gqn7iuvlbs5_0.jpg',
                                      'id': 'bfaf5b3182c07cf3dauuex',
                                      'name': 'Eli Ice Cube'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1534306274gqn7iuvlbs5_0.jpg',
                                      'id': 'bf53dcc657966dc41alj5l',
                                      'name': 'Fan'},
                                  {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1534306274gqn7iuvlbs5_0.jpg',
                                      'id': 'bf60e5be21f2202dd0nd6r',
                                      'name': 'Marshmallow'}],
                   'scenes': []}} `

**Comment by milo526** [comment]
Thanks for the report!

I'll try to validate this in the next few days.

**Comment by milo526** [comment]
I really can't find any glaring issues in the code and it hasn't happened for me.
I'm more and more starting to believe that the issue might be elsewhere.
I'll keep this open but don't expect a quick fix since I really don't know what to do about this 😅

**Comment by aryajuanda** [comment]
i have a same problem.. the problem seem happened when device is turning off manually and back turn on manually (loosing electricity). In tuya app, its reconect again but in homebridge it get device Offine and in home hit get No response.. 
restarting homebridge fix the problem...
