### ISSUE TITLE
Lomota garage door

### ISSUE THREAD

**Issue by gavinkleckner** [milo526/homebridge-tuya-web#162]
I want to make my garage doors smart and I was wondering if the lomota Garage door opener would work with this https://www.amazon.com/dp/B08FJ7S67K/ref=cm_sw_r_cp_api_glc_fabc_dLr9Fb5N60QDZ)

**Comment by milo526** [comment]
Probably, it is made by the correct manufacturer but I cannot give any guarantees.

It seems like it should work.
