### ISSUE TITLE
[TuyaWebPlatform] Authentication error: Get accesstoken failed. Username or password error!

### ISSUE THREAD

**Issue by russ1620** [milo526/homebridge-tuya-web#164]
Here's my config

But it gives me the error `[TuyaWebPlatform] Authentication error: Get accesstoken failed. Username or password error!`

Any ideas what might be causing the issue?

{
            "name": "TuyaWebPlatform",
            "options": {
                "username": "russ1620@gmail.com",
                "password": "PASSWORDXXXXX,
                "countryCode": "1",
                "platform": "smart_life"
```
            },
            "defaults": [
                {
                    "device_type": "form"
                }
            ],
            "scenes": true,
            "platform": "TuyaWebPlatform"
        }

**Comment by milo526** [comment]
Please see the [wiki entry](https://github.com/milo526/homebridge-tuya-web/wiki/Authentication-Error) I wrote about this.
Not much is known regarding this issue, the things I know are explained in that wiki entry.

I do not control the authentication for this plugin; that is done by Tuya.
