### ISSUE TITLE
Tuya OEM app

### ISSUE THREAD

**Issue by saamiranda** [milo526/homebridge-tuya-web#165]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Hi, is there a chance to use this plug-in with a Tuya OEM App? Our company has an OEM app (Hi By Geonav), and we would like to add our OEM devices with Homebridge but using our own app, not Tuya or Smart Life. Is this possible? Best regards!

**Describe alternatives you've considered**

**Additional context**

**Comment by milo526** [comment]
Hello,
Sadly that is not possible at the moment with this plugin due to Tuya limitations.

There might be another way to get this working though, please send me an email (see my profile for my email address) and we can discuss this further.

**Comment by milo526** [comment]
Closing due to no response.
