### ISSUE TITLE
da *%ck???

### ISSUE THREAD

**Issue by robitherobo** [milo526/homebridge-tuya-web#166]
heya as a proper rookie I have no idea what happened but I don't see any accessories anymore in Homebridge  

this is what I see even when I restored (still no accessories) but I can see everything fine on Smart life, I'm confused. thanks for the help

[08/01/2021, 11:06:01] [TuyaWebPlatform] getaddrinfo ENOTFOUND px1.tuyaeu.com

**Comment by robitherobo** [comment]
Also tried to uninstall the plugin and when I searched it again with the keyword Tuya I couldn't find milo256 in the list, I only found it when I typed Milo in search bar

**Comment by milo526** [comment]
Tuya's servers seem to be down.

This is also the issue that is reported in #161; 
no clue what tuya is doing with their servers lately.

Try rebooting your homebridge instance in a few minutes/hours it will probably resolve itself.

**Comment by robitherobo** [comment]
it's weird cause I'm also having issues with some HomeKit devices, can't add my outlets to Homekit anymore... imma just gonna throw it all out and go live in the woods thank you world :P

**Comment by djaytek** [comment]
I started having this issue for the last couple of days and now I can't control my devices from Home app. 
Is anyone having the same again?

**Comment by milo526** [comment]
Tuya's servers seem to be quite unstable lately; sadly there is nothing I can do about that since I do not work for or with Tuya.
