### ISSUE TITLE
[Accessory issue] Fan not updating

### ISSUE THREAD

**Issue by hamodcraft22** [milo526/homebridge-tuya-web#17]
ok so finally a tuya plugin that fully works!!! 

one small problem, the homebridge integration works amazingly but one issue....
when using the device physically "fan" it shows up in hombridge+homekit as ON at 100%, i can change the speed via homekit and it works amazing but I don't know why using the physical switch messes the things up 

also it takes a lot of time to update the statues in homebridge and the "pollingInterval": set to 1 does nothing of a difference

I recommend implementing the same idea of the homebridge-ewelink-max where it refreshes the statues when the homekit app is accessed

**Comment by hamodcraft22** [comment]
what?

**Comment by milo526** [comment]
This plugin uses some tricks to quickly update the state of your fan, some of which are similar to the ewelink-max solution. However Tuya changed some things on their side which this plugin will now have to solve (and what I'm working on at the moment) you can see this if you enable debugging for this plugin. The "error" you are looking for is "requesting to quickly". Once that problem is solved, your problem will be as well. You should be able to still control the device, homekit might just mis-report the state.

**Comment by hamodcraft22** [comment]
Amazing to hear!!

**Comment by hamodcraft22** [comment]
[6/21/2020, 11:23:03 AM] [TuyaWebPlatform] Error retrieving devices states Error: connect EHOSTUNREACH 18.185.175.51:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '18.185.175.51',
  port: 443,
  config: {
    url: 'https://px1.tuyaeu.com/homeassistant/skill',
    method: 'get',
    data: '{"header":{"name":"Discovery","namespace":"discovery","payloadVersion":1},"payload":{"accessToken":"EUheu1577038206493qNZKLE9wwswEWO8"}}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json;charset=utf-8',
      'User-Agent': 'axios/0.19.2',
      'Content-Length': 136
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus]
  },
  request: Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: true,
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      protocol: 'https:',
      maxRedirects: 21,
      maxBodyLength: 10485760,
      path: '/homeassistant/skill',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'px1.tuyaeu.com',
      port: null,
      nativeProtocols: [Object],
      pathname: '/homeassistant/skill'
    },
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 136,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'GET /homeassistant/skill HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json;charset=utf-8\r\n' +
        'User-Agent: axios/0.19.2\r\n' +
        'Content-Length: 136\r\n' +
        'Host: px1.tuyaeu.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      insecureHTTPParser: undefined,
      path: '/homeassistant/skill',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      _redirectable: [Circular],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://px1.tuyaeu.com/homeassistant/skill',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function]
}


this is the error i get, it might help you

**Comment by milo526** [comment]
Sorry but the error `EHOSTUNREACH` is not something this library can help you with. This error indicates that the machine that runs homebridge cannot access the Tuya cloud. Could this have been a one-time issue? The rest of your comments seem to indicate that other devices are working properly that should not be the case is you are also receiving this error.

**Comment by hamodcraft22** [comment]
yeah it could be that the internet went out for a second i dunno 😅
 i saw that you have a pre release, does that fix anything? (0.3.4-0)

**Comment by hamodcraft22** [comment]
I tested out the beta release (0.3.4-0) & the issue is still present

**Comment by hamodcraft22** [comment]
umm no you are not stal"ing" this issue bot 😛

**Comment by milo526** [comment]
Could you please see if the current beta version `@milo526/homebridge-tuya-web@beta` fixes this issue for you? The plugin has largely been re-written which includes some improvements in handling of the fan speed.

**Comment by hamodcraft22** [comment]
oh yeah i tried it again just now,
the first thing is that i get this error any time I'm using the tuya plugin "[7/26/2020, 8:13:10 PM] [TuyaWebPlatform] Requesting too quickly." after installing the plugin 
& 
"[7/26/2020, 8:15:24 PM] [TuyaWebPlatform] Could not find accessory in dictionary (1172f828-def3-4569-bf73-608d236aafc7)" after adding the config and restarting 

also getting this error when cloosing the homekit app and reopnning 

"[7/26/2020, 8:21:09 PM] [TuyaWebPlatform] RatelimitError: Requesting too quickly.
    at TuyaWebApi.discoverDevices (/usr/lib/node_modules/@milo526/homebridge-tuya-web/src/TuyaWebApi.ts:155:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

one more thing is that the fan has now 1 - 5 speeds which casus siri to say 5% or 1% rather then the previous better 1 - 100 scale

**Comment by hamodcraft22** [comment]
No you did not

**Comment by milo526** [comment]
Since this issue has become a bit of a mash of some different but separate issues I am going to close this one for now.

If you are still experiencing issues with the newest release please open separate issues for all issues that you are experiencing or respond to a relevant opened issue.
