### ISSUE TITLE
LED Strips - no color/brightness change

### ISSUE THREAD

**Issue by tbiggs45** [milo526/homebridge-tuya-web#172]
**Describe the bug**

I have 2 Treat Life brand LED Strips installed. When I set them up as a light in Homebridge, I have most all devices not responding and the strips only go on/off and do no change color. When I disable the 'color, brightness, color temp' on the strips, my other devices don't have connectivity issues anymore. 
"id": "ebb7a61d34ed0889d44kub",
                    "device_type": "light",
                    "light_characteristics": [
                        "Brightness",
                        "Color",
                        "Color Temperature"
Logs: 
[15/01/2021, 09:19:04] [TuyaWebPlatform] [TV Strip ] - Unsetting debouncedDeviceStateRequestPromise
[15/01/2021, 09:19:04] [TuyaWebPlatform] [TV Strip ] - Resolving resolveDeviceStateRequest from cache
[15/01/2021, 09:19:04] [TuyaWebPlatform] [TV Strip ] Characteristic.On - [GET] false
[15/01/2021, 09:19:04] [TuyaWebPlatform] [TV Strip ] Characteristic.Hue - [GET] undefined
[15/01/2021, 09:19:04] [TuyaWebPlatform] [TV Strip ] Characteristic.Saturation - [GET] undefined
[15/01/2021, 09:19:04] [TuyaWebPlatform] [TV Strip ] Characteristic.ColorTemperature - [GET] undefined
[15/01/2021, 09:19:04] [TuyaWebPlatform] [TV Strip ] Characteristic.Brightness - [GET] undefined
[15/01/2021, 09:19:04] [TuyaWebPlatform] [TV Strip ] Characteristic.Brightness - Tried to set brightness but failed to parse data. 
 { color_mode: 'colour', online: true, state: 'false' }
**Steps To Reproduce**

**Plugin Version**
 
 Firmware: 0.7.1
 **Homebridge Config**
 
 
 ```json
{
            "name": "TuyaWebPlatform",
            "options": {
                "username": "",
                "password": "",
                "countryCode": "1",
                "platform": "smart_life"
            },
            "defaults": [
                {
                    "id": "ebd17423347b2ae9d1stn2",
                    "device_type": "light",
                    "light_characteristics": [
                        "Brightness",
                        "Color",
                        "Color Temperature"
                    ]
                },
                {
                    "id": "44462287d8bfc0c107f7",
                    "device_type": "light",
                    "light_characteristics": [
                        "Brightness",
                        "Color",
                        "Color Temperature"
                    ]
                },
                {
                    "id": "10012004c82b960e4ddc",
                    "device_type": "light",
                    "light_characteristics": [
                        "Brightness",
                        "Color",
                        "Color Temperature"
                    ]
                },
                {
                    "id": "017743508caab5f0a068",
                    "device_type": "switch"
                },
                {
                    "id": "017743508caab5f12c24",
                    "device_type": "switch"
                },
                {
                    "id": "ebb7a61d34ed0889d44kub",
                    "device_type": "light",
                    "light_characteristics": [
                        "Brightness",
                        "Color",
                        "Color Temperature"
                    ]
                },
                {
                    "id": "eb1453e96158bb30d7bypa",
                    "device_type": "light",
                    "light_characteristics": [
                        "Brightness",
                        "Color",
                        "Color Temperature"
                    ]
                },
                {
                    "id": "eb5bebfaa0171efbb7k4q2",
                    "device_type": "light",
                    "light_characteristics": [
                        "Brightness",
                        "Color",
                        "Color Temperature"
                    ]
                },
                {
                    "id": "eb621ee7843356e9e3r7yr",
                    "device_type": "light",
                    "light_characteristics": [
                        "Color"
                    ]
                },
                {
                    "id": "eb859f00a06603600atmhi",
                    "device_type": "light",
                    "light_characteristics": [
                        "Brightness",
                        "Color",
                        "Color Temperature"
                    ]
                },
                {
                    "id": "eb728d534acef0fb5al4zl",
                    "device_type": "light",
                    "light_characteristics": [
                        "Brightness",
                        "Color",
                        "Color Temperature"
                    ]
                },
                {
                    "id": "017743508caab5f12c33",
                    "device_type": "switch"
                },
                {
                    "id": "5311784410521ce81930",
                    "device_type": "fan"
                }
            ],
            "scenes": true,
            "platform": "TuyaWebPlatform"
        }
```
 
 **Device Config**
 
  {   'data': {   'color_mode': 'colour',
                                                  'online': True,
                                                  'state': 'false'},
                                      'dev_type': 'light',
                                      'ha_type': 'light',
                                      'icon': 'https://images.tuyaus.com/smart/solution/142006/b9dd72a8410f8faa_cover.png',
                                      'id': 'ebb7a61d34ed0889d44kub',
                                      'name': 'TV Strip '},
 **Additional Context**
 
Great app and HUGE thanks for all of your support.

**Comment by milo526** [comment]
Due to the error

> Characteristic.Brightness - Tried to set brightness but failed to parse data. 
> { color_mode: 'colour', online: true, state: 'false' }

Your other devices do not respond, the plugin does log this error but does not properly inform Homebridge that an error occurred. This influences all your other Homebridge devices and makes them unresponsive, I'll fix this.

What we can also see in that error is that your devices does not expose its brightness to this API. This is a limitation imposed by Tuya and not something that I can alter. I advice you to disable color and brightness on these devices if you want to use them through HomeBridge.

**Comment by tbiggs45** [comment]
That's what I have been doing to lessen the errors. I just wanted to bring it to your attention. It's also interesting that a TreatLife/SmartLife/Tuya device doesn't expose all characteristics. But, it is what it is. Thanks for the quick response.

**Comment by milo526** [comment]
I can understand why you would think that, however it is very VERY common for these devices to expose only part of their devices.
This API is a giant mess and I'm trying to work around as many of its problem as I can to create the best possible plugin given my tools.
