### ISSUE TITLE
smartlife robot vacuums

### ISSUE THREAD

**Issue by aidanferre** [milo526/homebridge-tuya-web#173]
hi there is there anyway that you could add the option to add robot vacuums.  I've got 2 that i would like to add but when i get to the device there's no vacuum option

**Device type**

**Device information**

```json

```

**Comment by milo526** [comment]
Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

Without this it is hard for me to help you with regards to this specific issue.

**Comment by aidanferre** [comment]
when i go to add these vacuums it doesn't give me the option to add them under device type.  that's what i need is for vacuum to be under device type

**Comment by milo526** [comment]
Please provide me with the information I requested in my previous comment. It is essential for me to help you.
