### ISSUE TITLE
[NEW DEVICE] Door/Wiindow sensor

### ISSUE THREAD

**Issue by dieig** [milo526/homebridge-tuya-web#174]
Hi there,
I'd like to add in Homebridge a Door/Window sensor that works in the Smart life app.
Is it possible to add it with your plugin?

Thank you

**Comment by milo526** [comment]
Hey;

Sadly that is not possible.

Tuya does not expose sensors to the API that this plugin is using, please take a look at one of the other Tuya plugins such as the [homebridge-tuya-lan](https://www.npmjs.com/package/homebridge-tuya-lan) plugin.

**Comment by Kakise** [comment]
> Hi there,
> I'd like to add in Homebridge a Door/Window sensor that works in the Smart life app.
> Is it possible to add it with your plugin?
> 
> Thank you

Hello, if you want to use door sensors, you can use my plugin: https://github.com/Kakise/homebridge-tuya-door-cloud it works great with them
