### ISSUE TITLE
Tuya Smart Life Apps Not a Valid Device-ID  issues

### ISSUE THREAD

**Issue by chanyork** [milo526/homebridge-tuya-web#175]
Keep getting the below.

[1/19/2021, 3:46:33 PM] [TuyaWebPlatform] Tried overwriting device config for: "18857573dcxxxxxxxxxxx" which is not a valid device-id or device-name.

![image](https://user-images.githubusercontent.com/28833849/105006661-e97cb300-5a71-11eb-81cf-2207c8cf732c.png)

The Homebridge-tuya-web plugin version that I am using is @milo526/homebridge-tuya-web v0.7.1

 
 
 **Homebridge Config**
 
 
 ```json
        {
            "name": "TuyaWebPlatform",
            "options": {
                "username": "xxxxxx@xxxxxx.xxx",
                "password": "xxxxxxxxxxx",
                "countryCode": "61",
                "platform": "smart_life"
            },
            "defaults": [
                {
                    "id": "18857573dcxxxxxxxxxxxx",
                    "device_type": "garage"
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        }

```
 
 **Device Config**
 
 
 **Additional Context**

**Comment by milo526** [comment]
Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

Without this it is hard for me to help you with regards to this specific issue.

**Comment by chanyork** [comment]
> Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)
> 
> Without this it is hard for me to help you with regards to this specific issue.


Getting credentials
Got credentials
{   'access_token': 'EUheu1580860191490f4GZWXZ3EwgP7VN',
    'expires_in': 864000,
    'refresh_token': 'EUheu1580860191490f4GZWVz5sWH2hmS',
    'token_type': 'bearer'}
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': 'ECq7XADuDqzuAWTL',
                                      'name': 'Arrive Home'}],
                   'scenes': []}}

**Comment by milo526** [comment]
This API exposes no devices for your account.

The device you are trying to add can not be added through this plugin.

This is a limitation imposed by Tuya, sadly there is nothing I can do about this.

**Comment by chanyork** [comment]
i see thanks.

**Comment by eliassylvain** [comment]
Hello,

I am the same error on 2 ceiling light, there is still no solution ?

**Comment by milo526** [comment]
> Hello,
> 
> I have the same error on 2 ceiling lights, there is still no solution ?

Nothing has changed since my Jan 19th reply, sadly Tuya is phasing out this API thus it is very unlikely new devices will be supported. 
You might be better of by using the homebridge plugin that is designed by Tuya - https://github.com/tuya/tuya-homebridge that one does still receive updates from them.

I'd love to add support for new devices and create new functionality but my possibilities are very limited due to Tuya's way of dealing with this.

**Comment by eliassylvain** [comment]
Hello,

Thank you very much for this explication. This is too bad for us.

I'll try to use their plugin for these lights.
