### ISSUE TITLE
Support for single switch accessory with 2 channels to operate

### ISSUE THREAD

**Issue by Alperen-Ozturk** [milo526/homebridge-tuya-web#176]
**Is your feature request related to a problem? Please describe.**

I have some 2 channel Tuya wall switches. I control blinds with these wall switches. i.e. first channel is for blinds to go up and the second one is to go down. Tuya device id's for these type of devices are like [ID]_1 for channel 1 and [ID]_2 channel 2. These are configured like two separate accessories in HomeKit for each channel.

**Describe the solution you'd like**

Instead of having two accessories for each channel we might have a single accessory with two channel to control in HomeKit

**Additional context**

Current config
<img width="225" alt="Ekran Resmi 2021-01-19 16 05 19" src="https://user-images.githubusercontent.com/63194133/105039341-7ecb7780-5a71-11eb-8d92-3cb7a050db8a.png">

Requested config
<img width="127" alt="Ekran Resmi 2021-01-19 16 13 34" src="https://user-images.githubusercontent.com/63194133/105039412-986cbf00-5a71-11eb-8522-2f28033d50ed.png">

**Comment by milo526** [comment]
I would welcome a PR that implements this, however I do not have the capacity to implement this at the moment.

**Comment by mishendr** [comment]
I actually have the opposite problem. I have Tuya 2-Gang dimmer modules (MS-105B), which control 2 channels. However, I have only one ID from the Tuya/Smart Life app, and in HomeKit it is therefor seen as 1 dimmer. I can’t control the second channel (which is off course possible in the Smart Life app). How can I add both channels of the same Device ID to HomeBridge/HomeKit?

**Comment by Alperen-Ozturk** [comment]
@mishendr My channels were configured as ID_1 and ID_2. Just as you said there is only one ID for each device in Tuya mobile app but this plugin was seeing channels just as i mentioned, try that.  If it works it will expose two different accessories to HomeKit.  There is no way exposing it as a

**Comment by mishendr** [comment]
> @mishendr My channels were configured as ID_1 and ID_2. Just as you said there is only one ID for each device in Tuya mobile app but this plugin was seeing channels just as i mentioned, try that. If it works it will expose two different accessories to HomeKit. There is no way exposing it as a

**Comment by mishendr** [comment]
@Alperen-Ozturk Thanks for the quick reply! Unfortunately it doesn’t work. HomeBridge does not recognize it as a valid ID. It does however finds the device itself. Didn’t know it could do that btw.

“Tried overwriting device config for: “ 38341275c82b9648844c_1” which is not a valid device-ID or device-name”

**Comment by milo526** [comment]
The problem with these switches is that there is no way to get the state of the second switch.
For the first switch the plugin can know if you triggered it manually but that information is not exposed for the second switch.

**Comment by mishendr** [comment]
@milo526 Hi, well off course no problem, it’s not a paid job, I’m happy with all input, certainly yours off course. I understand, but Alperen-Ozturk does have a 2 channel “problem”, so it is possible with switches, not dimmers? Is that what you mean? I haven’t tried configuring them as switches yet (could do without the dimming part for now). Will report that when done.

B.t.w., do you think there will ever be support for Tuya smoke detectors?
