### ISSUE TITLE
status switch not updating in homebridge after physical turn on/off

### ISSUE THREAD

**Issue by mozzaLB** [milo526/homebridge-tuya-web#180]
**Describe the bug**
Really nice plugin and works great! I only have one issue with a 1 gang touch wall switch. When using the device physically the connected lights do turn on but the status in Homebridge/homekit does not update (status still off). When I use homebridge/homekit to turn on the switch everything works as expected. 

**Steps To Reproduce**
I just physically turn on the switch and lights are on but homebridge/homekit status does not change. operating the switch through homebridge/homekit works just fine.

**Plugin Version**
v0.7.1

 **Homebridge Config**
"platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "TuyaWebPlatform",
            "options": {
                "username": "*******",
                "password": "*****",
                "countryCode": "**",
                "platform": "tuya"
            },
            "defaults": [
                {
                    "id": "5003458298f4abeac02d",
                    "device_type": "climate",
                    "min_temper": "15",
                    "max_temper": "25",
                    "current_temperature_factor": "1",
                    "target_temperature_factor": "1"
                },
                {
                    "id": "bf8cee7e90d73e93fblfwx",
                    "device_type": "switch"
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        }
 
 **Device Config**
Getting devices
Got devices
{   u'header': {   u'code': u'SUCCESS', u'payloadVersion': 1},
    u'payload': {   u'devices': [   {   u'data': {   u'online': True,
                                                     u'state': False},
                                        u'dev_type': u'switch',
                                        u'ha_type': u'switch',
                                        u'icon': u'https://images.tuyaeu.com/smart/icon/ay15327721968035jwx9/159186441983323410445.gif',
                                        u'id': u'bf8cee7e90d73e93fblfwx',
                                        u'name': u'Schakelaar slaapkamer'},
                                    {   u'data': {   u'current_temperature': 21,
                                                     u'max_temper': 37,
                                                     u'min_temper': 0,
                                                     u'online': True,
                                                     u'state': u'true',
                                                     u'temperature': 21},
                                        u'dev_type': u'climate',
                                        u'ha_type': u'climate',
                                        u'icon': u'https://images.tuyaeu.com/smart/icon/1502103270_0.png',
                                        u'id': u'17050627e0980684d2cc',
                                        u'name': u'Your Eurom Heater'},
                                    {   u'data': {   u'current_temperature': 19,
                                                     u'max_temper': 37,
                                                     u'min_temper': 0,
                                                     u'online': True,
                                                     u'state': u'false',
                                                     u'temperature': 19},
                                        u'dev_type': u'climate',
                                        u'ha_type': u'climate',
                                        u'icon': u'https://images.tuyaeu.com/smart/product_icon/qn.png',
                                        u'id': u'5003458298f4abeac02d',
                                        u'name': u' Eurom Heater zolder'},
                                    {   u'data': {   },
                                        u'dev_type': u'scene',
                                        u'ha_type': u'scene',
                                        u'id': u'BX43kH5VE44xNyVC',
                                        u'name': u'\\" Eurom Heater zolder\\" Power:OFF'},
                                    {   u'data': {   },
                                        u'dev_type': u'scene',
                                        u'ha_type': u'scene',
                                        u'id': u'jXtLYpQeBYZitgek',
                                        u'name': u'\\" Eurom Heater zolder\\" Power:ON'},
                                    {   u'data': {   },
                                        u'dev_type': u'scene',
                                        u'ha_type': u'scene',
                                        u'id': u'3Vg3D8iKtSDJEhbV',
                                        u'name': u'\\"Your Eurom Heater\\" Power:OFF'},
                                    {   u'data': {   },
                                        u'dev_type': u'scene',
                                        u'ha_type': u'scene',
                                        u'id': u'8lj1OVk80ecA0QPt',
                                        u'name': u'\\"Your Eurom Heater\\" Power:ON'}],
                    u'scenes': []}}
 
 
 **Additional Context**

**Comment by milo526** [comment]
Hello,

This is sadly one of the issues that plagues this plugin that I cannot change.

Tuya severely limits how often this plugin can request the status of your devices.
Therefor it will look like the status in HomeKit is not updating.

It should have updated when you check again in 15 minutes.
Could you please check that for me?
Just be very patient and see if that does update the switch.

**Comment by mozzaLB** [comment]
Hi Milo, 

Thanks for your quick response. You are complete right, the status updates in homebridge/homekit after about 5min. Really strange though, this does not happen to both my electric heaters.

**Comment by milo526** [comment]
Glad to hear.

Sorry that it is not working as perfect as desired, however it is working as properly as possible.
Believe me that I would love to be able to do better, it is just not possible with this API.

**Comment by mozzaLB** [comment]
No worries! Plugin works great except for this glitch. Thanks for all the work you put into this!
