### ISSUE TITLE
Cannot set brightness / API changes?

### ISSUE THREAD

**Issue by jaketesler** [milo526/homebridge-tuya-web#182]
I think some recent changes to the Tuya API may be causing issues when polling certain states for lights (likely). That, or something in our specific light strips are causing weird problems with the API (unlikely). For reference, we have full control (brightness, color, color temp) when using the Tuya Smart app.

Our Homebridge log output (our light name is `Neon Left`):
```
[24/01/2021, 01:39:49] [TuyaWebPlatform] [Neon Left] - Unsetting debouncedDeviceStateRequestPromise
[24/01/2021, 01:39:49] [TuyaWebPlatform] [Neon Left] - Resolving resolveDeviceStateRequest from cache
[24/01/2021, 01:39:49] [TuyaWebPlatform] [Neon Left] Characteristic.On - [GET] true
[24/01/2021, 01:39:49] [TuyaWebPlatform] [Neon Left] Characteristic.Hue - [GET] undefined
[24/01/2021, 01:39:49] [TuyaWebPlatform] [Neon Left] Characteristic.ColorTemperature - [GET] undefined
[24/01/2021, 01:39:49] [TuyaWebPlatform] [Neon Left] Characteristic.Saturation - [GET] undefined
[24/01/2021, 01:39:49] [TuyaWebPlatform] [Neon Left] Characteristic.Brightness - [GET] undefined
[24/01/2021, 01:39:49] [TuyaWebPlatform] [Neon Left] Characteristic.Brightness - Tried to set brightness but failed to parse data. 
 { color_mode: 'colour', online: true, state: 'true' }
```
As you can see, when the plugin attempts to set the brightness it cannot parse the returned response. 

This is reproducible beginning when starting Homebridge; it's persistent and prevents controlling the device from within Homekit on iOS. 

We're using the most recent Homebridge (1.1.7) and the most recent plugin version (0.7.1). 

 **Homebridge Config**
```json
{
            "name": "TuyaWebPlatform",
            "options": {
                "username": XXX,
                "password": XXX,
                "countryCode": "1",
                "platform": "tuya"
            },
            "defaults": [
                {
                    "id": XXX,
                    "device_type": "light",
                    "light_characteristics": [
                        "Brightness",
                        "Color",
                        "Color Temperature"
                    ]
                },
                {
                    "id": XXX,
                    "device_type": "light",
                    "light_characteristics": [
                        "Brightness",
                        "Color",
                        "Color Temperature"
                    ]
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        }
```
 
 **Device Config**
```
Getting credentials
Got credentials
{   u'access_token': XXX,
    u'expires_in': 864000,
    u'refresh_token': XXX,
    u'token_type': u'bearer'}
Getting devices
Got devices
{   u'header': {   u'code': u'SUCCESS', u'payloadVersion': 1},
    u'payload': {   u'devices': [   {   u'data': {   u'color_mode': u'colour',
                                                     u'online': True,
                                                     u'state': u'true'},
                                        u'dev_type': u'light',
                                        u'ha_type': u'light',
                                        u'icon': u'https://images.tuyaus.com/smart/icon/ay1514364649128b8REf/1586840521955342e8a6d.png',
                                        u'id': XXX,
                                        u'name': u'Neon Right'},
                                    {   u'data': {   u'color_mode': u'colour',
                                                     u'online': False,
                                                     u'state': u'true'},
                                        u'dev_type': u'light',
                                        u'ha_type': u'light',
                                        u'icon': u'https://images.tuyaus.com/smart/icon/ay1514364649128b8REf/1586840521955342e8a6d.png',
                                        u'id': XXX,
                                        u'name': u'Neon Left'}],
                    u'scenes': []}}
```

**Comment by mongolianmiller** [comment]
Same issue. Like... basically the exact same issue. LED light strips, Smart Life App lets me set the brightness etc -- this stopped working in Homekit/Homebridge with the same error messages that @jaketesler presented above.

**Comment by milo526** [comment]
So to clarify, the lights have worked properly for you before?

I just tested my own lights again and everything works as expected.

**Comment by jaketesler** [comment]
@milo526 I can’t speak for @mongolianmiller, but we were setting up our lights for the first time when we encountered this issue. 

What lights are you using (the product name)? We’re using Monster Illuminessence but controlled through the Tuya app instead of the Monster app. (Successfully, I might add)

**Comment by milo526** [comment]
That leads me to conclude that your lights are not fully supported by this API.

I believe that you are able to control them through the Tuya app - however that has very little to do with wether or not you can control them through this API.

The api that this plugin uses is not at all the same as the Tuya app uses.

Many devices are badly or not at all supported in this API.

This is a limitation from Tuya and not something I can change sadly

**Comment by jaketesler** [comment]
Wait a minute! 

@mongolianmiller said their lights stopped working recently. It could be an API change. 

@milo526 you’re fairly quick to assume it’s the product but Tuya OEMs their lights – it’s actually the same LED strips regardless of vendor. So it should work with the API. 

I’d request you reopen this issue. In the case I’m right, it seems like a trivial fix to accept additional fields in the JSON response (either due to an API change or for some other reason). In the case you’re correct I’d also be happy to open a PR to support these strips. 

But in either case this _is_ a problem, I think closing the issue was a bit premature.

**Comment by milo526** [comment]
> @mongolianmiller said their lights stopped working recently. It could be an API change.

This was regarding your device, if their case is different they can open a new issue discussing their case - that way we can keep the issues clean and concise.

> @milo526 you’re fairly quick to assume it’s the product but Tuya OEMs their lights – it’s actually the same LED strips regardless of vendor.

True, Tuya does OEM their lights, it is however not "the same device", tuya sells different versions, Tuya sells complete systems and Tuya sells separate chips. Any combination of these could lead to a different output.

> So it should work with the API.

Clearly it doesn't - and other similar devices do still support these operations, that makes it strongly seem like it is product specific.

> I’d request you reopen this issue.

At the moment I have no reason to do this.

> In the case I’m right, it seems like a trivial fix to accept additional fields in the JSON response (either due to an API change or for some other reason).

I don't understand what you are getting at, you uploaded your JSON response, there is no new data. We can clearly see that the API output from your device does not contain brightness.

> In the case you’re correct I’d also be happy to open a PR to support these strips.

Awesome, however you will need to change something on Tuya's servers. I do not work for Tuya, if you do, please let me know, we can make a lot of people happy if we can talk to one of their developers that works on this API!
I have not yet found the source-code for their API to which I can send a PR.

> But in either case this is a problem,

I can see why you think this is a problem, however I have strong reasons to believe that this is not a problem with the plugin. Since my time is severely limited I cannot help you with problems that are not with my plugin.

> I think closing the issue was a bit premature.

That is fine, you are entitled to your opinions. However I have had many people complain about this before. In all cases it turned out that the device was not fully supported by the API and that neither I nor the other party could do anything to change that.
Coming back to my limited time I'd rather not walk this path again.
Furthermore this issue is not locked thus you should still be able to respond to it.
Providing me with more and new information will probably lead to me reconsidering this.

**Comment by mongolianmiller** [comment]
@milo526 - I just updated all my Homebridge / Plugins, and inserted the ID's proper into the plugin. The brightness and colors are controllable with my lightstrips! Yay!  (I still get the same errors in Homebridge, see below, but, I guess I don't care as long as its working, lol)

```
[1/8/2022, 4:45:30 PM] [TuyaWebPlatform] [Lily’s Desk] Characteristic.Brightness - Tried to set brightness but failed to parse data. 
 { color_mode: 'colour', online: true, state: 'true' }
[1/8/2022, 4:45:30 PM] [TuyaWebPlatform] [Asher’s Desk] Characteristic.Brightness - Tried to set brightness but failed to parse data. 
 { color_mode: 'colour', online: true, state: 'true' }
```
