### ISSUE TITLE
Support for Diffuser and IR Controller

### ISSUE THREAD

**Issue by ariknil** [milo526/homebridge-tuya-web#190]
Hi!!

I would like tha the plug in support devices like diffuser with changing color lights and WiFi Infrared Controller.

**Comment by milo526** [comment]
Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

Without this it is hard for me to help you with regards to this specific issue.
