### ISSUE TITLE
Device dont respond to switches in the home app

### ISSUE THREAD

**Issue by tolyadzn** [milo526/homebridge-tuya-web#193]
Hello I added today a new device to my homebridge through your plugin. It is normally recognized in the home app. I can turn the light off and on in the home app, but the actual lamp dont show any functions. Here is the output:

Getting credentials
Got credentials
{   'access_token': 'EUheu1612438242581bv51bUSwOiB4soI',
    'expires_in': 864000,
    'refresh_token': 'EUheu1612438242581bv51bvo8nfGWSwf',
    'token_type': 'bearer'}
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {   'brightness': '255',
                                                  'color_mode': 'white',
                                                  'online': True,
                                                  'state': 'false'},
                                      'dev_type': 'light',
                                      'ha_type': 'light',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/153313677215sora6tszu_0.png',
                                      'id': '58032557bcddc2201842',
                                      'name': 'Lampe Wohnbereich'}],
                   'scenes': []}}
!!! NOW REMOVE THIS FILE, SO YOUR CREDENTIALS (username, password) WON'T LEAK !!!
Thanks

**Comment by milo526** [comment]
Have you tried the standard stuff.

Switching on and off the power of the light
Rebooting your homebridge/hoobs instance.
Do changes via the Tuya (or smart life) app work?
