### ISSUE TITLE
Getting Cannot read property 'context' of undefined on start

### ISSUE THREAD

**Issue by ttopholm** [milo526/homebridge-tuya-web#194]
Hi, getting the above error on start up: 

`[2/5/2021, 3:03:05 PM] [TuyaWebPlatform] Cannot read property 'context' of undefined`

Here is my config:

`{
            "name": "TuyaWebPlatform",
            "options": {
                "username": "XXXX",
                "password": "XXXX",
                "countryCode": "45",
                "platform": "tuya"
            },
            "defaults": [
                {
                    "id": "XXXX",
                    "device_type": "cover"
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        }`

**Comment by milo526** [comment]
Are you by any chance running the homebridge beta?

This was just reported in #158 so I suspect it is the same problem?

**Comment by ttopholm** [comment]
No, using 1.2.5 and @milo526/homebridge-tuya-web v0.8.0-0

**Comment by ttopholm** [comment]
Downgraded to 0.7.1 and then it works....

**Comment by milo526** [comment]
Awesome, thanks for reporting - will look into this.

**Comment by ttopholm** [comment]
Hmm.. after I upgraded from 0.7.1 to 0.8.0 the error is gone... so it seems the error is there when you do a fresh installation of 0.8.0, but if you downgrade and then upgrade it works fine

**Comment by milo526** [comment]
This is fixed in b402d9c673936ce06d03f1a0cb370b7e7e4a544e and will be released in a new update shortly.
