### ISSUE TITLE
Can't connect Tuya switch

### ISSUE THREAD

**Issue by snorbik** [milo526/homebridge-tuya-web#198]
Hi Milo, 

i am trying to get my Tuya switch connected via your plugin, but unfortunately I get the following error in the log. Using latest version of HOOBS and latest version of your plugin.

`[TuyaWebPlatform] Tried overwriting device config for: "bf85a____________ddac" which is not a valid device-id or device-name.`

I have tried to verify if my account is showing this device and everything seems fine. Sending output below:

`Getting credentials
Got credentials
{   'access_token': 'REDACTED',
    'expires_in': 864000,
    'refresh_token': 'REDACTED',
    'token_type': 'bearer'}
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/ay15422864509092y6k8/160371793060f7ad00bff.png',
                                      'id': 'bf85a____________ddac',
                                      'name': 'Switch'}],
                   'scenes': []}}
!!! NOW REMOVE THIS FILE, SO YOUR CREDENTIALS (username, password) WON'T LEAK !!!`

Can you help, please?

**Comment by milo526** [comment]
Could you try to see if it works if you use the name instead of the ID?

Why are you even trying to overwrite? It should also work just fine if you remove the whole defaults section from your config.

**Comment by milo526** [comment]
I am unable to reproduce this issue.
Please make sure you entered the device ID correctly or use the device name instead.

**Comment by snorbik** [comment]
Hi Milo, 

today I have finally found time to reinstall HOOBS and your plugin. Now I tried to do it as you suggest, but I still can't see any accessories in my HOOBS.

Through the Python script I can see all my devices and their current settings, but nothing is transferred to HOOBS.

[Screenshot here](https://ibb.co/bKhYvYB)

**Comment by snorbik** [comment]
I finally found it. The issue was, that I was keeping FORM in my settings (maybe dropdown with possibilities) or description with mostly used ones would be helpful.
