### ISSUE TITLE
Keine Geräte in der Homebridge

### ISSUE THREAD

**Issue by ThomaspunktS** [milo526/homebridge-tuya-web#199]
Evening together.

I have the following problem. On the Synology NAS is running Docker and I have set up the Homebridge.

Shellys, Fritz devices and even the Denon AVR run smoothly, are displayed in the Homebridge and can be controlled via Apple's Homekit.

Now I got myself the Lidl Zigbee gateway, several outlets and motion detectors. I installed the Tuya app, set up access, and installed the Tuya web plugin for the Homebridge. I had no success with the Lidl app out the back as well.

However, after installing and setting up the plugin, I don't see any devices in the Homebridge. As a beginner I was already maöl proud to get the other plugins to run. However, with the Tuyainstallation I bite my teeth out.

Here is my config:

{
            "name": "TuyaWebPlatform",
            "options": {
                "username": "xxxxxxxxxx",
                "password": "xxxxxxxxxx",
                "countryCode": "49",
                "platform": "tuya"
            },
            "defaults": [
                {
                    "id": "bff48ca632c255b834lkdh",
                    "device_type": "outlet"
                },
                {
                    "id": "bf256f42e7ae902e57ykva",
                    "device_type": "outlet"
                },
                {
                    "id": "bfd0a58bb8dab87f025t0f",
                    "device_type": "switch"
                }
            ],
            }, "scenes": false,
            "platform": "TuyaWebPlatform"
        }

What am I doing wrong here, or where is my thinking error? Am I maybe doing the whole thing fundamentally wrong?
I am glad about any hint or tip!

Greetings
Thomas

**Comment by milo526** [comment]
Please write any communication in English.

**Comment by ThomaspunktS** [comment]
Evening together.

I have the following problem. On the Synology NAS is running Docker and I have set up the Homebridge.

Shellys, Fritz devices and even the Denon AVR run smoothly, are displayed in the Homebridge and can be controlled via Apple's Homekit.

Now I got myself the Lidl Zigbee gateway, several outlets and motion detectors. I installed the Tuya app, set up access, and installed the Tuya web plugin for the Homebridge. I had no success with the Lidl app out the back as well.

However, after installing and setting up the plugin, I don't see any devices in the Homebridge. As a beginner I was already maöl proud to get the other plugins to run. However, with the Tuyainstallation I bite my teeth out.

Here is my config:

{
            "name": "TuyaWebPlatform",
            "options": {
                "username": "xxxxxxxxxx",
                "password": "xxxxxxxxxx",
                "countryCode": "49",
                "platform": "tuya"
            },
            "defaults": [
                {
                    "id": "bff48ca632c255b834lkdh",
                    "device_type": "outlet"
                },
                {
                    "id": "bf256f42e7ae902e57ykva",
                    "device_type": "outlet"
                },
                {
                    "id": "bfd0a58bb8dab87f025t0f",
                    "device_type": "switch"
                }
            ],
            }, "scenes": false,
            "platform": "TuyaWebPlatform"
        }



What am I doing wrong here, or where is my thinking error? Am I maybe doing the whole thing fundamentally wrong?
I am glad about any hint or tip!



Greetings
Thomas

**Comment by milo526** [comment]
Hello, 
Good Evening to you too.

Sadly the zigbee hub is not supported (tuya limitation)

You should however be able to see your power plugs.

What version of the plugin are you running?

**Comment by ThomaspunktS** [comment]
Okay, I am using version 0.71

I have now gone through other plug-ins and can't reach the goal.

With the Hue Bridge, I can switch the sockets and integrate them into HomeKit. Unfortunately, only as lamps and not as sockets.

**Comment by milo526** [comment]
If they work with the Hue Bridge, they are ZigBee devices and not WiFi devices. these will therefor not work with this plugin.
This is a limitation imposed by Tuya that I cannot change.
