### ISSUE TITLE
Fan not showing

### ISSUE THREAD

**Issue by AndrewJ1990** [milo526/homebridge-tuya-web#2]
I have a ceiling fan added to the Smartlife app, but it is not showing in Homebridge. All the other accessories in the app are, however not the ceiling fan.

**Comment by emland89** [comment]
I have the same issue, what if scenes are implemented for this type of cases where devices are not supported, like having scenes as switches, at least we could have the device working somehow

**Comment by milo526** [comment]
Hello, could you please let me know if you have any errors in your logs when you restart homebridge?
