### ISSUE TITLE
Cache not being cleared?

### ISSUE THREAD

**Issue by wills721** [milo526/homebridge-tuya-web#202]
**Describe the bug**

I have removed the persist folder 'by hand' and I have also tried the reset connection under help.  Yet still when tuya-web plugin launches the logs show it is finding accessories from the cache?

"2/18/2021, 5:02:55 AM Got SIGINT, shutting down Bridge...
2/18/2021, 5:03:10 AM Persist directory removed.
2/18/2021, 5:03:13 AM Persist directory removed.
2/18/2021, 5:03:28 AM Loaded plugin '@milo526/homebridge-tuya-web'
2/18/2021, 5:03:28 AM [2/18/2021, 10:03:28 AM] Registering platform 'milo526/homebridge-tuya-web.TuyaWebPlatform'
2/18/2021, 5:03:28 AM Loading 1 platforms...
2/18/2021, 5:03:28 AM [TuyaWebPlatform] Initializing TuyaWebPlatform platform...
2/18/2021, 5:03:28 AM [TuyaWebPlatform] Loading accessory from cache: Train outlet
2/18/2021, 5:03:28 AM [TuyaWebPlatform] Loading accessory from cache: Georgia Fan
2/18/2021, 5:03:28 AM [TuyaWebPlatform] Loading accessory from cache: Kitchen overhead light
2/18/2021, 5:03:28 AM [TuyaWebPlatform] Loading accessory from cache: Basement Door light
2/18/2021, 5:03:28 AM [TuyaWebPlatform] Loading accessory from cache: Kitchen chandalier
2/18/2021, 5:03:28 AM [TuyaWebPlatform] Loading accessory from cache: Basement stair light
2/18/2021, 5:03:28 AM [TuyaWebPlatform] Loading accessory from cache: Brian Fan
2/18/2021, 5:03:28 AM [TuyaWebPlatform] Loading accessory from cache: Brian night light
2/18/2021, 5:03:28 AM [TuyaWebPlatform] Loading accessory from cache: Foyer outlet
2/18/2021, 5:03:28 AM [TuyaWebPlatform] Loading accessory from cache: Living Room light
2/18/2021, 5:03:28 AM [TuyaWebPlatform] Loading accessory from cache: Ensley Fan
2/18/2021, 5:03:28 AM [TuyaWebPlatform] Loading accessory from cache: Georgia Bed Light
2/18/2021, 5:03:28 AM [TuyaWebPlatform] Loading accessory from cache: Chandelier light 
2/18/2021, 5:03:28 AM [TuyaWebPlatform] Loading accessory from cache: Georgia Dressor Light
2/18/2021, 5:03:28 AM [TuyaWebPlatform] Loading accessory from cache: Kitchen counter light"

**Steps To Reproduce**
Remove cache and restart -- cache still found. 

**Plugin Version**
Latest hoobs installation
 
 **Homebridge Config**
 
```json
{
    "server": {
        "port": 8088,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYMNAJ",
        "polling_seconds": 5,
        "docker": true
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "91:1B:A7:A4:D5:93"
    },
    "description": "",
    "ports": {},
    "plugins": [
        "homebridge-tuya-web"
    ],
    "accessories": [],
    "platforms": [
        {
            "platform": "TuyaWebPlatform",
            "plugin_map": {
                "plugin_name": "homebridge-tuya-web"
            },
            "name": "TuyaWebPlatform",
            "scenes": false,
            "options": {
                "platform": "tuya",
                "username": "****",
                "password": "****",
                "countryCode": "1",
                "pollingInterval": 600
            }
        }
    ],
    "package_manager": "npm",
    "system": "hoobs"
}
```
 
 **Additional Context**

**Comment by milo526** [comment]
Why do you want to clear the cache? This should not be needed.

However if you are sure this is what you want;

At the same level of the `persists` folder there should be an `accessories` folder. This folder contains a `cachedAccessories` file.

This is a JSON file in which the device cache is stored.
You can remove this file to clear the cache that you saw, please notice that removing this file will also clear the device cache for other plugins!

**Comment by wills721** [comment]
I've done that.  In fact,  I've removed the entire persist folder and restarted hoobs.  Yet still,  it shows that it is finding accessories in the cache.

**Comment by milo526** [comment]
The accessories folder is not inside the persists folder.

**Comment by wills721** [comment]
admin@Spies-Cloud:/volume2/docker/hoobs/etc$ ls
access.json  config.json  dashboard.json  layout.json  persist
admin@Spies-Cloud:/volume2/docker/hoobs/etc$

I do not have such a folder?

**Comment by milo526** [comment]
> hoobs@hoobs:/home/hoobs/.hoobs/etc $ ls
> access.json  accessories  config.json  dashboard.json  layout.json  persist

That is interesting cause I do

**Comment by wills721** [comment]
I run hoobs on Synology NAS w/in Docker.  Could this be why?

**Comment by milo526** [comment]
That shouldn't matter.

Removing the directories on my local install also did not seem to remove the cache - I will look into this when I have some time later.

**Comment by wills721** [comment]
Thank you

**Comment by wills721** [comment]
FWIW:

admin@Spies-Cloud:/volume2$ sudo find . -name "accessories"
Password:
./docker/hoobs/node_modules/@milo526/homebridge-tuya-web/dist/accessories
./@docker/btrfs/subvolumes/9c94b477e23e84f7e7d90229dc5fd1cddbf61a60fe97c56e38bd1e21426daae8/usr/src/hoobs/node_modules/hap-nodejs/dist/accessories
./@docker/btrfs/subvolumes/c878228243a5eb025852ef5a25b3dab8760d9ac92edb5d00eb1df2ded772c311/usr/src/hoobs/node_modules/hap-nodejs/dist/accessories
./@docker/btrfs/subvolumes/fe2a3dd204024314e43d43c1afe1bab0c33fbbdf29a8d848db2dccd9948675ee/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/accessories
./@docker/btrfs/subvolumes/8368abfb9ca30d139fa9c8c235a1b2828654a453e2a1a998f5ee1f05950dd059/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/accessories
./@docker/btrfs/subvolumes/8368abfb9ca30d139fa9c8c235a1b2828654a453e2a1a998f5ee1f05950dd059/usr/local/lib/node_modules/homebridge-config-ui-x/dist/modules/accessories
./@docker/btrfs/subvolumes/99645a609edfb2f250b281a6d232e44e16efd14a926eeb90868061dc1e3984f7/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/accessories
./@docker/btrfs/subvolumes/99645a609edfb2f250b281a6d232e44e16efd14a926eeb90868061dc1e3984f7/usr/local/lib/node_modules/homebridge-config-ui-x/dist/modules/accessories
./@docker/btrfs/subvolumes/3303d0d487f39c9d4f69ef269e050b6b1178d31512a77b9d18e8908a1bdfe51b-init/usr/src/hoobs/node_modules/hap-nodejs/dist/accessories
./@docker/btrfs/subvolumes/3303d0d487f39c9d4f69ef269e050b6b1178d31512a77b9d18e8908a1bdfe51b/root/.hoobs/etc/accessories
./@docker/btrfs/subvolumes/3303d0d487f39c9d4f69ef269e050b6b1178d31512a77b9d18e8908a1bdfe51b/usr/src/hoobs/node_modules/hap-nodejs/dist/accessories
admin@Spies-Cloud:/volume2$

**Comment by milo526** [comment]
Going to the help menu (via the 3 dots at the top right) you can see a "Reset connection" button.

This will clear the relevant cache for you.

After this you will need to re-link with your home app by scanning the QR-code.

Please notice that this might remove your devices from scenes and automations.

**Comment by wills721** [comment]
As I mentioned above -- I have also tried this several times.  The cache still does not go away.
