### ISSUE TITLE
Double Power Point - only top plug exposed to HK

### ISSUE THREAD

**Issue by DaveM8686** [milo526/homebridge-tuya-web#205]
**Describe the bug**

I have a Tuya double adaptor smart plug.  It has two vertically stacked plug points and one physical master button.  In the Tuya app, it shows as two individual points with individual control.  When brought over to HomeBridge / HomeKit, only the top power point is exposed.  The bottom one does not appear.  Toggling the power point definitely only affects the top one, so it's not the Master Switch that's coming through.

**Steps To Reproduce**

1. Add a double power point to Tuya, such as one like this: https://www.kmart.com.au/product/mirabella-genio-wi-fi-double-power-plug-with-usb-ports/3294803
2. Add this plugin to HomeBridge
3. Check in HomeKit if only one or both plugs are installed

**Plugin Version**
 

1.0.0 

 **Homebridge Config**
 
 
 ```json
{
            "name": "TuyaWebPlatform",
            "options": {
                "username": "REDACTED",
                "password": "REDACTED",
                "countryCode": "REDACTED",
                "platform": "tuya",
                "pollingInterval": 10
            },
            "defaults": [
                {
                    "id": "00033161ecfabc5df379",
                    "device_type": "outlet"
                },
                {
                    "id": "00033161ecfabc5de81b",
                    "device_type": "outlet"
                },
                {
                    "id": "42555720b8f0090167d2",
                    "device_type": "outlet"
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        }

```
 
 **Device Config**
 
 
Getting credentials
Got credentials
{   'access_token': 'EUheu1595376439660nlmpSRUG6hn8LMt',
    'expires_in': 864000,
    'refresh_token': 'EUheu1595376439660nlmpSQCfPsTzYEk',
    'token_type': 'bearer'}
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/ay1533773342993pM7Be/157061699335d83bfe93b.jpg',
                                      'id': '00033161ecfabc5de7e6',
                                      'name': 'Front Door Light'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/ay1533773342993pM7Be/157061699335d83bfe93b.jpg',
                                      'id': '00033161ecfabc5de81b',
                                      'name': 'Lizz’s Electric Blanket'},
                                   {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/ay1568595969438ERU1j/1605067399e398661413c.png',
                                      'id': '42555720b8f0090167d2',
                                      'name': 'Garage Double Plug'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/ay1533773342993pM7Be/157061699335d83bfe93b.jpg',
                                      'id': '00033161ecfabc5df379',
                                      'name': 'David’s Electric Blanket'},
                                  {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': 'qEZmGyVieMA2bbOS',
                                      'name': 'If Schedule:7:05 am Every '
                                              'day,\\"HeimVision N600S\\" '
                                              'ON/OFF:OFF'}],
                   'scenes': []}}
!!! NOW REMOVE THIS FILE, SO YOUR CREDENTIALS (username, password) WON'T LEAK !!!

 **Additional Context**
 
In regards to the output above, the item in question is the "Garage Double Plug".

**Comment by milo526** [comment]
Sadly this is not supported through the API that this plugin uses.

**Comment by DaveM8686** [comment]
Thanks for the info.  I've switched over to the Tuya LAN protocol instead, as it is supported through there.  A bit fiddlier to set up each time, but the double power point was kind of vital for me.  Hopefully the API can be updated at some point soon and I can come back to this one.
