### ISSUE TITLE
Status on,  off

### ISSUE THREAD

**Issue by fabiohblage** [milo526/homebridge-tuya-web#206]
Hello, @milo526 

I'm doing bench tests with SMARTLIFE,

I realized that when I turn the light on manually by the switch,

status on or off is not received on homebrige.

**Comment by milo526** [comment]
Please make sure you have a polling interval defined in your config file.

It will then update after max 5 minutes (or longer if you define a longer polling interval)

I know this is not ideal but it is the best I can do given the API that this plugin is using.

**Comment by fabiohblage** [comment]
What smaller range can I use? 

@milo526

**Comment by milo526** [comment]
Any range you want, however the plugin will overwrite it and set it to 605 seconds.

Any value below 605 will be set to 605, any value above will be respected.
Any faster and the plugin will actually work worse.

**Comment by fabiohblage** [comment]
Is it possible to use your local (lan) plugin and get a faster response?

**Comment by milo526** [comment]
I don't have a local lan plugin? But by all means switch to the [homebridge-tuya-lan](https://www.npmjs.com/package/homebridge-tuya-lan) plugin if that suits your needs better!
