### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by mrmillennium** [milo526/homebridge-tuya-web#21]
I’m using as a platform smart_life 
In the field username and password I put what usually do for entering the service.. here it says that password or username is incorrect I retried several times and obtained always the same result.. in the app I enter with no issue.
Thank you for your help

**Comment by milo526** [comment]
Hello,

I'm sorry to hear this but to be blunt; At least one of the assumptions you make is incorrect. There are no other mentions of this issue. I just verified sign-up on my personal homebridge at that works exactly as expected.

So please double check that you enter your username and password correct and that you are using the SmartLife platform.
The platform you are supposed to enter in your homebridge platform is related to the app that your account is registered at. 
Please also make sure that your country code matches and is not prefixed with the `+` sign.

**Comment by mbierman** [comment]
@mrmillennium have you correctly set  "platform":  correctly? Tuya has many separate companies that use their code. If your account is with smart_life but you set this to another like tuya your account won't be recognized.

**Comment by mrmillennium** [comment]
Yes, I’ve checked many times the information, also the platform i was sure about smart life but just for being sure I’ve changed between tuya and jinvoo.. but I’m receiving the same error code
Does it matter if I’ve registered to the app smart life with Sign In with Apple and then created a login?
Maybe could be that
Thank you
Il 23 giu 2020, 20:44 +0200, milo526/homebridge-tuya-web <reply@reply.github.com>, ha scritto:
>
> enter

**Comment by mbierman** [comment]
To register the devices you need an app. To use that app, you need to set up an account. After you have configured all your Tuya based devices in an app, use those credentials in this plugin and you should be good.

**Comment by milo526** [comment]
> Yes, I’ve checked many times the information, also the platform i was sure about smart life but just for being sure I’ve changed between tuya and jinvoo.. but I’m receiving the same error code Does it matter if I’ve registered to the app smart life with Sign In with Apple and then created a login? Maybe could be that Thank you Il 23 giu 2020, 20:44 +0200, milo526/homebridge-tuya-web <reply@reply.github.com>, ha scritto:
> […](#)

The problem could actually be with the "Sign In with Apple" since Apple will then send a random email adres during the setup progress; you will then need this random email adres to setup this app since Tuya/smartlife/jinvoo don't know your real email only the generated once.

**Comment by mbierman** [comment]
> The problem could actually be with the "Sign In with Apple" since Apple will then send a random email adres during the setup progress; you will then need this random email adres to setup this app since Tuya/smartlife/jinvoo don't know your real email only the generated once.

That makes sense. I've avoided using "sign in with Apple" so far so it didn't occur to me. :)

**Comment by ROBrownsmith** [comment]
> > Yes, I’ve checked many times the information, also the platform i was sure about smart life but just for being sure I’ve changed between tuya and jinvoo.. but I’m receiving the same error code Does it matter if I’ve registered to the app smart life with Sign In with Apple and then created a login? Maybe could be that Thank you Il 23 giu 2020, 20:44 +0200, milo526/homebridge-tuya-web [reply@reply.github.com](mailto:reply@reply.github.com), ha scritto:
> > […](#)
> 
> The problem could actually be with the "Sign In with Apple" since Apple will then send a random email adres during the setup progress; you will then need this random email adres to setup this app since Tuya/smartlife/jinvoo don't know your real email only the generated once.

This happened to me too. After setting up with appleID I realised my mistake and then tried to bind my proper email to the account but the api still wouldn't recognise the credentials. I solved the situation by creating a new Tuya account using a secondary email address where I could receive the Tuya verification codes. Thank you for your work.

**Comment by milo526** [comment]
Glad it is solved

**Comment by BytSerk** [comment]
> > > Yes, I’ve checked many times the information, also the platform i was sure about smart life but just for being sure I’ve changed between tuya and jinvoo.. but I’m receiving the same error code Does it matter if I’ve registered to the app smart life with Sign In with Apple and then created a login? Maybe could be that Thank you Il 23 giu 2020, 20:44 +0200, milo526/homebridge-tuya-web [reply@reply.github.com](mailto:reply@reply.github.com), ha scritto:
> > > […](#)
> > 
> > 
> > The problem could actually be with the "Sign In with Apple" since Apple will then send a random email adres during the setup progress; you will then need this random email adres to setup this app since Tuya/smartlife/jinvoo don't know your real email only the generated once.
> 
> This happened to me too. After setting up with appleID I realised my mistake and then tried to bind my proper email to the account but the api still wouldn't recognise the credentials. I solved the situation by creating a new Tuya account using a secondary email address where I could receive the Tuya verification codes. Thank you for your work.

I have an issue with login error after login through apple id 

solved by this comment great
