### ISSUE TITLE
tuya plugin has error on my hoobs. would you help?

### ISSUE THREAD

**Issue by ericwongmusic** [milo526/homebridge-tuya-web#231]
Hi! My Tuya plugin keep showing error messages, can you advice how to solve it? Thanks! Here the messages:

2/27/2021, 5:48:56 AM [TuyaWebPlatform] [MacBook Pro] - Unsetting debouncedDeviceStateRequestPromise
2/27/2021, 5:48:56 AM [TuyaWebPlatform] [MacBook Pro] - Resolving resolveDeviceStateRequest from cache
2/27/2021, 5:48:56 AM [TuyaWebPlatform] [MacBook Pro] Characteristic.On - [GET] true
2/27/2021, 5:48:56 AM [TuyaWebPlatform] [香薰機] - Unsetting debouncedDeviceStateRequestPromise
2/27/2021, 5:48:56 AM [TuyaWebPlatform] [香薰機] - Resolving resolveDeviceStateRequest from cache
2/27/2021, 5:48:56 AM [TuyaWebPlatform] [香薰機] Characteristic.On - [GET] false
2/27/2021, 5:48:56 AM [TuyaWebPlatform] [投影機] - Unsetting debouncedDeviceStateRequestPromise
2/27/2021, 5:48:56 AM [TuyaWebPlatform] [投影機] - Resolving resolveDeviceStateRequest from cache
2/27/2021, 5:48:56 AM [TuyaWebPlatform] [投影機] Characteristic.On - [GET] false
2/27/2021, 5:48:56 AM [TuyaWebPlatform] [USB] - Unsetting debouncedDeviceStateRequestPromise
2/27/2021, 5:48:56 AM [TuyaWebPlatform] [USB] - Resolving resolveDeviceStateRequest from cache
2/27/2021, 5:48:56 AM [TuyaWebPlatform] [USB] Characteristic.On - [GET] true
2/27/2021, 5:48:56 AM [TuyaWebPlatform] [Smart Socket 1] - Unsetting debouncedDeviceStateRequestPromise
2/27/2021, 5:48:56 AM [TuyaWebPlatform] [Smart Socket 1] - Resolving resolveDeviceStateRequest from cache
2/27/2021, 5:48:56 AM [TuyaWebPlatform] [Smart Socket 1] Characteristic.On - [GET] false
2/27/2021, 5:48:56 AM [TuyaWebPlatform] [Smart Socket 2] - Unsetting debouncedDeviceStateRequestPromise
2/27/2021, 5:48:56 AM [TuyaWebPlatform] [Smart Socket 2] - Resolving resolveDeviceStateRequest from cache
2/27/2021, 5:48:56 AM [TuyaWebPlatform] [Smart Socket 2] Characteristic.On - [GET] false
2/27/2021, 5:48:56 AM [TuyaWebPlatform] [電暖毯（中）] - Unsetting debouncedDeviceStateRequestPromise
2/27/2021, 5:48:56 AM [TuyaWebPlatform] [電暖毯（中）] - Resolving resolveDeviceStateRequest from cache
2/27/2021, 5:48:56 AM [TuyaWebPlatform] [電暖毯（中）] Characteristic.On - [GET] false
2/27/2021, 5:48:56 AM [TuyaWebPlatform] [電暖毯（左）] - Unsetting debouncedDeviceStateRequestPromise
2/27/2021, 5:48:56 AM [TuyaWebPlatform] [電暖毯（左）] - Resolving resolveDeviceStateRequest from cache
2/27/2021, 5:48:56 AM [TuyaWebPlatform] [電暖毯（左）] Characteristic.On - [GET] false
2/27/2021, 5:48:56 AM [TuyaWebPlatform] [Switch 3] - Unsetting debouncedDeviceStateRequestPromise
2/27/2021, 5:48:56 AM [TuyaWebPlatform] [Switch 3] - Resolving resolveDeviceStateRequest from cache
2/27/2021, 5:48:56 AM [TuyaWebPlatform] [Switch 3] Characteristic.On - [GET] false

**Describe the bug**

**Steps To Reproduce**

**Plugin Version**
 
 
 **Homebridge Config**
 
 
 ```json

```
 
 **Device Config**
 
 
 **Additional Context**

**Comment by milo526** [comment]
I'm missing a lot of information here, most importantly the error.

Everything that you show is info logging, no errors.
