### ISSUE TITLE
Moes 2 gang dimmer

### ISSUE THREAD

**Issue by JossiBD** [milo526/homebridge-tuya-web#232]
Hi there,

I’m using the Moes 2 Gang dimmer to control my led lights. 
The dimmer enables to control two different devices under two different switches (2 Gang). 
The dimmer is associated to the smartlife app and To Alexa and although I can see the two switches under those apps, I can see only one of the switches under Homebridge. 
I removed the dimmer and reinstalled it again but it didn’t solve the problem. 
please advise. 

Joseph

**Describe the bug**

**Steps To Reproduce**

**Plugin Version**
 
 
 **Homebridge Config**
 
 
 ```json

```
 
 **Device Config**
 
 
 **Additional Context**

**Comment by milo526** [comment]
This functionality is not supported by the API that this device is using, sadly there is nothing I can do for you.

You could look into using one of the other Tuya homebridge plugins.
