### ISSUE TITLE
Thermostat problem

### ISSUE THREAD

**Issue by starec007** [milo526/homebridge-tuya-web#233]
I have a Tuya thermostat and it doesn't display me properly at all. I also entered the ID from the application, but still nothing. The homebridge can only be turned on and off. I don't see the current temperature at all and I can't even set the melting temperature.
This is mi log

"defaults": [
                {
                    "id": "bf48f7aefb5fd50efe3afv",
                    "device_type": "climate",
                    "min_temper": "5.0",
                    "max_temper": "50.0",
                    "current_temperature_factor": "0.1",
                    "target_temperature_factor": "0.1"

**Comment by milo526** [comment]
Please follow the issue template.
