### ISSUE TITLE
choosing home

### ISSUE THREAD

**Issue by Witar23** [milo526/homebridge-tuya-web#235]
Is there a way to only link devices to HomeKit from one home
in SmartLife tool I have created 2 homes, but I need to link only one to HomeKit, the other one is home of my parents for whom I created some automatization and I don't need them to see in my HomeKit where I have my basic home (iE I don't want to show this devices to other users of my home)

recomended solution is to add option "home" where I could specify which one to link

**Comment by milo526** [comment]
Please see the option on hiding devices.

The api that this plugin uses does not expose information on the home you are using so this is not possible.
