### ISSUE TITLE
Thermostat having a crazy temperature range

### ISSUE THREAD

**Issue by snorbik** [milo526/homebridge-tuya-web#236]
Hi Milo,

today I've been able to finally run your plugin and connect it to my setup. As I am using Tuya Thermostat (climate device type) I have discovered following issues:

**a)** When thermostat is turned off, it shows temperature 150,0

Screenshot here

**b)** When thermostat is turned on, it has crazy temperature range (taken probably from Tuya) maximum is 700 and minimum is 10 - the thing is that Tuya is using data without decimal in their response -> 300 = 30 Celsius, 305 = 30,5 Celsius. This makes the setting of temperature very difficult as all possible temperatures are set in the very small part of setting wheel. FYI my maximum and minimum temperature in Smart Life app are set correctly, but these changes are not transferred to Tuya.

[Home app screenshot here](https://ibb.co/J5NhFgw) | [2](https://ibb.co/VvPJPqH) | [3](https://ibb.co/BnKhh0P)
[Smart life app screenshot here](https://ibb.co/WkDLQGD)
[Tuya response screenshot here](https://ibb.co/0hQbxFR)

**c)** Even when the temperature set correctly, in the thermostat tile there is still 150

[Screenshot here](https://ibb.co/n3Q63sB)

Can you help?

**Comment by StuFull** [comment]
Have you tried setting the temperature correction factors in the plug-in settings?

**Comment by snorbik** [comment]
I tried, but honestly I wasnt sure I am doing it correctly. Do you @StuFull have any demo settings that I could use?

**Comment by milo526** [comment]
https://github.com/milo526/homebridge-tuya-web#thermostatclimate


```json
{
            "name": "TuyaWebPlatform",
            "options": {
                "username": "EMAIL",
                "password": "PWD",
                "countryCode": "31",
                "platform": "tuya",
                "pollingInterval": 300
            },
            "defaults": [
                {
                    "id": "DEVICE_ID",
                    "device_type": "temperature_sensor",
                    "min_temper": "5",
                    "max_temper": "40",
                    "current_temperature_factor": "0.1",
                    "target_temperature_factor": "0.1"
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        }
```

**Comment by snorbik** [comment]
Thanks @milo526! I am using HOOBS for plugin configuration, so I needed only the part inside of default.

Just one small note - I needed to set my `device_type` to `climate` instead of `temperature_sensor`

Now everything works perfectly. Thanks for help.

**Comment by snorbik** [comment]
And I guess it would be helpful to others if you would have this part of code in project readme as well :)
