### ISSUE TITLE
Heater

### ISSUE THREAD

**Issue by fallingrock** [milo526/homebridge-tuya-web#240]
**Heater**

Note: The device I own is a Atomi Smart Heater, but t works fine with the tuya app and can be turned on & off using this plug-in if configured as a fan.

**Device information**

```json
{   u'header': {   u'code': u'SUCCESS', u'payloadVersion': 1},
    u'payload': {   u'devices': [   {   u'data': {   u'current_temperature': 68,
                                                     u'max_temper': 86,
                                                     u'min_temper': 60,
                                                     u'online': True,
                                                     u'state': u'false',
                                                     u'temperature': 70},
                                        u'dev_type': u'climate',
                                        u'ha_type': u'climate',
                                        u'icon': u'https://images.tuyaus.com/smart/icon/ay1531317374343k75lf/1596215049d9080cc3b71.jpg',
                                        u'id': u'6017237224a160203ff4',
                                        u'name': u'Heater'}],
                    u'scenes': []}}
```

**Comment by fallingrock** [comment]
I was able to get it to work mostly right by configuring it as a thermostat... but the temperature settings are out of whack.

Also, the temperature is being reported in celsius and I can't change it to Fahrenheit.

![IMG_3134](https://user-images.githubusercontent.com/4029821/112041325-46e5bc80-8b14-11eb-8dd5-e23d7d897150.PNG)

![IMG_3135](https://user-images.githubusercontent.com/4029821/112041403-5cf37d00-8b14-11eb-94d7-09bb3d925356.PNG)

**Comment by milo526** [comment]
I'm gonna need some more details than "out of whack" to help you.

did you look at the temperature_factor configuration values?

Regarding the celsius/fahrenheit issue.
The toggle you are looking at is for the hardware display. Changing this is not supported through HomeKit (however changing it through the Tuya app should keep it correct).
Changing the unit in the homekit app can be done by changing the temperature unit in the settings app (it is located under "language and region")
