### ISSUE TITLE
Thermostat Reporting Incorrectly

### ISSUE THREAD

**Issue by StuFull** [milo526/homebridge-tuya-web#242]
**Describe the bug**
 
I have an issue which seems similar to that identified by feckdej in #230, however I don't think it's entirely the same hence opening a new report.

I can control the thermostat within AHK (functions such as on, off and temperature changes) however I don't think it reports the correct status to AHK and I think it is this which is blocking me from making automations work.

Unlike #230 I can see that the state is changing however when switched off the device reports 'Heating to' and when on and active it reports 'Set To', which is contrary to other heating devices actions in AHK.

**Steps To Reproduce**

1. Go to 'device'
2. Click on 'switch off'
3. Scroll up to 'status'

**Plugin Version**

homebridge-tuya-web v1.0.0
 
 **Homebridge Config**
{
            "name": "TuyaWebPlatform",
            "options": {
                "username": "Redacted",
                "password": "Redacted",
                "countryCode": "44",
                "platform": "smart_life",
                "pollingInterval": 600
            },
            "defaults": [
                {
                    "id": "Redacted",
                    "device_type": "climate",
                    "max_temper": "25",
                    "current_temperature_factor": "0.5",
                    "target_temperature_factor": "0.5"
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        }

 **Device Config**
 **I cannot get this script to work.  I tried, I'm sorry.**
 
 **Additional Context**

**Comment by StuFull** [comment]
You can see here when the device is switched to off it reports 'heating to' and when it is switched on it reports 'set to'.

![IMG_1660](https://user-images.githubusercontent.com/67040954/112714082-80ca1080-8ed0-11eb-86e3-3d1296195b81.jpeg)
![IMG_1661](https://user-images.githubusercontent.com/67040954/112714094-8aec0f00-8ed0-11eb-9e73-651ca14a94d2.jpeg)

**Comment by StuFull** [comment]
Do you have any update or thoughts on this?

**Comment by milo526** [comment]
Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

Please do this for both cases, the one where it says "heating to" and the one where it says "set to".
Live is rather busy at this point so my open source work in a tad lower on the priority list then I want it to be, sorry for that.

**Comment by StuFull** [comment]
I tried to get that script to work using my MacBook but failed miserably. Any tips?

**Comment by milo526** [comment]
[repl.it](https://repl.it)

**Comment by StuFull** [comment]
OK so the output I get is as follows.  Does that help you?

Strange it thinks current temp is 39

Getting credentials
Got credentials
{   'access_token': 'Redacted',
    'expires_in': 864000,
    'refresh_token': 'Redacted',
    'token_type': 'bearer'}
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {   'current_temperature': 39,
                                                  'max_temper': 35,
                                                  'min_temper': 5,
                                                  'online': True,
                                                  'state': 'true',
                                                  'temperature': 16},
                                      'dev_type': 'climate',
                                      'ha_type': 'climate',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/15264583415nnlzwfs1qd2wqz6i937op3nmi_0.png',
                                      'id': 'Redacted',
                                      'name': 'Thermostat'}],
                   'scenes': []}}

**Comment by StuFull** [comment]
Still an issue if you’re able to find the time to take a look.
