### ISSUE TITLE
multiple gang tuya switch does not activate the homebridge switches

### ISSUE THREAD

**Issue by bobotzzz** [milo526/homebridge-tuya-web#245]
When using a tuya multiple gang wi-fi switch, activating the switches directly from the switch's panel (on the wall) the switches in the homebridge app does not turn on/off, even tho in the smart life app they are activated.
![6ABB913B-813C-4DC3-BFEE-BEDDA80C0677_1_105_c](https://user-images.githubusercontent.com/4257977/112504690-b23dc180-8d94-11eb-89c9-df72ca4203f3.jpeg) 
![image](https://user-images.githubusercontent.com/4257977/112504817-d6010780-8d94-11eb-9f56-6f738935a4aa.png) 
![image](https://user-images.githubusercontent.com/4257977/112504883-e3b68d00-8d94-11eb-8877-fe90a6789399.png)

**Comment by milo526** [comment]
Please look at the documentation.

This is known behavior and will not change
