### ISSUE TITLE
Support for New Upgraded Wifi Light Fan Switch

### ISSUE THREAD

**Issue by MoTechnicalities** [milo526/homebridge-tuya-web#246]
Please add support for this Wifi Light Fan Switch:
https://www.amazon.com/gp/product/B08FQL6R42/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

My HomeBridge Log reports the following:
[26/03/2021, 18:45:49] [TuyaWebPlatform] Missing required `id` property on device configuration, received:
{
  "device_type": "form"
}

Thank you.

**Comment by MoTechnicalities** [comment]
**More info on the product:**
**Standard Function Set**
Code	        Type              Values
switch	        Boolean	    {true,false}
fan_speed	Enum	    {"range":["1","2","3"]}
countdown	Enum	    {"range":["0","1","2","3","4","5","6"]}
light	                Boolean	    {true,false}

**Standard State Set**
switch	        Boolean	    {true,false}
fan_speed	Enum	    {"range":["1","2","3"]}
countdown	Enum	    {"range":["0","1","2","3","4","5","6"]}
light	                Boolean	    {true,false}

**Comment by milo526** [comment]
Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

Without this it is hard for me to help you with regards to this specific issue.

**Comment by milo526** [comment]
And your config is malformed. Please read the readme on what keys you should use to define `device_type` overwrites.

I suspect you are using hoobs? Their ui-config is slightly incompatible with homebridge's variant. I'm working out these kinks but for now the best thing to do is manually overwrite the device config.
