### ISSUE TITLE
PIR MOTION SENSOR

### ISSUE THREAD

**Issue by JPF-dot** [milo526/homebridge-tuya-web#252]
Hi, 

Apologies for my newbie question. I have a PIR infrared Tuya Sensor configured in my Smart Life app. 
I installed your plugin in home bridge on a raspberry Pi to be able to bring it into HomeKit. 

I've entered my login, password and country code. I, then, entered the virtual ID number of the PIR SENSOR. 
There is a multiple choice button where I can choose the function of the device I'm trying to add but there is no mention of a PIR SENSOR. I chose different options to see if one would work but apparently none are working so my device is not recognized. 

this is the log issue which I don't understand because my PIR sensor has a valid VIRTUAL ID and I'm sure it's entered correctly : 
[08/04/2021, 15:03:23] [TuyaWebPlatform] Tried overwriting device config for: "VIRTUAL ID NUMBER OF MY DEVICE" which is not a valid device-id or device-name.

Any help would be welcome 

JP

**Comment by milo526** [comment]
Sensors are not exposed to the API that this plugin is using.

What you ask is not possible with the technologies I use.

Please look for another Homebridge Tuya plugin.

Your best bet atm is homebridge-tuya
