### ISSUE TITLE
This plugin generated a warning from the characteristic ...

### ISSUE THREAD

**Issue by rikray02** [milo526/homebridge-tuya-web#253]
Hello,

I use this pluggin for only 2 LED light color.  It'works very well and thank you for that.  So, i received frequently this message in homebridge web console.  Does i need to do somethings to fix this warning message?

Any suggest to fix it? 
Richard

4/8/2021, 8:34:09 PM] [@milo526/homebridge-tuya-web] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number 392 exceeded maximum of 100. See https://git.io/JtMGR for more info.

[4/8/2021, 8:34:09 PM] [@milo526/homebridge-tuya-web] This plugin generated a warning from the characteristic 'Color Temperature': characteristic was supplied illegal value: number -868 exceeded minimum of 140. See https://git.io/JtMGR for more info.

**Comment by milo526** [comment]
This issue has been reported before, please respond there instead of opening a new issue.
