### ISSUE TITLE
Blind status

### ISSUE THREAD

**Issue by Stetocasa** [milo526/homebridge-tuya-web#254]
Hi! Trough Smartlife I added a blind motor that works fine in Smartlife app with the right status (closed/opening/closing/open)
In HomeKit via homebridge, the accessory works well as open and close but the status still "opening" "closing"
Seems not sync with Smartlife to catch the current status. If I close HomeKit and reopen still not updated 

Attached "apro = opening"
The real action was done 30 minutes ago but still not changing status ![image](https://user-images.githubusercontent.com/70729310/114296087-85362200-9aa9-11eb-8732-715a65ba051f.jpeg)

**Comment by milo526** [comment]
Duplicate of #143
