### ISSUE TITLE
HomeBridge stop reacting

### ISSUE THREAD

**Issue by jimmymcheung** [milo526/homebridge-tuya-web#257]
In console it says: Failed to check registry.npmjs.org for updates: "getaddrinfo EAI_AGAIN registry.npmjs.org" - see https://git.io/JJSz6 for help.

**Comment by bwp91** [comment]
Did you check the link? 

> getaddrinfo - your DNS resolver could not resolve registry.npmjs.org. Check your internet connection and DNS settings.
