### ISSUE TITLE
Slow to respond, No Respond

### ISSUE THREAD

**Issue by MycroftVoodoo** [milo526/homebridge-tuya-web#267]
**Describe the bug**
Homebridge warns that this plugin is slowing performance.  

Specifically I get these warning:
"This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://git.io/JtMGR for more info."

This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.

[USB] - [GET] Request failed with status code 504

**Steps To Reproduce**
This happens after running for a day or two

**Plugin Version**
@milo526/homebridge-tuya-web v1.0.1
 
 **Homebridge Config**
 
 
 ```json
{
    "name": "TuyaWebPlatform",
    "options": {
        "username": REDACTED,
        "password": REDACTED,
        "countryCode": REDACTED,
        "platform": "smart_life"
    },
    "defaults": [
        {
            "device_type": "form"
        }
    ],
    "scenes": false,
    "platform": "TuyaWebPlatform"
}
```
 
 **Device Config**
 Getting credentials
Got credentials
{   'access_token': 'AZhaz1616246896211p4sCbb6Hoj9kPvS',
    'expires_in': 864000,
    'refresh_token': 'AZhaz1616246896211p4sCbpswPljWQ8u',
    'token_type': 'bearer'}
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/1504185916_0.png',
                                      'id': '04200497dc4f22c2dfc7_1',
                                      'name': 'Switch 1'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/1504185916_0.png',
                                      'id': '04200497dc4f22c2dfc7_2',
                                      'name': 'Switch 2'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/1504185916_0.png',
                                      'id': '04200497dc4f22c2dfc7_3',
                                      'name': 'Switch 3'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/1504185916_0.png',
                                      'id': '04200497dc4f22c2dfc7_4',
                                      'name': 'Switch 4'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/1504185916_0.png',
                                      'id': '04200497dc4f22c2dfc7_7',
                                      'name': 'USB'}],
                   'scenes': []}}
 
 **Additional Context**
Homebridge version v1.3.4

**Comment by milo526** [comment]
Thanks for notifying me :)

**Comment by milo526** [comment]
I hope that the newest pre-release (v1.1.0-0) solves this issue.

If you can install the pre-release, please do so and let me know how it goes!

If you have other issues with the pre-release, please post them in the discussion https://github.com/milo526/homebridge-tuya-web/discussions/276

**Comment by MycroftVoodoo** [comment]
Will do. Thanks for follow up

John Biasi
***@***.***

**Comment by ldhall1856** [comment]
I see the same error.  I do not know how to upgrade to the pre-release using docker. When will the update be released?

Thanks,
L. Hall

**Comment by milo526** [comment]
> I see the same error. I do not know how to upgrade to the pre-release using docker. When will the update be released?
> 
> Thanks,
> L. Hall

Whenever I feel like enough people have tested it and I am confident that there are no big issues in the release.

**Comment by ldhall1856** [comment]
Awesome! Thanks!

Would you mind telling me how to install the pre-release?

**Comment by milo526** [comment]
For homebridge [please see here](https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions)

For hoobs [please follow this comment](https://github.com/milo526/homebridge-tuya-web/issues/113#issuecomment-748600272)

**Comment by ldhall1856** [comment]
Still seeing the same error. Any updates?

**Comment by jonpeng** [comment]
Still seeing the same issues on v1.0.2.

**Comment by MycroftVoodoo** [comment]
I have not seen any issues since updating to 1.1.xx (Next) version.

**Comment by JeffGoldner** [comment]
I'm getting these errors lately. I'll give the 1.1 version a go.

**Comment by JeffGoldner** [comment]
And the v1.1.0 branch worked for me.

**Comment by Witar23** [comment]
I am having the same issue, plugins works but HomeBridge raporting slow down issue

**Comment by avidteacher** [comment]
I am having the same issue (on v 1.3.8).  One report for every Tuya device, repeating about every 90 seconds.  Interestingly, my PI 4 is showing CPU spikes each time it does this.   All of the Tuya devices are also show as "No Response" in the Home App, and then come back on within 30 seconds or so.   It wasn't doing this a couple of versions ago - but I also updated a number of plugins at the same time.

**Comment by milo526** [comment]
> I am having the same issue (on v 1.3.8). One report for every Tuya device, repeating about every 90 seconds. Interestingly, my PI 4 is showing CPU spikes each time it does this. All of the Tuya devices are also show as "No Response" in the Home App, and then come back on within 30 seconds or so. It wasn't doing this a couple of versions ago - but I also updated a number of plugins at the same time.

Since you are reporting you are using v1.3.8 and this plugin is on version 1.1.1 I assume you are using another plugin. Probably tuya-lan or tuya/tuya-homebridge. Please report your problem there.

**Comment by milo526** [comment]
I've seen multiple reports of this problem being solved by the latest stable release.
Please let me know if this problem is still present for you on the latest version.
Please make sure to check that you are indeed using the homebridge-tuya-web plugin.

![Homebridge Tuya Web plugin installed](https://user-images.githubusercontent.com/5261909/147102547-2befaf48-e3c4-4544-bd9b-5f93ac254662.png)

**Comment by MycroftVoodoo** [comment]
I have had no problems since updating.  Thank you for the fix!
John J Biasi
***@***.***
