### ISSUE TITLE
Looking forward to Covers Type accessories implementation.

### ISSUE THREAD

**Issue by Aekung** [milo526/homebridge-tuya-web#27]
**Is your feature request related to a problem? Please describe.**

It's more like the feature request and there's no problem about it. I just happened to have 3 tuya covers from 2 manufacturer and I am now having to use the RF Signal to control it in homekit by bridging it with broadlink rm plugin. It would be a whole lot better experience to control it with Tuya Web API since the state of the device can be reported correctly along with the % of opening and closing. Since Tuya API supports Covers, just which it could be implemented in the plugin.

**Describe the solution you'd like**
I want to be able to control covers by homekit natively without relying on RF Signal since RF doesn't report the current state of the devices. 

**Describe alternatives you've considered**
Staying with RF Signal would be what I would do. But as said, the real state of the devices are not reported so it's quite a mess sometimes.

**Additional context**
I do have 3 covers from 2 manufacturers that use Tuya Web API. I am currently using Smart Life app. My only computer in my house is Macbook Air (I don't have Window) so if I can help extracting any useful information from you, please kindly instruct and I will do so.

**Comment by hugozheng2017** [comment]
I have a tuya web garage door.also hope to support it.

**Comment by milo526** [comment]
Hello, thank you for your interests.

Please follow the steps outlined in the readme under: [How to check whether the API this library uses can control your device?](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

**Comment by Aekung** [comment]
> Hello, thank you for your interests.
> 
> Please follow the steps outlined in the readme under: [How to check whether the API this library uses can control your device?](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

@milo526 

Thanks for the reply.

This is what I got from the test on Repl

```
Getting credentials
Got credentials
{   'access_token': 'XXXXXXXX',
    'expires_in': 864000,
    'refresh_token': 'XXXXX',
    'token_type': 'bearer'}
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {   'online': True,
                                                  'state': 3,
                                                  'support_stop': True},
                                      'dev_type': 'cover',
                                      'ha_type': 'cover',
                                      'icon': 'https://images.tuyaus.com/smart/product_icon/cl.png',
                                      'id': '52003233ecfabca9fdce',
                                      'name': 'Window Cover for Front Door'},
                                  {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/program_category_icon/kg.png',
                                      'id': '138766762cf432caa04b',
                                      'name': 'Bedroom Light'},
                                  {   'data': {   'online': True,
                                                  'state': 3,
                                                  'support_stop': True},
                                      'dev_type': 'cover',
                                      'ha_type': 'cover',
                                      'icon': 'https://images.tuyaus.com/smart/product_icon/cl.png',
                                      'id': '10670875bcddc2b0e398',
                                      'name': 'Window Cover for Garden'},
                                  {   'data': {   'online': True,
                                                  'state': 2,
                                                  'support_stop': True},
                                      'dev_type': 'cover',
                                      'ha_type': 'cover',
                                      'icon': 'https://images.tuyaus.com/smart/program_category_icon/cl.png',
                                      'id': '630777045002914b3123',
                                      'name': 'Window Cover for Home Theater'}],
                   'scenes': []}}
!!! NOW REMOVE THIS FILE, SO YOUR CREDENTIALS (username, password) WON'T LEAK !!!
```

I think it's supported but as it's a cover type, it's not supported by this plugin yet. Hopefully it could work soon.

**Comment by milo526** [comment]
Thank you for this information, it turns out that support for the cover accessory is already tracked in #18 

Closing this issue to prevent duplicating information.
