### ISSUE TITLE
Power consumption

### ISSUE THREAD

**Issue by hbkmanbass** [milo526/homebridge-tuya-web#271]
Dear team, 

I would like to get access to my power consumption in eve app and homekit 
Is it possible ? 

Thanks in advance,

**Comment by mbierman** [comment]
Yes. You need something like https://www.home-assistant.io/integrations/neurio_energy/

**Comment by hbkmanbass** [comment]
Thank you for your answer. I would like to use the Smartlife outlet I have and use it in this plugin. I can view the power consumption in the Smartlife app but not in Home app or eve app ..

**Comment by milo526** [comment]
This is technologically impossible with the api that this plugin uses.
