### ISSUE TITLE
Treatlife Fan Control Switch

### ISSUE THREAD

**Issue by dfizzo** [milo526/homebridge-tuya-web#272]
**Describe the bug**

**Steps To Reproduce**

**Plugin Version**
 
 
 **Homebridge Config**
 
 
 ```json

```
 
 **Device Config**
 
 
 **Additional Context**

**Comment by dfizzo** [comment]
I have also reached out to Tuya support to add device support to the /homeassistant API

**Comment by milo526** [comment]
👍
