### ISSUE TITLE
TuyaWebPlatform Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by sirwasaeed** [milo526/homebridge-tuya-web#273]
Hi, 

I have been using this plugin for atleast 6 months or more without any problems.
But since a week ago, i am unable to use Homekit without connectivity issues. 

Everything from Homebridge to the plugin is up to date. I even did a full re-install of homebridge + plugin.
My config follows as:

},
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "TuyaWebPlatform",
            "options": {
                "username": "username@hotmail.com",
                "password": "password",
                "countryCode": "31",
                "platform": "tuya",
                "pollingInterval": 700

I tried a different account that i added to Tuya, with different login. 
I changed my password, still no luck. 

Is it just me?

**The error is get:**

Starting to advertise 'Homebridge AD8F 5777' using bonjour-hap backend!
[5/16/2021, 4:20:10 PM] Homebridge v1.3.4 (Homebridge AD8F) is running on port 53114.
[5/16/2021, 4:20:10 PM] [TuyaWebPlatform] Sending HTTP GET request to /homeassistant/skill - Header: {"name":"Discovery","namespace":"discovery","payloadVersion":1}.
[5/16/2021, 4:20:42 PM] [TuyaWebPlatform] connect ETIMEDOUT 18.196.39.108:443
[5/16/2021, 4:20:42 PM] [TuyaWebPlatform] Error: connect ETIMEDOUT 18.196.39.108:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '18.196.39.108',
  port: 443,
  config: {
    url: '/homeassistant/skill',
    method: 'get',
    data: '{"header":{"name":"Discovery","namespace":"discovery","payloadVersion":1},"payload":{"accessToken":"EUheu15925146217965ECxCShSbSWKPM3"}}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json;charset=utf-8',
      'User-Agent': 'axios/0.21.1',
      'Content-Length': 136
    },
    baseURL: 'https://px1.tuyaeu.com',
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus]
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: '/homeassistant/skill',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'px1.tuyaeu.com',
      port: null,
      nativeProtocols: [Object],
      pathname: '/homeassistant/skill'
    },
    _ended: false,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 136,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'GET /homeassistant/skill HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json;charset=utf-8\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Content-Length: 136\r\n' +
        'Host: px1.tuyaeu.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/homeassistant/skill',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'px1.tuyaeu.com',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://px1.tuyaeu.com/homeassistant/skill',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]

Any help is appreciated. Thanks in advance!

**Comment by milo526** [comment]
I have not received any other complaints regarding this and I assume that, if the plugin broke, I would have received complaints.
For now, I assume that either your network connection or the tuya servers had a hick-up.
Please see how it continues to function.

**Comment by GiorgioJ** [comment]
I do have similar issues which started a week back or so. Will let you know if I have discovered a potential trigger of this issue.

**Comment by sirwasaeed** [comment]
Hi,

It was Tuya related, might have been server issues on their end.

Previously, i did a fresh install of both homebridge + plugin and that didn't fix it. 
This week it started to work again like normal.

Thanks again!
