### ISSUE TITLE
Cannot read property 'brightness'

### ISSUE THREAD

**Issue by newt10** [milo526/homebridge-tuya-web#28]
**Describe the bug**
Seeing error in homebridge - Can still turn device on/off but the error is not going away

0|homebridge  | [7/5/2020, 12:53:35 AM] [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
0|homebridge  |     at LightAccessory.updateState (/home/pi/.nvm/versions/node/v12.16.1/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:227:39)
0|homebridge  |     at LightAccessory.updateAccessory (/home/pi/.nvm/versions/node/v12.16.1/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:14)
0|homebridge  |     at /home/pi/.nvm/versions/node/v12.16.1/lib/node_modules/homebridge-tuya-web/index.js:96:52
0|homebridge  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
0|homebridge  | [7/5/2020, 12:53:42 AM] [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
0|homebridge  |     at LightAccessory.updateState (/home/pi/.nvm/versions/node/v12.16.1/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:227:39)
0|homebridge  |     at LightAccessory.updateAccessory (/home/pi/.nvm/versions/node/v12.16.1/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:14)
0|homebridge  |     at /home/pi/.nvm/versions/node/v12.16.1/lib/node_modules/homebridge-tuya-web/index.js:96:52
0|homebridge  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
0|homebridge  | [7/5/2020, 12:53:49 AM] [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
0|homebridge  |     at LightAccessory.updateState (/home/pi/.nvm/versions/node/v12.16.1/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:227:39)
0|homebridge  |     at LightAccessory.updateAccessory (/home/pi/.nvm/versions/node/v12.16.1/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:14)
0|homebridge  |     at /home/pi/.nvm/versions/node/v12.16.1/lib/node_modules/homebridge-tuya-web/index.js:96:52
0|homebridge  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
0|homebridge  | [7/5/2020, 12:53:55 AM] [Config] Homebridge Config UI X v4.23.2 is listening on :: port 8080
0|homebridge  | [7/5/2020, 12:53:58 AM] [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
0|homebridge  |     at LightAccessory.updateState (/home/pi/.nvm/versions/node/v12.16.1/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:227:39)
0|homebridge  |     at LightAccessory.updateAccessory (/home/pi/.nvm/versions/node/v12.16.1/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:14)
0|homebridge  |     at /home/pi/.nvm/versions/node/v12.16.1/lib/node_modules/homebridge-tuya-web/index.js:96:52
0|homebridge  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)

**To Reproduce**
Just shows up every few minutes in the homebridge logs

**Expected behavior**
Not sure what the error is -> expected to run without error

**Screenshots**

**Device**
Merkury Color LED bulbs via Tuya

**Comment by milo526** [comment]
This seems to be the same problem as #11 is that right?

**Comment by milo526** [comment]
And please also follow the steps as described [here](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device) and post the output. Without that I can do very little.

**Comment by glitch82** [comment]
I’m having the same issue but it’s definitely new and I didn’t have it some versions ago. I’m using the Teckin Smart WiFi RGB and cool/warm white bulb with the Smart Life application.

**Comment by milo526** [comment]
Closing due to no response from original author and failure to follow posted guidelines and request for more information.

**Comment by Radstake** [comment]
I have exactly the same. It work before just great! Also the same Led Strip worked perfectly, now stopped working with the same error.

**Comment by gerswin** [comment]
same here
