### ISSUE TITLE
ich brauche hilfe!!!

### ISSUE THREAD

**Issue by row65** [milo526/homebridge-tuya-web#282]
Ich habe einen Temperatur-Feuchte-Detektor. was muss ich in Plugins einstellenum es dann in der Homekit die Temperatur und Feuchtigkeit sehen kann
Werte sind Temperatur -10±55 Feuchtigkeit 0-100%RH
!--
Everything that is placed between these <! - - and - - > are considered comments and will not render. 
Make sure to place all your information outside of these notations or I will not be able to read it!
-->

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by row65** [comment]
Ich habe einen Temperatur-Feuchte-Detektor. was muss ich in Plugins einstellen um es dann in der Homekit die Temperatur und Feuchtigkeit sehen kann
Werte sind Temperatur -10±55 Feuchtigkeit 0-100%RH

**Comment by milo526** [comment]
Please converse in English and follow the issue template.
Furthermore excessive use of exclamation marks will not help you.

**Comment by row65** [comment]
I have a temperature / humidity detector. I have to set plugins in order to see the temperature and humidity in the HomeKit
Values are temperature -10 ± 55 humidity 0-100% RH

**Comment by milo526** [comment]
Please read the section on [thermostat/climate] in the readme on how to expose the temperature.
Humidity is not supported due to technical limitations.
