### ISSUE TITLE
Air Purifier Hosome

### ISSUE THREAD

**Issue by Lestercity** [milo526/homebridge-tuya-web#287]
Would support for an air purifier be managable? Using your plugin with great pleasure and just bought a tuya air purifier from Hosome through Amazon. Seems to be a very well reviewed model.

**Comment by milo526** [comment]
I don't know. 

Please follow the issue template and I can give you a better answer.

More info can also be found here: https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device

**Comment by RosemaryOrchard** [comment]
I have 2 Himox air purifiers. The results of the above script (with just one device connected to Tuya) show:
```
'devices': [   {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/program_category_icon/kj.png',
                                      'id': '80256465cc50e3ff9b50',
                                      'name': 'Bedroom Air Purifier'}],
                   'scenes': []}}
```
I hope this helps! I would love to be able to control the lights as well as set the fan to low, high or auto.

**Comment by milo526** [comment]
Hello, as we can see, the device is reported as a "switch" sadly there is nothing I can do to help you here since Tuya does not properly expose your devices.
