### ISSUE TITLE
after the update, one of the dimmers stopped working via hoobs.

### ISSUE THREAD

**Issue by motogon** [milo526/homebridge-tuya-web#288]
**Describe the bug**

after the update, one of the dimmers stopped working via hoobs. Through the tuya app - this dimmer works correctly.

Other dimmers and switches from tuya - in hoobs work fine.

**Steps To Reproduce**

After pressing the button in the home application, the button changes color (displays the status on), but the dimmer remains in the off state.

12.06.2021, 18:40:44 [TuyaWebPlatform] [Гостиная ] Characteristic.On - [SET] true 1
112.06.2021, 18:41:10 [TuyaWebPlatform] [Гостиная ] Characteristic.On - [SET] false 0

if you turn on / off the dimmer in the tuya application, then the status in the homekit is not transmitted.

12.06.2021, 18:26:22 [TuyaWebPlatform] [Гостиная ] - Unsetting debouncedDeviceStateRequestPromise
12.06.2021, 18:26:22 [TuyaWebPlatform] [Гостиная ] - Resolving resolveDeviceStateRequest from cache
12.06.2021, 18:26:22 [TuyaWebPlatform] [Гостиная ] Characteristic.On - [GET] false
12.06.2021, 18:26:22 [TuyaWebPlatform] [Гостиная ] Characteristic.Brightness - [GET] 58

**Plugin Version**
 
1.0.1
 
 **Homebridge Config**
 
```json
{
            "platform": "TuyaWebPlatform",
            "plugin_map": {
                "plugin_name": "homebridge-tuya-web"
            },
            "name": "TuyaWebPlatform",
            "scenes": false,
            "options": {
                "platform": "tuya",
                "username": "хххххх",
                "password": "хххххх",
                "countryCode": "+7",
                "pollingInterval": 10
            },
            "defaults": [],
            "scenesWhitelist": [],
            "hiddenAccessories": []
        },
 ```
 **Device Config**
 

Getting devices
Got devices
```json
{   u'header': {   u'code': u'SUCCESS', u'payloadVersion': 1},
    u'payload': {   u'devices': [   {   u'data': {   u'online': False,
                                                     u'state': True},
                                        u'dev_type': u'switch',
                                        u'ha_type': u'switch',
                                        u'icon': u'https://images.tuyaeu.com/smart/icon/ay1510556338767TKsrc/158322532579e9964e9d9.png',
                                        u'id': u'772766852cf4327e7a98',
                                        u'name': u'\u041f\u043e\u043b\u0438\u0432 3'},
                                    {   u'data': {   u'online': False,
                                                     u'state': True},
                                        u'dev_type': u'switch',
                                        u'ha_type': u'switch',
                                        u'icon': u'https://images.tuyaeu.com/smart/icon/ay1510556338767TKsrc/158322532579e9964e9d9.png',
                                        u'id': u'772766852cf4327e7a68',
                                        u'name': u'\u041f\u043e\u043b\u0438\u0432 \u043a\u043b\u0430\u043f\u0430\u043d 1'},
                                    {   u'data': {   u'online': False,
                                                     u'state': True},
                                        u'dev_type': u'switch',
                                        u'ha_type': u'switch',
                                        u'icon': u'https://images.tuyaeu.com/smart/icon/ay1510556338767TKsrc/158322532579e9964e9d9.png',
                                        u'id': u'772766852cf4327e75f2',
                                        u'name': u'\u041a\u043b\u0430\u043f\u0430\u043d 4'},
                                    {   u'data': {   u'brightness': u'48',
                                                     u'online': True,
                                                     u'state': u'false'},
                                        u'dev_type': u'light',
                                        u'ha_type': u'light',
                                        u'icon': u'https://images.tuyaeu.com/smart/product_icon2/dj_1.png',
                                        u'id': u'65468423d8f15b0db3ca',
                                        u'name': u'\u0421\u043f\u0430\u043b\u044c\u043d\u044f \u0431\u043e\u043b\u044c\u0448\u0430\u044f'},
                                    {   u'data': {   u'brightness': u'59',
                                                     u'online': True,
                                                     u'state': u'false'},
                                        u'dev_type': u'light',
                                        u'ha_type': u'light',
                                        u'icon': u'https://images.tuyaeu.com/smart/product_icon2/dj_1.png',
                                        u'id': u'65468423d8f15b0d6bd8',
                                        u'name': u'\u0413\u043e\u0441\u0442\u0435\u0432\u0430\u044f \u0441\u043f\u0430\u043b\u044c\u043d\u044f'},
                                    {   u'data': {   u'brightness': u'32',
                                                     u'online': True,
                                                     u'state': u'true'},
                                        u'dev_type': u'light',
                                        u'ha_type': u'light',
                                        u'icon': u'https://images.tuyaeu.com/smart/product_icon2/dj_1.png',
                                        u'id': u'654684234c11ae1709bf',
                                        u'name': u'\u041a\u0430\u0431\u0438\u043d\u0435\u0442'},
                                    {   u'data': {   u'online': True,
                                                     u'state': True},
                                        u'dev_type': u'switch',
                                        u'ha_type': u'switch',
                                        u'icon': u'https://images.tuyaeu.com/smart/icon/001460162698766TR4v1/1571295242db8f709b6dc.png',
                                        u'id': u'bf97b17f166ac21713tiko',
                                        u'name': u'\u0412\u0435\u043d\u0442\u0438\u043b\u044f\u0442\u043e\u0440 \u043a\u0432\u0430\u0440\u0442\u0438\u0440\u0430'},
                                    {   u'data': {   u'online': True,
                                                     u'state': True},
                                        u'dev_type': u'switch',
                                        u'ha_type': u'switch',
                                        u'icon': u'https://images.tuyaeu.com/smart/icon/001460162698766TR4v1/1571295242db8f709b6dc.png',
                                        u'id': u'bf83354dd6a57d77e6ekkr',
                                        u'name': u'\u041a\u043e\u043c\u043f'},
                                    {   u'data': {   u'brightness': u'16',
                                                     u'online': True,
                                                     u'state': u'false'},
                                        u'dev_type': u'light',
                                        u'ha_type': u'light',
                                        u'icon': u'https://images.tuyaeu.com/smart/icon/001461404842469iWoLE/1595839264366307063f6.jpg',
                                        u'id': u'48002207bcddc260ad75',
                                        u'name': u'\u0413\u043e\u0441\u0442\u0438\u043d\u0430\u044f '},
                                    {   u'data': {   u'online': False,
                                                     u'state': True},
                                        u'dev_type': u'switch',
                                        u'ha_type': u'switch',
                                        u'icon': u'https://images.tuyaeu.com/smart/icon/1542249879hiloaqulpb9_0.jpg',
                                        u'id': u'180001305002914783fa',
                                        u'name': u'\u041f\u043e\u043b\u0438\u0432 \u0433\u0430\u0437\u043e\u043d'},
                                    {   u'data': {   u'online': False,
                                                     u'state': True},
                                        u'dev_type': u'switch',
                                        u'ha_type': u'switch',
                                        u'icon': u'https://images.tuyaeu.com/smart/icon/ay1510556338767TKsrc/158322532579e9964e9d9.png',
                                        u'id': u'772766852cf4327e7997',
                                        u'name': u'\u041a\u043b\u0430\u043f\u0430\u043d 2'},
                                    {   u'data': {   },
                                        u'dev_type': u'scene',
                                        u'ha_type': u'scene',
                                        u'id': u'bYlJi5ck2tsZJn8b',
                                        u'name': u'\u0415\u0441\u043b\u0438 \u0422\u0430\u0439\u043c\u0435\u0440:18:00 7/6,\\"\u041f\u043e\u043b\u0438\u0432 \u0433\u0430\u0437\u043e\u043d\\" \u043f\u043e\u043b\u0438\u0432:ON...'}],
                    u'scenes': []}}
 ```
 **Additional Context**
 

problem with dimmer u'id ': u'48002207bcddc260ad75',

**Comment by milo526** [comment]
Hey,

Is it only this dimmer that no longer works?

Could you maybe see if there is some more log output? The log your provide now indicates that t should work :/

**Comment by motogon** [comment]
13.06.2021, 14:01:51 [TuyaWebPlatform] [Гостиная ] - Unsetting debouncedDeviceStateRequestPromise
13.06.2021, 14:01:51 [TuyaWebPlatform] [Гостиная ] - Resolving resolveDeviceStateRequest from cache
13.06.2021, 14:01:51 [TuyaWebPlatform] [Гостиная ] Characteristic.On - [GET] false
13.06.2021, 14:01:51 [TuyaWebPlatform] [Гостиная ] Characteristic.Brightness - [GET] 16

Yes, the problem is with only one dimmer.
Everything else works.

I saw nothing more in the logs.

**Comment by motogon** [comment]
in debug mode

[TuyaWebPlatform] Loading accessory from cache: Гостиная

--
}
[TuyaWebPlatform] Existing Accessory found [Name: Комп] [Tuya ID: bf83354dd6a57d77e6ekkr] [HomeBridge ID: f0a5964d-e57f-4187-b95b-a240d4667f3d]
[TuyaWebPlatform] [Гостиная ] deviceConfig: {
  data: { brightness: '16', online: true, state: 'false' },
  name: 'Гостиная ',
  icon: 'https://images.tuyaeu.com/smart/icon/001461404842469iWoLE/1595839264366307063f6.jpg',
  id: '48002207bcddc260ad75',
  dev_type: 'light',
  ha_type: 'light'
}
[TuyaWebPlatform] Existing Accessory found [Name: Гостиная ] [Tuya ID: 48002207bcddc260ad75] [HomeBridge ID: 02d2dd27-62cb-4be5-bbf1-b8e2b7def0d8]
[TuyaWebPlatform] [Гостиная ] Characteristic.On - {"format":"bool","perms":["ev","pr","pw"]}
[TuyaWebPlatform] [Гостиная ] Characteristic.Brightness - {"format":"int","perms":["ev","pr","pw"],"unit":"percentage","minValue":0,"maxValue":100,"minStep":1}

--
[TuyaWebPlatform] [Гостиная ] - Requesting device state
[TuyaWebPlatform] [Гостиная ] - Creating new debounced promise
[TuyaWebPlatform] [Гостиная ] - Triggering debouncedDeviceStateRequest
[TuyaWebPlatform] [Гостиная ] - Requesting device state
[TuyaWebPlatform] [Гостиная ] - Triggering debouncedDeviceStateRequest
--
[TuyaWebPlatform] [Гостиная ] - Unsetting debouncedDeviceStateRequestPromise
[TuyaWebPlatform] [Гостиная ] - Resolving resolveDeviceStateRequest from cache
[TuyaWebPlatform] [Гостиная ] Characteristic.On - [GET] false
[TuyaWebPlatform] [Гостиная ] Characteristic.Brightness - [GET] 16

**Comment by motogon** [comment]
hoobs -d  |grep "Гостиная"
[TuyaWebPlatform] Loading accessory from cache: Гостиная
[TuyaWebPlatform] [Гостиная ] deviceConfig: {
  name: 'Гостиная ',
[TuyaWebPlatform] Existing Accessory found [Name: Гостиная ] [Tuya ID: 48002207bcddc260ad75] [HomeBridge ID: 02d2dd27-62cb-4be5-bbf1-b8e2b7def0d8]
[TuyaWebPlatform] [Гостиная ] Characteristic.On - {"format":"bool","perms":["ev","pr","pw"]}
[TuyaWebPlatform] [Гостиная ] Characteristic.Brightness - {"format":"int","perms":["ev","pr","pw"],"unit":"percentage","minValue":0,"maxValue":100,"minStep":1}
[TuyaWebPlatform] [Гостиная ] - Requesting device state
[TuyaWebPlatform] [Гостиная ] - Creating new debounced promise
[TuyaWebPlatform] [Гостиная ] - Triggering debouncedDeviceStateRequest
[TuyaWebPlatform] [Гостиная ] - Requesting device state
[TuyaWebPlatform] [Гостиная ] - Triggering debouncedDeviceStateRequest
[TuyaWebPlatform] [Гостиная ] - Unsetting debouncedDeviceStateRequestPromise
[TuyaWebPlatform] [Гостиная ] - Resolving resolveDeviceStateRequest from cache
[TuyaWebPlatform] [Гостиная ] Characteristic.On - [GET] false
[TuyaWebPlatform] [Гостиная ] Characteristic.Brightness - [GET] 16
[TuyaWebPlatform] [Гостиная ] - Requesting device state
[TuyaWebPlatform] [Гостиная ] - Creating new debounced promise
[TuyaWebPlatform] [Гостиная ] - Triggering debouncedDeviceStateRequest
[TuyaWebPlatform] [Гостиная ] - Requesting device state
[TuyaWebPlatform] [Гостиная ] - Triggering debouncedDeviceStateRequest
[TuyaWebPlatform] [Гостиная ] - Unsetting debouncedDeviceStateRequestPromise
[TuyaWebPlatform] [Гостиная ] - Resolving resolveDeviceStateRequest from remote
[TuyaWebPlatform] [Гостиная ] - Set device state request cache
[TuyaWebPlatform] [Гостиная ] Characteristic.On - [GET] false
[TuyaWebPlatform] [Гостиная ] Characteristic.Brightness - [GET] 16
[TuyaWebPlatform] [Гостиная ] - Requesting device state
[TuyaWebPlatform] [Гостиная ] - Creating new debounced promise
[TuyaWebPlatform] [Гостиная ] - Triggering debouncedDeviceStateRequest
[TuyaWebPlatform] [Гостиная ] - Requesting device state
[TuyaWebPlatform] [Гостиная ] - Triggering debouncedDeviceStateRequest
[TuyaWebPlatform] [Гостиная ] - Unsetting debouncedDeviceStateRequestPromise
[TuyaWebPlatform] [Гостиная ] - Resolving resolveDeviceStateRequest from cache
[TuyaWebPlatform] [Гостиная ] Characteristic.On - [GET] false
[TuyaWebPlatform] [Гостиная ] Characteristic.Brightness - [GET] 16
[TuyaWebPlatform] [Гостиная ] Characteristic.On - [SET] true 1
[TuyaWebPlatform] [Гостиная ] - Requesting device state
[TuyaWebPlatform] [Гостиная ] - Creating new debounced promise
[TuyaWebPlatform] [Гостиная ] - Triggering debouncedDeviceStateRequest
[TuyaWebPlatform] [Гостиная ] - Requesting device state
[TuyaWebPlatform] [Гостиная ] - Triggering debouncedDeviceStateRequest
[TuyaWebPlatform] [Гостиная ] - Unsetting debouncedDeviceStateRequestPromise
[TuyaWebPlatform] [Гостиная ] - Renewing cache due to RateLimitError
[TuyaWebPlatform] [Гостиная ] Characteristic.On - [GET] true
[TuyaWebPlatform] [Гостиная ] Characteristic.Brightness - [GET] 16
[TuyaWebPlatform] [Гостиная ] - Requesting device state
[TuyaWebPlatform] [Гостиная ] - Creating new debounced promise
[TuyaWebPlatform] [Гостиная ] - Triggering debouncedDeviceStateRequest
[TuyaWebPlatform] [Гостиная ] - Requesting device state
[TuyaWebPlatform] [Гостиная ] - Triggering debouncedDeviceStateRequest
[TuyaWebPlatform] [Гостиная ] - Unsetting debouncedDeviceStateRequestPromise
[TuyaWebPlatform] [Гостиная ] - Resolving resolveDeviceStateRequest from cache
[TuyaWebPlatform] [Гостиная ] Characteristic.On - [GET] true
[TuyaWebPlatform] [Гостиная ] Characteristic.Brightness - [GET] 16

**Comment by motogon** [comment]
I have turned on the dimmer in the tuya app


[TuyaWebPlatform] [Гостиная ] - Requesting device state
[TuyaWebPlatform] [Гостиная ] - Creating new debounced promise
[TuyaWebPlatform] [Гостиная ] - Triggering debouncedDeviceStateRequest
[TuyaWebPlatform] [Гостиная ] - Requesting device state
[TuyaWebPlatform] [Гостиная ] - Triggering debouncedDeviceStateRequest
[TuyaWebPlatform] [Гостиная ] - Unsetting debouncedDeviceStateRequestPromise
[TuyaWebPlatform] [Гостиная ] - Resolving resolveDeviceStateRequest from remote
[TuyaWebPlatform] [Гостиная ] - Set device state request cache
[TuyaWebPlatform] [Гостиная ] Characteristic.On - [GET] true
[TuyaWebPlatform] [Гостиная ] Characteristic.Brightness - [GET] 58
[TuyaWebPlatform] [Гостиная ] - Requesting device state
[TuyaWebPlatform] [Гостиная ] - Creating new debounced promise
[TuyaWebPlatform] [Гостиная ] - Triggering debouncedDeviceStateRequest
[TuyaWebPlatform] [Гостиная ] - Requesting device state
[TuyaWebPlatform] [Гостиная ] - Triggering debouncedDeviceStateRequest
[TuyaWebPlatform] [Гостиная ] - Unsetting debouncedDeviceStateRequestPromise
[TuyaWebPlatform] [Гостиная ] - Resolving resolveDeviceStateRequest from cache
[TuyaWebPlatform] [Гостиная ] Characteristic.On - [GET] true
[TuyaWebPlatform] [Гостиная ] Characteristic.Brightness - [GET] 58

**Comment by motogon** [comment]
[Lupanovo 857A@Гостиная @Гостиная @On] The read handler for the characteristic 'On' was slow to respond!
[Lupanovo 857A@Гостиная @Гостиная @Brightness] The read handler for the characteristic 'Brightness' was slow to respond!

**Comment by motogon** [comment]
13.06.2021, 15:13:23 [TuyaWebPlatform] Sending HTTP POST request to /homeassistant/skill - Header: {"name":"turnOnOff","namespace":"control","payloadVersion":1}.
13.06.2021, 15:13:23 [TuyaWebPlatform] [Гостиная ] Characteristic.On - [SET] true 1

**Comment by motogon** [comment]
> Hey,
> 
> Is it only this dimmer that no longer works?
> 
> Could you maybe see if there is some more log output? The log your provide now indicates that t should work :/

Any thoughts on the cause of the problem? :)
