### ISSUE TITLE
New device 

### ISSUE THREAD

**Issue by dragonjo84** [milo526/homebridge-tuya-web#294]
Hello,

New devices added to smartlife do not appear in my homekit.

Is there a manipulation to be done?

Thanks

**Describe the bug**

**Steps To Reproduce**

**Plugin Version**
 
 
 **Homebridge Config**
 
 
 ```json

```
 
 **Device Config**
 
 
 **Additional Context**

**Comment by milo526** [comment]
I don't know man, all the info that I need to answer your question is missing in the issue template.
