### ISSUE TITLE
Temperature / humidity sensor is a switch …

### ISSUE THREAD

**Issue by neonish** [milo526/homebridge-tuya-web#296]
First of all, shout out to @milo526, this plugin has saved me so much time already. Thanks for that!

I'm trying to add a tuya temperature / humidity sensor I recently bought:
![IMG_0309](https://user-images.githubusercontent.com/29614734/124710727-6fe06080-defd-11eb-9239-ce56a1e88759.jpg)

It's working fine in the tuya app, I can see the temperature & humidity history and all … Though it doesn't seem to work with this plugin, neither as "temperature sensor" nor as "thermostat". The controls in my home app don't receive any values.

Running debug_discovery.py gives me this:
```
'devices': [  
       {  'data': {'online': True, 'state': False},
              'dev_type': 'switch',
              'ha_type': 'switch',
              'icon': 'https://images.tuyaeu.com/smart/program_category_icon/wsdcg.png',
              'id': '####',
              'name': 'Temperature Humidity Sensor'
       }
]
```

Which explains why no values are received. I can configure it as "switch" in the plugin, but obviously this has no real use, as it doesn't do anything.

I checked further with `tuya-lan-find`, which comes with @AMoo-Miki/homebridge-tuya-lan and checks outgoing connections from the tuya app:
```
{
    name: 'Temperature Humidity Sensor',
    id: '####',
    key: '####',
    def: {
        schema: '[
            {
                "mode":"ro",
                "code":"temp_current",
                "name":\\u5f53\\u524d\\u6e29\\u5ea6,
                "property":
                    {
                        "unit":\\u00b0C,
                        "min":-400,
                        "max":2000,
                        "scale":1,
                        "step":1,
                        "type":"value"
                    },
                "iconname":"icon-wendu1",
                "id":1,
                "type":"obj",
                "desc":""
            },
            {
                "mode":"ro",
                "code":"humidity_value",
                "name":\\u5f53\\u524d\\u6e7f\\u5ea6,
                "property":
                    {
                        "unit":"%",
                        "min":0,
                        "max":100,
                        "scale":0,
                        "step":1,
                        "type":"value"
                    },
                "iconname":"icon-dp_wet2",
                "id":2,
                "type":"obj",
                "desc":""
            },
            {
                "mode":"ro",
                "code":"battery_state",
                "name":\\u7535\\u6c60\\u7535\\u91cf\\u72b6\\u6001,
                "property":
                    {
                        "range":["low","middle","high"],
                        "type":"enum"
                    },
                "iconname":"icon-dianliang",
                "id":3,
                "type":"obj",
                "desc":""
            }
        ]',
    },
}
```

Which is more of what I expected from a temperature / humidity sensor …

Do you guys have any pointers for me on how to get this to work?

**Comment by milo526** [comment]
Sadly there is nothing I can do to help you.
Tuya does not supply this plugin with the required information.

Your best bet is to switch to the other plugin.

**Comment by neonish** [comment]
The other plugin is fetching its data from your local network. As the sensor is only waking up for real short amounts of time when a value has changed, it's impossible to use it locally in homebridge. Therefore I need to fetch the data from tuya cloud. 

There must be some way, as the tuya app also connects to the cloud and gets its data from there. Can you tell me where to find further documentation on tuya's web api?

**Comment by milo526** [comment]
Sadly this plugin does not use the tuya cloud API. It uses a separate, dedicated Hass IO API. I have no further knowledge about the API that the tuya app uses.

**Comment by neonish** [comment]
Apparently Tuya recently added these sensors to their HA integration … Take a look at this comment: [tuya/tuya-home-assistant#5 (comment)](https://github.com/tuya/tuya-home-assistant/issues/5#issuecomment-855518808)

Would this work?

**Comment by milo526** [comment]
No, what you refer to is the Tuya HA integration that uses their standard API. This plugin uses an older version of the Tuya HA API
