### ISSUE TITLE
light strips not changing colour

### ISSUE THREAD

**Issue by aidanferre** [milo526/homebridge-tuya-web#297]
i have bought 2 LE light strips and added them to the smart life/tuya app.  i can turn them on and off but can't change the colour.  this is the error i get in the logs 
"the read handler for the characteristic 'colour temperature' didn't respond at all

**Comment by milo526** [comment]
Please follow the issue template to give me the correct info that I need to resolve this issue.

All of the essential info is currently lacking from this post so sadly I can't help you here.
