### ISSUE TITLE
No output after platform initialisation

### ISSUE THREAD

**Issue by darkenv2** [milo526/homebridge-tuya-web#30]
I sincerely apologize as I'm a total Noob and just started using Homebridge about 3 days ago. I just installed a new fan control light switch and linked it to the Smart Life app. I installed the plugin @milo526/homebridge-tuya-web v0.3.3 and logged in with all my credentials and everything and once I restart homebridge it loads everything up and says "[TuyaWebPlatform] Initializing TuyaWebPlatform..." and nothing more. Am I doing something wrong? Again I'm sorry for the really dumb basic question. I just really want to get this working.

**Comment by milo526** [comment]
Hello, please try running homebridge with debug mode enabled and post the output here. In debug mode it will output more.

Furthermore please use the provided issue templates next-time, I think this could have fitted the bug template nicely.

**Comment by darkenv2** [comment]
I got two bits of information from debug mode for the plugin

[7/8/2020, 19:37:49] [TuyaWebPlatform] Initializing TuyaWebPlatform...
  follow-redirects options {
  protocol: 'https:',
  maxRedirects: 21,
  maxBodyLength: 10485760,
  path: '/homeassistant/auth.do',
  method: 'POST',
  headers: {
    Accept: 'application/json, text/plain, */*',
    'Content-Type': 'application/x-www-form-urlencoded',
    'Content-Length': 96,
    'User-Agent': 'axios/0.19.2'
  },
  agent: undefined,
  agents: { http: undefined, https: undefined },
  auth: undefined,
  hostname: 'px1.tuyaeu.com',
  port: null,
  nativeProtocols: {
    'http:': {
      _connectionListener: [Function: connectionListener],
      METHODS: [Array],
      STATUS_CODES: [Object],
      Agent: [Function],
      ClientRequest: [Function: ClientRequest],
      IncomingMessage: [Function: IncomingMessage],
      OutgoingMessage: [Function: OutgoingMessage],
      Server: [Function: Server],
      ServerResponse: [Function: ServerResponse],
      createServer: [Function: createServer],
      get: [Function: get],
      request: [Function: request],
      maxHeaderSize: [Getter],
      globalAgent: [Getter/Setter]
    },
    'https:': {
      Agent: [Function: Agent],
      globalAgent: [Agent],
      Server: [Function: Server],
      createServer: [Function: createServer],
      get: [Function: get],
      request: [Function: request]
    }
  }
} +0ms

[7/8/2020, 19:37:51] [TuyaWebPlatform] Refreshing state for all devices...
  follow-redirects options {
  protocol: 'https:',
  maxRedirects: 21,
  maxBodyLength: 10485760,
  path: '/homeassistant/skill',
  method: 'GET',
  headers: {
    Accept: 'application/json, text/plain, */*',
    'Content-Type': 'application/json;charset=utf-8',
    'User-Agent': 'axios/0.19.2',
    'Content-Length': 136
  },
  agent: undefined,
  agents: { http: undefined, https: undefined },
  auth: undefined,
  hostname: 'px1.tuyaus.com',
  port: null,
  nativeProtocols: {
    'http:': {
      _connectionListener: [Function: connectionListener],
      METHODS: [Array],
      STATUS_CODES: [Object],
      Agent: [Function],
      ClientRequest: [Function: ClientRequest],
      IncomingMessage: [Function: IncomingMessage],
      OutgoingMessage: [Function: OutgoingMessage],
      Server: [Function: Server],
      ServerResponse: [Function: ServerResponse],
      createServer: [Function: createServer],
      get: [Function: get],
      request: [Function: request],
      maxHeaderSize: [Getter],
      globalAgent: [Getter/Setter]
    },
    'https:': {
      Agent: [Function: Agent],
      globalAgent: [Agent],
      Server: [Function: Server],
      createServer: [Function: createServer],
      get: [Function: get],
      request: [Function: request]
    }
  }
} +511ms

**Comment by darkenv2** [comment]
Did that information help?

**Comment by milo526** [comment]
With all due respect, there is no need to ping this after 50 hours. I'm in the middle of the test weeks of my study; I hope you understand that has priority over this library for me now. If you want it fixed this badly please submit a PR and I'll be sure to swiftly take a look at it.

Lastly if this is all the output you get please take a look at "[How to check whether the API this library uses can control your device?](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)" cause probably none of your devices are compatible (if they where, there would be more debug output).
