### ISSUE TITLE
Smartlife fan cannot be detected/reflected on hoobs

### ISSUE THREAD

**Issue by Alvin-Ong-1988** [milo526/homebridge-tuya-web#304]
**Describe the bug**
Using this plugin with HOOBS to control my fan on smartlife (1 device only) however the HOOBS unable to detect any device after installing. But no errors can be found on the log.

**Steps To Reproduce**
7/19/2021, 6:18:44 PM: tuyawebbridge stopping
7/19/2021, 6:18:48 PM: Tuya Web Bridge starting
7/19/2021, 6:18:50 PM: Tuya Web BridgeLoaded plugin '@milo526/homebridge-tuya-web'
7/19/2021, 6:18:50 PM: Tuya Web BridgeLoading 1 platforms...
7/19/2021, 6:18:51 PM: Tuya Web BridgeBridge is running on port 51826.

**Plugin Version**
1.0.1
 
 **Homebridge Config**
{
    "accessories": [],
    "platforms": [
        {
            "options": {
                "password": "MY PASSWORD",
                "countryCode": "65",
                "platform": "smart_life",
                "username": "MY USERNAME"
            },
            "name": "TuyaWebPlatform",
            "platform": "TuyaWebPlatform",
            "scenes": false
        }
    ]
}
 
 
 ```json

```
 
 **Device Config**
Getting credentials
Got credentials
{   'access_token': 'EUheu1603710099811zzA7oBTIQYlaCEI',
    'expires_in': 864000,
    'refresh_token': 'EUheu1603710099811zzA7oU21nJfXif3',
    'token_type': 'bearer'}
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': 'o4sCcqwiudT6sPID',
                                      'name': '\\"Smart Ceiling Fan\\" Wind '
                                              'Speed Level: Level 1'}],
                   'scenes': []}}
!!! NOW REMOVE THIS FILE, SO YOUR CREDENTIALS (username, password) WON'T LEAK !!!

**Comment by Alvin-Ong-1988** [comment]
I’m sorry but the Issue have not been resolve.

**Comment by Alvin-Ong-1988** [comment]
Hi. Anybody can advise me on the issue?

**Comment by Alvin-Ong-1988** [comment]
Hi Milo Cesar Sir, can you please advise on my issue if possible. Thanks a million.

**Comment by milo526** [comment]
Your original post shows that no devices are exposed. Sadly it seems that Tuya does not expose your devices via the HomeAssistant API.
Since im not affiliated with Tuya there is nothing I can do to change this.

**Comment by Alvin-Ong-1988** [comment]
Hi Sir, thanks for the reply. I did not know my device was not expose to Tuya. 
Under Device Config under which line do i know if the device is expose to Tuya?
Under Payload line??
