### ISSUE TITLE
Friedrich floating air pro ductless AC

### ISSUE THREAD

**Issue by banjobanjobanjo** [milo526/homebridge-tuya-web#305]
Hi. Thank you so much for what you’ve made! I was able to add my Friedrich Floating Air pro ductless AC units using the plugin, but I hit some challenges:
1. I use Fahrenheit temp measurement on these units and in homekit, but the plug-in seems to require using Celsius. And when I change the target temperature in homekit, it forces the AC units to Celsius.
2. I experienced what others have noted, that the temperature reported in homekit is a high number (150), but when I follow the temperature factor instructions, it returns a lower number, but still incorrect (C of F).
3. My devices only show heat control, but they are heat and cooling.

It’s able to communicate—that much I know. Homekit can turn on and off the units, and can attempt to change the temp (though that’s when it forces them to C).

thank you for your guidance. Happy to pay for this amazing convenience.

**Comment by milo526** [comment]
I'm sorry but the question you raise seem very specific to your device, I have no clue how to handle them.

All temperatures in Homekit MUST be in celsius, whenever you change the temperature in the Home app (probably in Fahrenheit) it will still use celsius under the hood.

It might be that the interface between your device and Tuya is wrong in this case or that your device does not use the Tuya provided soft- and/or hard-ware correctly but that is impossible for me to check/verify.

**Comment by banjobanjobanjo** [comment]
Thanks. I understand it’s unique to my hardware. I just wanted to see if there was something simple I was missing. The larger issue for me is that homebridge forces my ductless AC units over to C any time I use homekit to change the target temp. Is that something you’ve seen before? Thank you.

**Comment by milo526** [comment]
Nope never heard of that issue before, then again, I live in an area of the world that uses proper metrics 😛 I have never had any thermostat that uses Fahrenheit

**Comment by banjobanjobanjo** [comment]
Well played. Sorry to take more of your time, but where might I go from here? I would rather make it work with Tuya Web, rather than buying a third party device like the Mysa AC units, but maybe that’s all I can do.
