### ISSUE TITLE
Smart plug detected, but not showing up on Hoobs

### ISSUE THREAD

**Issue by pedrocs** [milo526/homebridge-tuya-web#306]
I ran the Python script provided, here's my output:

Getting credentials
Got credentials
{   'access_token': 'EUheu1627303626310DDtgQFiWezgLWbo',
    'expires_in': 864000,
    'refresh_token': 'EUheu1627303626310DDtgQDO1DbBA2J8',
    'token_type': 'bearer'}
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/solution/134001/66ba22c327bfbf3d_cover.png',
                                      'id': 'bf86478160b2cfae3fzfzc',
                                      'name': 'Big light'}],
                   'scenes': []}}

Thanks!

**Comment by milo526** [comment]
Do you have any logs? 

Could you please try running hoobs in debug mode and provide the startup logs for this plugin.
