### ISSUE TITLE
Can’t add a Tuya relay Switch 

### ISSUE THREAD

**Issue by Lui5Jacint0** [milo526/homebridge-tuya-web#307]
**Describe the bug**
I have configured the pluggin in homebridge with the correct info (pasted the device id from Tuya app), but an error occurs: “Tried overwriting device config for: ***** which is not a valid device id

**Steps To Reproduce**

**Plugin Version**
 
 
 **Homebridge Config**
 
 
 ```json

```
 
 **Device Config**

 
 
 **Additional Context**

**Comment by milo526** [comment]
The previous edits to your question seem to suggest that your username or password is wrong.

If you fixed that issue but still get the same error, please fill in the issue template as requested so I can help you.
At the moment your question is lacking all the info that I need to troubleshoot this for you.

**Comment by Lui5Jacint0** [comment]
**Describe the bug**

I have configured the pluggin in homebridge with the correct info (pasted the device id from Smart Life app), but an error occurs: “Tried overwriting device config for: ***** which is not a valid device id. Even though it works on the script available in documentation.



**Steps To Reproduce**


**Plugin Version**

homebridge-tuya-web v1.0.2
 
 
 **Homebridge Config**
 
 
 ```json
{
    "name": "TuyaWebPlatform",
    "options": {
        "username": "********mail.com",
        "password": "*******",
        "countryCode": "351",
        "platform": "smart_life"
    },
    "defaults": [
        {
            "id": "138561742462ab3bbf0f",
            "device_type": "light"
        }
    ],
    "scenes": false,
    "platform": "TuyaWebPlatform"
}
```
 
 **Device Config**
 
 
 **Additional Context**

**Comment by Lui5Jacint0** [comment]
Any update regarding this issue?

**Comment by milo526** [comment]
Your device is not being exposed to the Tuya HomeAssistant API, since I'm not affiliated with Tuya, there is nothing I can do to help you.
