### ISSUE TITLE
Login to Tuya Web fails

### ISSUE THREAD

**Issue by Thomas0901** [milo526/homebridge-tuya-web#31]
**Describe the bug**
I installed HomeBridge and then the TuyaWeb Plugin here for my sockets (brand Teckin, app Smart Life)
The spckets I have in my Smart Life app do not appear.
The status log provides details that login fails, though I provided the same settings as in the app
Where can I check this on the web? Reset password?

[7/10/2020, 10:13:33 PM] Homebridge is running on port 51071.
[7/10/2020, 10:13:33 PM] [TuyaWebPlatform] Error: Authentication fault: Get accesstoken failed. Username or password error!
    at /usr/local/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:213:44
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Device**
 - Plugin: [See manufacturer in your homekit device] Teckin
 - Version: [See firmware in your homekit device]
 - Model : [See model in your homekit device] SP12
 - Device-config: [Follow the steps as described [here](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device) and post the output]

**Additional context**

**Comment by milo526** [comment]
Hey can you try running [this script](https://github.com/milo526/homebridge-tuya-web/blob/master/tools/debug_discovery.py) on a service such as https://repl.it?

Do you by any chance use sign-in with Apple?

**Comment by Thomas0901** [comment]
Hi,
Tried the script, same error.
yes i do use apple login. Should i delete the account and start all over without apple login?

**Comment by milo526** [comment]
Yeah that's te error; See also #21; when you use sign-in with apple; apple generates a new private email adres for you that they forward to your actual email adres; this makes Tuya think that apple's email adres is your real one and thus your credentials don't work. As far as I'm aware there is no easy way to get your "private apple email" so you'll have to create a new account.

**Comment by daveyijzermans** [comment]
Wanted to let people that are running into this issue know that you can create a new account, add that new account as a member to your existing home and transfer ownership to the new account. That way you don't have to re-add devices to your home.
Also wanted to note that you can partially see the Apple randomly generated e-mail address in the Home settings. Home management > [Home name] > tap your name and the beginning of the random e-mail address is [displayed](https://imgur.com/A4JJwVn). But it cannot be copied :(

**Comment by milo526** [comment]
Thank you for sharing that! that helps people who have this problem a lot.

**Comment by yaroslavYS** [comment]
I experience same problem - initially I signed in with Google, then added a password
but repl giving me

```
Getting credentials
Got credentials
{   'errorMsg': 'Get accesstoken failed. Username or password error!',
    'responseStatus': 'error'}
{'responseStatus': 'error', 'errorMsg': 'Get accesstoken failed. Username or password error!'}
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    payload = {"accessToken": auth_response["access_token"]}
KeyError: 'access_token'
```

**Comment by milo526** [comment]
Same issue - same solution, don't use any Oauth provider (login with google, login with apple etc.) just create a Tuya account and it will work.

**Comment by yaroslavYS** [comment]
thank you - so I'll wait 7 days till they delete my account - because I can't re-use it

**Comment by mbierman** [comment]
@daveyijzermans you can use a modified version of your gmail address

name@gmail.com = n.ame@gmail.com

https://gmail.googleblog.com/2008/03/2-hidden-ways-to-get-more-from-your.html

**Comment by daveyijzermans** [comment]
@mbierman Thanks, yes, I have. Now waiting for Smart Life/Tuya to delete my Oauth-besmudged account so I can create a new, clean one. The hoops we jump through... 😄

**Comment by mbierman** [comment]
@daveyijzermans strange thing...I went to reset my password and now my account isn’t working.

**Comment by jeylites** [comment]
Previously I used Oauth to login, after reading the comments here; I signed out and created a new login from the Tuya platform using a different email address. Unfortunately, I get the same issue `Error: Authentication fault: Get accesstoken failed. Username or password error!`

**Comment by randy3k** [comment]
> Previously I used Oauth to login, after reading the comments here; I signed out and created a new login from the Tuya platform using a different email address. Unfortunately, I get the same issue `Error: Authentication fault: Get accesstoken failed. Username or password error!`

I am in the same boat. I have to create a new account to make it work.

**Comment by cumanzor** [comment]
The same thing will happen if you first created your account with a phone then added an email later on.
