### ISSUE TITLE
https://plugins.hoobs.org/plugin/@milo526/homebridge-tuya-web

### ISSUE THREAD

**Issue by jhameiri** [milo526/homebridge-tuya-web#314]
**Describe the bug**

**Steps To Reproduce**

**Plugin Version**
 
 
 **Homebridge Config**
 
 
 ```json

```
 
 **Device Config**
 
 
 **Additional Context**
 

Hello
I installed TUYA CURTAIN SWITCH with the SMART LIFE app, and it works properly ,with all the functionality (OPEN, STOP, CLOSE).
To work with Apple's ecosystem, I use the HOOBS bridge.
With TUYA's plugin.(https://plugins.hoobs.org/plugin/@milo526/homebridge-tuya-web)
The problem is that the curtain (with Apple's home) can only be controlled with full opening or full closing, because there is no stop button.
what can we do?

Regards
Joseph

**Comment by davic80** [comment]
Same issue here

**Comment by milo526** [comment]
Sadly there is nothing you can do. Apple does not seem to support this action in HomeKit for now.
