### ISSUE TITLE
Changing device name or model

### ISSUE THREAD

**Issue by g33z3riley** [milo526/homebridge-tuya-web#316]
Hey great work on this plugin! Just wondering if it is possible to change the device name or model in homebridge - I am using several of these devices in Node-red to integrate with my CBUS lighting system and each shows up as switch-switch (name-model) - node red seems to be unable to distinguish between them and defaults to just controlling the first instance. It would be amazing if there was a way of changing either of these in the config?

**Comment by milo526** [comment]
HomeKit should (and always did) report the names correctly (based on the name you set in the Tuya app).
That is the best I can do sadly, i would have no clue how I could otherwise change the node-red name.

**Comment by g33z3riley** [comment]
Thanks for getting back to me so quickly Milo! No worries I think it's a tuya thing - I'll forget the node red bit and just do the automations in homebridge.
