### ISSUE TITLE
Merkury BW210-999W not showing up 

### ISSUE THREAD

**Issue by PlatGitHub468** [milo526/homebridge-tuya-web#317]
**Describe the bug**

Hello,
I have some Mercury BW210-999W.  It's showing up in my SmartLife App along with other devices.  I can control the light (turn on/off, change color, brightness) in SmartLife App.  However, using your home bridge plugin, this light does not show up anywhere in HomeKit.  My other SmartLife devices show up in HomeKit.   

Do you have any suggestion on how to troubleshoot this?

**Steps To Reproduce**

**Plugin Version**
 
 
 **Homebridge Config**
 
 
 ```json

```
 
 **Device Config**
 
 
 **Additional Context**

**Comment by milo526** [comment]
Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

Without this, it is hard for me to help you with regards to this specific issue.
