### ISSUE TITLE
Color and Temperature selection in Home app does not work correctly

### ISSUE THREAD

**Issue by nedvisol** [milo526/homebridge-tuya-web#32]
**Describe the bug**
I have Feit Electric recessed LED light bulbs - color and tunable white, Tuya-compliant (model LEDR6). The on/off, brightness features work fine. However, when I select a color in the Home app, the bulbs don't change the color correctly 50% of the time. When they are not correct, the color from the bulb is pale white, dimmed, and sometimes flickered. This does not happen when I changed the color through Feit app (colors set correctly at the bulbs.)

**To Reproduce**
1. Setup homebridge-tuya-web per instructions
2. Open the Home app on iOS
3. Open up light bulb accessory
4. Change the color to any color (red, green, blue, or something) in the color dial.

**Expected behavior**
Color is shown correctly at the bulb.

**Screenshots**
Sorry, didn't take photos of the light

**Device**
 - Plugin: @milo526/homebridge-tuya-web
 - Version: 0.3.34-0
 - Model : LIGHTBULB

**Additional context**
It seems the problem has to do with how Homebridge/Home app sends events when a color is selected. When you select a color, the Home app fires 2 `set` events back-to-back; one to set Hue and one to set Saturation. This creates a race condition in the code that causes two `setDeviceState` calls being made, one with correct Hue value but old/stale Saturation %, and one with correct Saturation % but with old/stale Hue value.

I fixed this by wrapping the setColor method using debounce so it will wait for all the setHue and setSaturation calls to complete, and use the last values. Also in the `setColor` method, use the value from cached state rather than the passed in `color` value.

This seems to work well but the downside is that we always return successful callback `set` method.

I'll add my PR shortly. (PS it also has the color temperature code...)

**Comment by gashead76** [comment]
This is great, I hope it fixes the issue for me as well. Thanks a bunch for doing this!

**Comment by milo526** [comment]
As mentioned in the #33, `@milo526/homebridge-tuya-web@beta` should include these fixes, in a way that the Home app still gets the proper callback. Could you please install the beta version and see if that solves your issues?

**Comment by nedvisol** [comment]
@milo526 I love the new refactored accessory code. Looks awesome!

**Comment by nedvisol** [comment]
@milo526 just installed the `@beta` and it's working well! Actually much better than what I had in my code. Let me close this bug now. Thank you so much!
