### ISSUE TITLE
wrong status thermostats

### ISSUE THREAD

**Issue by paqpaqpaq** [milo526/homebridge-tuya-web#330]
**Describe the bug**
Regardless its actual state, home app always shows HEATING, when idle, not heating, or heating.
It will show OFF once switched to OFF

**Steps To Reproduce**

Set thermostat to lower value than actual temperature

**Plugin Version**

 1.0.2

 **Homebridge Config**

 
 ```"defaults": [
                {
                    "id": "58542378bcddc2408874",
                    "device_type": "climate",
                    "min_temper": "15.0",
                    "max_temper": "25.0"
                }



```
 
 **Device Config**
```
{   'data': {   'current_temperature': 23,
                                                  'max_temper': 35,
                                                  'min_temper': 5,
                                                  'online': True,
                                                  'state': 'true',
                                                  'temperature': 16},
                                      'dev_type': 'climate',
                                      'ha_type': 'climate',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1522639892fyvv6kiwqyxjbkzjp3rpv6lxr_0.png',
                                      'id': '58542378bcddc2408874',
                                      'name': 'Verwarming'},
```

**Comment by milo526** [comment]
I'm currently not able to check, but if I remember correctly this is not something this plugin controls.
I believe that the state is heating if and only if the desired temperature > actual temperature.

Are the temperatures being reported correctly?

**Comment by paqpaqpaq** [comment]
The temperatures are reported correctly.

The thermostat either heats (ON), or is OFF... those are the two states in the tuya platform I guess.
But this way it 'heats' a room of 20 degrees to the set 17 e.g. Quite weird. 

The plugin reports errors when trying to set on cool or AUTO.
Tuya has also options for  home, away, smart and sleep.

in the developer platform these are the only settings as far as I can find.
Manually setting the JSON 'switch' to false, switches off the thermostat.
```
temp_set | Integer | {   "unit": "℃",   "min": 5,   "max": 35,   "scale": 0,   "step": 1 }
switch | Boolean | "{true,false}"
child_lock | Boolean | "{true,false}"
temp_current | Integer | {   "unit": "℃",   "min": 0,   "max": 50,   "scale": 0,   "step": 1 }


```

**Comment by dpamping** [comment]
I’m having the same problem

**Comment by Catta1997** [comment]
any fix?
