### ISSUE TITLE
White/Color mode light source

### ISSUE THREAD

**Issue by edwerde** [milo526/homebridge-tuya-web#333]
**Is your feature request related to a problem? Please describe.**

My light bulbs have the white and color mode separated.
**Describe the solution you'd like**

Adding a separate white mode/color mode light source 

**Describe alternatives you've considered**

**Additional context**

**Comment by edwerde** [comment]
![image](https://user-images.githubusercontent.com/39650829/135330263-23a84775-cded-4f73-b4b2-4c496f093882.png)
This is what the plugin currently does when i ask siri to turn the light white

**Comment by milo526** [comment]
Sadly this is not something I can change.
This is due to the specific implementation by Tuya which I can not alter.
