### ISSUE TITLE
Simple switch that control fan power doesn't work 

### ISSUE THREAD

**Issue by idanmantin** [milo526/homebridge-tuya-web#338]
Hey,

I setup all my Tuya devices with this plugins (smart light switch, outlet, double light switch).
All work perfectly except one device, actually switch that I setup as fan - it's seems like the request to the device won't sent.

From Tuya APP in my iPhone I can control the fan (simple switch).

I tried to set my device as switch (liked other component in my home), but it's still not working.

Could you tell me what is the problem ? I tried to debug...

**Comment by benisdev-py** [comment]
same issue

**Comment by idanmantin** [comment]
Thank you, after resetting the switch it worked.
