### ISSUE TITLE
[NEW DEVICE] Kogan Garage Door Opener

### ISSUE THREAD

**Issue by walshy1009** [milo526/homebridge-tuya-web#34]
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {   'online': True,
                                                  'state': 1,
                                                  'support_stop': False},
                                      'dev_type': 'cover',
                                      'ha_type': 'cover',
                                      'icon': 'https://images.tuyaeu.com/
smart/icon/ay15253387844269Sg99/1574046954ea7319a4965.png',
                                      'id': '82553610d8f15bb41be0',
                                      'name': 'Kogan Smart Wireless Garag
e '
                                              'Door Opener'}],
                   'scenes': []}}
!!! NOW REMOVE THIS FILE, SO YOUR CREDENTIALS (username, password) WON'T 
LEAK !!!

**Comment by milo526** [comment]
Support for cover accessories is tracked in #30
