### ISSUE TITLE
Authentication error: you cannot auth exceed once in 60 seconds

### ISSUE THREAD

**Issue by MattRoe84** [milo526/homebridge-tuya-web#350]
**Describe the bug:**
I've had the plugin up and running fine with no issue for some time and a couple of nights back night im now getting this error. 

[TuyaWebPlatform] Cannot acquire token, waiting 65 seconds. [TuyaWebPlatform] Retrying authentication after previous error.
[10/16/2021, 8:48:58 AM] [TuyaWebPlatform] Authentication error: you cannot auth exceed once in 60 seconds

**Plugin Version - v1.0.2**
  
 **Homebridge Config**
 {
    "name": "TuyaWebPlatform",
    "options": {
        "username": "***@***",
        "password": "*****",
        "countryCode": "44",
        "platform": "smart_life",
        "pollingInterval": 10
    },
    "defaults": [
        {
            "device_type": "form"
        }
    ],
    "scenes": false,
    "platform": "TuyaWebPlatform"
}
 
 
 **Device Config - errors**

auth_response = requests.post(
Getting credentials
Got credentials
{   'errorMsg': 'you cannot auth exceed once in 60 seconds',
    'responseStatus': 'error'}
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    payload = {"accessToken": auth_response["access_token"]}
KeyError: 'access_token'

**Comment by Hendriks046** [comment]
I’m having the same problem over and over again. It starts to annoy me! Look at my thread #346 

I asked @milo526 to reopen the issue.
