### ISSUE TITLE
One light out of six is not responding to homebridge (works fine from Smart Life app)

### ISSUE THREAD

**Issue by mgrosman** [milo526/homebridge-tuya-web#357]
**Describe the bug**

I have several devices set up via HOOBS, among them are six identical light switches. One of these stopped responding to on/off commands from HOOBS / Homebridge. However, I can turn it off/on over WIFI without issues from the Smart Life app (so the device itself seems to be ok). 

It has the same basic configuration as the other light switches, and I've verified that the device ID matches the device ID in the Smart Life app. Also tried changing the device type from Light to Switch back and forth and that didn't make a difference.

![image](https://user-images.githubusercontent.com/8738264/139257005-06c30546-262f-4e34-ad2c-c2647110e2db.png)

**Steps To Reproduce**

**Plugin Version**
 
I'm on 1.0.2 (Latest version as of this writing)

 **Homebridge Config**
 
 
 ```json
{
    "accessories": [],
    "platforms": [
        {
            "platform": "TuyaWebPlatform",
            "name": "TuyaWebPlatform",
            "options": {
                "platform": "smart_life",
                "username": "REDACTED",
                "password": "REDACTED",
                "countryCode": "REDACTED",
                "pollingInterval": 600
            },
            "scenes": false,
            "defaults": [
                {
                    "id": "bf3211fc33acb5e7e6rvya",
                    "device_type": "light"
                },
                {
                    "id": "0861648384cca8b800ee",
                    "device_type": "light"
                },
                {
                    "id": "0861648384cca8b858db",
                    "device_type": "light"
                },
                {
                    "id": "0861648384cca8b7dd9c",
                    "device_type": "light"
                },
                {
                    "id": "0861648384cca8b731b3",
                    "device_type": "light"
                },
                {
                    "id": "bf73e6faa6f6db6751iele",
                    "device_type": "outlet"
                }
            ]
        }
    ]
}
```
 
 **Device Config**
 
 Getting credentials
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fa30ed2b070>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='px1.tuyail.com', port=443): Max retries exceeded with url: /homeassistant/auth.do (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa30ed2b070>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 20, in <module>
    auth_response = requests.post(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='px1.tuyail.com', port=443): Max retries exceeded with url: /homeassistant/auth.do (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa30ed2b070>: Failed to establish a new connection: [Errno -2] Name or service not known'))

 **Additional Context**
 
As I noted above the device ID matches the ID in the tuya app. Seems like a communication issue between homebridge and the Tuya API perhaps (though why only for this one light, whereas all the others work as expected). 

**The device ID for the one that's not responding is: 0861648384cca8b731b3**

Thanks for your help!

**Comment by k3lv1n90** [comment]
Having the same issue as well, one light out of nine will have this issue, can't switch on/off except from the smart life app, tried removing polling interval, tried adding that specific light into homebridge using virtual id, tried using bridge settings but still won't work.

**Comment by mgrosman** [comment]
Cheers @k3lv1n90 good to know I'm not the only one running into this issue :)

I've done a bit more digging and looks like the API requests are successfully accepted by the Tuya cloud platform. But then the Tuya app fails to trigger the required action. 

Here's what it looks like on a light switch that functions properly - there's a request from Homebridge (listed as home_assistant) with the required action (ex ON), followed by the action by the device itself. 

![image](https://user-images.githubusercontent.com/8738264/139584778-a4381348-5d1f-42f6-bdae-457224381882.png)

On the other hand, here's what it looks like on the device that's not responding - the request from Homebridge is received, but it's not followed by the second request with the device itself action from Tuya. 

![image](https://user-images.githubusercontent.com/8738264/139584997-72cb22d7-92db-42bb-bc2f-2b1f6df0cc41.png)

I also tried to trigger the device from the Tuya console debugger and it did not respond to that either. So seems like the issue may be with communication between the Tuya cloud service and the Smart Life app perhaps?

@milo526  any thoughts?

**Comment by many7695** [comment]
I have two devices that don’t show up a smart power switch and a Star Projector Smart Night Light

**Comment by toddcavanaugh** [comment]
This just started happening for me as well. 6 identical fixtures (Feit), 1 just stopped working in Home but works fine from Smart Life. Annoying! Would be nice to know if it's software that will get sorted out or if I need to return one and try to get another fixture.

**Comment by k3lv1n90** [comment]
I fixed all the issue by simply changing plugin, this is the official tuya plugin for homebridge. Much better since, haven't had any issues

https://github.com/tuya/tuya-homebridge

**Comment by toddcavanaugh** [comment]
Thanks, @k3lv1n90. I did the same after your recommendation. It was much more complicated to set up but finally got it working. I don't really understand the API call limits so hopefully it's not an issue on the free version.
