### ISSUE TITLE
Implement Clan at Home

### ISSUE THREAD

**Issue by frizby66** [milo526/homebridge-tuya-web#36]
Unable to implement tuya api for Clan_at_home. Clan at home works with tuya Alexa skill but log says it’s no valid taken revived, username or password incorrect. 

Also, Alexa skill implements up camera support, is this possible?

**Comment by milo526** [comment]
The log clearly states that your username or password is incorrect. This is not an issue with the plug-in.
Do you by any chance use sign-in with Apple? That is not supported by this plugin.

Cameras cannot be supported by this plugin due to api limitations.

**Comment by frizby66** [comment]
I think the issue is with the platform option. You can have tuya, smart life, etc. but when I enable the skill in Alexa, the skill shows “Clan at Home”, which is the app I am using but the skill is the smart life skill. Does that make sense? Not using Apple ID to login.

**Comment by milo526** [comment]
I have no clue what clan at home is not do I have the time to figure out all these different systems.

You should be able to add this device to the guys or smartphone apps, once you have done that you can use their respective platform options and it should work.
