### ISSUE TITLE
Multiple tiles of the same devices appearing on Homekit

### ISSUE THREAD

**Issue by freemanuk** [milo526/homebridge-tuya-web#368]
Hi there, 

I have recently added a ZemiSmart Homekit Zigbee Hub to my Smartlife app, so that I can pair zigbee devices to Homekit. However, the zigbee devices are appearing on Homekit through the ZemiSmart Homekit Zigbee Hub and Homebridge at the same time. I am now having 2 sets of same tiles for each devices. I tried to hide ZemiSmart Homekit Zigbee Hub from my Homekit with the configuration as shown below, but the zigbee devices are still appearing through Homebridge. Is there anyway to overcome this? Thank you.

{
    "platform": "TuyaWebPlatform",
    "name": "TuyaWebPlatform",
    "scenes": true,
    "options": {
        "platform": "smart_life",
        "username": "XXXXXXXX@XXXX.com",
        "password": "XXXXXXXX",
        "countryCode": "##"
    },
    "hiddenAccessories": [
        "bf5e8a081eecf24a951xbd"
    ]
}

**Comment by milo526** [comment]
Hello,

I'm gonna need some more info from you.
Zigbee devices should not be exposed through my plugin so I don't understand how adding a zigbee hub could create duplicate devices?
Could you post a screenshot of your control app (probably the iOS home app) to show what you mean?

Please all post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)
These results will show if my plugin is indeed exposing these devices (and if so how they are exposing them and probably why)
