### ISSUE TITLE
Tuya Device Status no longer update on Homekit

### ISSUE THREAD

**Issue by freemanuk** [milo526/homebridge-tuya-web#369]
Hi, just doing a quick check. If anybody encountered Tuya Device Status no longer update on Homekit like my case. Homekit will not update the device status if the device is switched on/ off via Smartlife app or Alexa. The status is forever unchanged unless you click on Home app.

**Comment by freemanuk** [comment]
The device status update is back, but taking about 5 to 10 mins to update now.

**Comment by lowellstewart** [comment]
I am seeing something similar... but all of my Tuya devices are no longer working in Homekit at all.
The devices (I have two outlets and two smart switches) all work normally and quickly from the Tuya app on my phone.  And the devices still show up in HomeKit/Apple Home.  But when I switch them using the Tuya app, the status doesn't update in the Apple Home.  Also, attempting to switch the devices on or off through the Apple Home app, or through the HOOBS front-end, does not have any effect on the devices themselves.  It's like the bridge stopped working or something, but I have updated/rebooted everything multiple times and it all just seems to have stopped working. 

It was working great only a few weeks ago.

**Comment by lowellstewart** [comment]
Ah, nevermind.  I finally noticed an authentication error in my log.  I'm not sure how that happened, but apparently something went awry there.  Sorry for the noise.

**Comment by SanityFox** [comment]
I'm having this problem too since the new HomePod updates as part of the Monterey 12.1 update. Devices appear in HomeKit, but nothing is changeable. Going to the dashboard in Homebridge, I am unable to control devices there too.

**Comment by milo526** [comment]
@SanityFox Do you have any errors in your logs? If so please see if there is a matching issue already opened or create a new issue please.
