### ISSUE TITLE
Can't change brightness or color of smart LED strips

### ISSUE THREAD

**Issue by carter0nline** [milo526/homebridge-tuya-web#375]
(Repost because nobody responded before previous issue was autoclosed, which, by the way, is kinda dumb when dealing with bug reports)
Hello. I was able to get my devices from Tuya up and running in HOOBS and added to HomeKit. Only problem is that I cannot change the brightness or color of my smart LED strips. When changing these properties in HOOBS or HomeKit, the lights do absolutely nothing. Turning on/off seems to work fine.

Steps To Reproduce
Change brightness or color of smart LED strips

Plugin Version
1.0.2

Homebridge Config

{
   "platform": "TuyaWebPlatform",
   "name": "TuyaWebPlatform",
   "options": {
       "username": "[REDACTED]",
       "password": "[REDACTED]",
       "countryCode": "1",
       "platform": "tuya",
       "pollingInterval": 1000
   }
}
Device Config

I could not get the script here to run without erroring, so I can't provide the output.
Additional Context

Not much else I can say

**Comment by milo526** [comment]
You are free to maintain your own open-source work in which you can deal with issues the way you want to, I'll do it my way in my repositories.

I cannot reproduce this issue and it is missing critical information.
The script still works for me and for other users, please provide me with the output of that script, it is essential to help you now.
