### ISSUE TITLE
Electric Radiator - Temperature shows x 10. Works with Smart Things but HK  shows 160 when Temp is 16. Tried factor controls but doesn’t change? Please confirm if Heaters are compatible with this plug-in, I used Thermostat? Thanks

### ISSUE THREAD

**Issue by MarkP63** [milo526/homebridge-tuya-web#377]
**Describe the bug**

**Steps To Reproduce**

**Plugin Version**
 
 
 **Homebridge Config**
 
 
 ```json

```
 
 **Device Config**
 
 
 **Additional Context**

**Comment by MarkP63** [comment]
Apologies meant SmartLife App

**Comment by milo526** [comment]
Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device) and your current configuration as set in homebridge/hoobs.

Without this it is hard for me to help you with regards to this specific issue.

**Comment by MarkP63** [comment]
Python Script Test - https://repl.it/



Getting credentials
Got credentials
{   'access_token': ‘xxxxxxxxxxxxxxxxxxxxxxxxxxxx’
    'expires_in': 864000,
    'refresh_token': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'token_type': 'bearer'}
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {   'current_temperature': 100,
                                                  'max_temper': 300,
                                                  'min_temper': 70,
                                                  'online': True,
                                                  'state': 'true',
                                                  'temperature': 115},
                                      'dev_type': 'climate',
                                      'ha_type': 'climate',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/ay1555980033059u7AZh/158650072820f486513da.png',
                                      'id': 'bfccb1533f215093479r8j',
                                      'name': 'Studio radiator  2'},
                                  {   'data': {   'current_temperature': 105,
                                                  'max_temper': 300,
                                                  'min_temper': 70,
                                                  'online': True,
                                                  'state': 'true',
                                                  'temperature': 115},
                                      'dev_type': 'climate',
                                      'ha_type': 'climate',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/ay1555980033059u7AZh/158650072820f486513da.png',
                                      'id': 'bf3dfd860f9e226a26hyjs',
                                      'name': 'Studio radiator 1'},
                                  {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': 'tux3ygpFcE9O26D5',
                                      'name': 'Studio Rads 16.0°C'},
                                  {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': 'uLTVXDX8xN3JVEcK',
                                      'name': 'Studio Rads 11.5°C'},
                                  {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': 'qAPe3Es0GPY0lwO4',
                                      'name': 'Studio Rads 7.0°C'},
                                  {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': 'bi4KW2CEgDOHhr4v',
                                      'name': '\\"Hifi lamp\\" Switch '
                                              '1:Reverse Switch'},
                                  {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': '5cq0yE6nZQEzIrXn',
                                      'name': 'All Switch OFF'},
                                  {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': 'ubXsu44CYqoVoFIg',
                                      'name': 'All Switch ON'},
                                  {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': 'yR741ubZvDA2wHpK',
                                      'name': 'All OFF'},
                                  {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': 'jka5EZLRWCRlEBC1',
                                      'name': ' All ON'}],
                   'scenes': []}}
!!! NOW REMOVE THIS FILE, SO YOUR CREDENTIALS (username, password) WON'T LEAK !!!
 

Please can you tell from this file as per your instructions? tks

**Comment by m4gn3to** [comment]
I'm facing the same issue but with a thermostat:

Getting credentials
Got credentials
{   'access_token': '*******************************************',
    'expires_in': 864000,
    'refresh_token': '*******************************************',
    'token_type': 'bearer'}
Getting devices
Got devices
{   'header': 
  {'code': 'SUCCESS', 'payloadVersion': 1},
  'payload': {   
  'devices': [   
  {   
    'data': 
    {   
      'current_temperature': 41,
      'max_temper': 35,
      'min_temper': 5,
      'online': True,
      'state': 'true',
      'temperature': 40},
      'dev_type': 'climate',
      'ha_type': 'climate',
      'icon': 'https://images.tuyaeu.com/smart/icon/15264583415nnlzwfs1qd2wqz6i937op3nmi_0.png',
      'id': '*******************',
      'name': 'Termostato Salón'}],
      'scenes': []
    }
  }
!!! NOW REMOVE THIS FILE, SO YOUR CREDENTIALS (username, password) WON'T LEAK !!!

**Comment by milo526** [comment]
Are you using the config ui-x plugin?
If so (for the both of you), please add a new device config.
Set the correct id (or name, but preferably id), select the correct device type, and set temperature factor accordingly.
So in the case that your themostat is reporting 160 instead of 16, set it to `0.1`

![Config screenshot](https://user-images.githubusercontent.com/5261909/147098801-2237ab41-4912-4973-8f21-6e734477be8e.png)

**Comment by m4gn3to** [comment]
Thank you very much!!!

Now it works !!!!!!!!!!
