### ISSUE TITLE
LED Strip colors not working

### ISSUE THREAD

**Issue by carlosveny** [milo526/homebridge-tuya-web#392]
**Describe the bug**
When trying to change the color of the LEDS in Homekit the device says "No response" and the color doesn't change at all. However on/off works properly.

**Steps To Reproduce**
1. Go to the LEDS accessory.
2. Try to change the color.
This is what i get in Homebridge:
[1/9/2022, 6:45:05 PM] [TuyaWebPlatform] [LEDS Nuevos] - [SET] Invalid payload in response: {"payload":{},"header":{"code":"DependentServiceUnavailable","payloadVersion":1}}

**Plugin Version**
1.1.1
 
 **Homebridge Config**
 ```json
{
            "name": "TuyaWebPlatform",
            "options": {
                "username": "XXX@XXX",
                "password": "XXX",
                "countryCode": "34",
                "platform": "smart_life"
            },
            "defaults": [
                {
                    "id": "XXX",
                    "device_type": "light",
                    "light_characteristics": [
                        "Color"
                    ]
                },
                {
                    "id": "XXX",
                    "device_type": "light",
                    "light_characteristics": [
                        "Color"
                    ]
                },
                {
                    "id": "XXX",
                    "device_type": "light",
                    "light_characteristics": [
                        "Color"
                    ]
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        }
```
 
 **Device Config**
Getting credentials
Got credentials
{   'access_token': 'EUheu1604344367123CAGeH6YGV9yhq8q',
    'expires_in': 864000,
    'refresh_token': 'EUheu1604344367123CAGeHX2RypYzu8x',
    'token_type': 'bearer'}
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {   'color_mode': 'colour',
                                                  'online': True,
                                                  'state': 'true'},
                                      'dev_type': 'light',
                                      'ha_type': 'light',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/001460162698766TR4v1/15942862796a3a0a18daa.png',
                                      'id': 'XXX',
                                      'name': 'LEDS Javier'},
                                  {   'data': {   'color_mode': 'colour',
                                                  'online': True,
                                                  'state': 'false'},
                                      'dev_type': 'light',
                                      'ha_type': 'light',
                                      'icon': 'https://images.tuyaeu.com/smart/program_category_icon/dj.png',
                                      'id': 'XXX',
                                      'name': 'LEDS'},
                                  {   'data': {   'color_mode': 'colour',
                                                  'online': True,
                                                  'state': 'true'},
                                      'dev_type': 'light',
                                      'ha_type': 'light',
                                      'icon': 'https://images.tuyaeu.com/smart/solution/142006/b9dd72a8410f8faa_cover.png',
                                      'id': 'XXX',
                                      'name': 'LEDS Nuevos'},
                                  {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': 'WIiRjK8EzcvTYR2a',
                                      'name': '\\"Smart Strip\\" ON/OFF:OFF'},
                                  {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': 'r4OfdN1lECQoMIKs',
                                      'name': '\\"Smart Strip\\" '
                                              'ON/OFF:Reverse Switch'},
                                  {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': 'SvRvhF15RAvEXgtM',
                                      'name': '\\"Smart Strip\\" ON/OFF:ON'}],
                   'scenes': []}}
!!! NOW REMOVE THIS FILE, SO YOUR CREDENTIALS (username, password) WON'T LEAK !!!
 
 **Additional Context**
I don't think the problem is in my accessory because I have 3 different LED strips and none of them can change the colors through Homekit (in the smart life app it works).

**Comment by milo526** [comment]
Your lights do not support setting the colour through the api that this plugin uses.
That is what the `DependentServiceUnavailable` error means.

Sorry but there is nothing I can do for you.
