### ISSUE TITLE
2 switchs is not supported (only one switch is visible)

### ISSUE THREAD

**Issue by jmcollin78** [milo526/homebridge-tuya-web#393]
**Device type**
Double switch device: Loratap

**Device information**
```json
Getting credentials
Got credentials
{   'access_token': 'xxxx',
    'expires_in': 864000,
    'refresh_token': 'xxxx',
    'token_type': 'bearer'}
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/solution/137001/63ef34c2da0d9955_cover.png',
                                      'id': 'bfc55496803c3c235f7uqo',
                                      'name': 'Lumières cuisine'},
                                  ],
                   'scenes': []}}
!!! NOW REMOVE THIS FILE, SO YOUR CREDENTIALS (username, password) WON'T LEAK !!!
````
This is a double switch device. And only one switch is visible on Homebridge.

**Comment by jmcollin78** [comment]
If you gave me some guideline, maybe I will be able to develop myself an evolution for this feature

**Comment by milo526** [comment]
Hello, 
Please move to use a different API if this is a requirement for you.
The Tuya homeassistant API that this plugin uses is not compatible with multiple switches in one device.

For example you might want to take a look at the [first party plugin created by Tuya](https://github.com/tuya/tuya-homebridge) themselves.

**Comment by jmcollin78** [comment]
Many thank for this quick and valuable answer. I will have a look at this Tuya plugin
