### ISSUE TITLE
Thermostat target temperature not working and arrow up when it’s not heating

### ISSUE THREAD

**Issue by dpamping** [milo526/homebridge-tuya-web#394]
If I select a target temperature on the tuya app the Homekit device doesn't change. Also it shows the arrow for heating when the thermostat is not heating.
![IMG_9052](https://user-images.githubusercontent.com/74436764/149409647-ca165fb4-c243-46f0-9dc6-8055ec6273c3.PNG)
![IMG_9053](https://user-images.githubusercontent.com/74436764/149409664-f0f51c0f-6ac3-4b13-ba75-6e219f2f0d18.PNG)

**Comment by milo526** [comment]
The homekit status updates at most once over 5 minutes (or longer if you set a longer value in your config)
After this time it'll be updated correctly.
Sadly that is not something I can change due to limitations for the manufacturer.

**Comment by dpamping** [comment]
And what about the arrow showing when the thermostat is not heating. It shouldn’t be an arrow right?
