### ISSUE TITLE
Feature request: fan and light control

### ISSUE THREAD

**Issue by sdaltons1** [milo526/homebridge-tuya-web#396]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

A device type to control both fan and light.

**Describe alternatives you've considered**

Choosing whether I'd prefer fan OR light control and leaving it at that.

**Additional context**

Hello,

I have a couple of the Treatlife ceiling fan control and dimmer light switches (treatlife De-fan-15h-484) found here:

Smart Ceiling Fan Control and Dimmer Light Switch, Neutral Wire Needed, Treatlife 2.4Ghz Single Pole Wi-Fi Fan and Light Switch Combo, Works with Alexa, Google Home and SmartThings, Remote Control https://www.amazon.com/dp/B086PPRWL7/ref=cm_sw_r_cp_api_glt_i_YM4CJKT0S78XNN45KZT0?_encoding=UTF8&psc=1

I am using the Smart Life app and this plug-in. They show up in Homekit as fans. Just wondering if it would be possible to pull in the light dimmer aspect as well. It appears I could change the device type to dimmer, but then lose the fan aspect. Ideally I wouldn't have to choose one or the other. 

Let me know if I can provide any additional context. 

Thanks.

**Comment by milo526** [comment]
Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

Without this it is hard for me to help you with regards to this specific issue.

I'm strongly suspecting the light will not show up in there; if that is the case, I cannot add support for that light/fan combo to this plugin due to limitations imposed by the manufacturer of these products.

**Comment by sdaltons1** [comment]
{   'data': {   'online': True,
                                                  'speed': '2',
                                                  'speed_level': 4,
                                                  'state': 'true'},
                                      'dev_type': 'fan',
                                      'ha_type': 'fan',
                                      'icon': 'https://images.tuyaus.com/smart/icon/ay14906729310721fNjn/1568862398d42329fe9d0.jpg',
                                      'id': '850007548caab5ebce8c',
                                      'name': "Max's Fan MASTER"},

**Comment by milo526** [comment]
Sadly there is no light present so this plugin can not fix this problem.
You might want to take a look at the official Tuya plugin, that one will probably support your use case.
