### ISSUE TITLE
Motion Sensor Zigbee as socket/switch 

### ISSUE THREAD

**Issue by jraa** [milo526/homebridge-tuya-web#398]
**Describe the bug**

I have a motion sensor zigbee connected to gateway tuya and it shows as a socket/switch on HomeKit.

**Steps To Reproduce**

**Plugin Version**
 

Firmware 1.1.1
 
 **Homebridge Config**
 
 
 ```json
{
            "name": "TuyaWebPlatform",
            "options": {
                "username": ,
                "password": ,
                "countryCode": "351",
                "platform": "tuya",
                "pollingInterval": 900
            },
            "defaults": [
                {
                    "device_type": "form"
                }
            ],
            "scenes": false,
            "hiddenAccessories": [
                "Estore Varanda",
            ],
            "platform": "TuyaWebPlatform"
        }
```
 
 **Device Config**
 
 
 **Additional Context**

**Comment by milo526** [comment]
Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

Without this it is hard for me to help you with regards to this specific issue.
