### ISSUE TITLE
Sylvania support

### ISSUE THREAD

**Issue by mopx** [milo526/homebridge-tuya-web#40]
Hi, do you have any idea of what is the platform name for Sylvania Smart WIFI bulbs? The official app connects to tuya.com so I'm guessing it can be compatible with this plugin using the correct platform name. I've tried guessing it with no luck.

**Comment by milo526** [comment]
I am afraid that app is not supported by the API this plugin is using.
This however does not mean that you cannot use your devices with this plugin!

Please use one of the supported apps (Tuya, Smartlife, Jinvoo Smart) and add your devices there, if they are Tuya-compatible it shouldn't matter which app you are using. Once you have created an account for one of these apps and added your devices to that app/account, you should be able to use this plugin.

I understand that this seems stupid, having to move all your devices to a different app, but this is a limitation by Tuya, this is not something we can change.
