### ISSUE TITLE
RGB Lightbulb on SmartLife (brand: i2Go) not working properly on HomeKit (Homebridge)

### ISSUE THREAD

**Issue by petrocino** [milo526/homebridge-tuya-web#401]
**Describe the bug**

I've buyed 2 RGB Lightbulbs from i2Go brand on Brazil. They are fully compatible with Tuya Platform, and work very good into the Smartlife app.

So, I've installed this plugin at Homebridge.
The HomeKit does see the 2 lightbulbs, without problems. Turn on and off.
But when I try to set brightness, temperature and also color, doesn't work. The lights are not accurate (blue becomes purple, and both RED and GREEN has low bright), the brightness are very low, and cannot be changed.

**Steps To Reproduce**
1. Go to the device property on Home App
2. Click on any color (its not accurate)
3. Move the Brightness level. Nothing happens

**Plugin Version**
@milo526/homebridge-tuya-web v1.1.1
Firmware on Homekit device: "1.1.1"
 
 
 **Homebridge Config**
 
 
 ```json
{
            "name": "TuyaWebPlatform",
            "options": {
                "username": "**********",
                "password": "***********",
                "countryCode": "**",
                "platform": "smart_life"
            },
            "defaults": [
                {
                    "id": "************",
                    "device_type": "outlet"
                },
                {
                    "id": "************",
                    "device_type": "light",
                    "min_brightness": "10",
                    "max_brightness": "1100",
                    "min_kelvin": "10",
                    "max_kelvin": "1000",
                    "light_characteristics": [
                        "Brightness",
                        "Color",
                        "Color Temperature"
                    ]
                },
                {
                    "id": "************",
                    "device_type": "light",
                    "min_brightness": "10",
                    "max_brightness": "1100",
                    "min_kelvin": "10",
                    "max_kelvin": "1000",
                    "light_characteristics": [
                        "Brightness",
                        "Color",
                        "Color Temperature"
                    ]
                }
            ],
            "scenes": false,
            "hiddenAccessories": [
                "Varal de luz"
            ],
            "_bridge": {
                "username": "0E:FC:3A:1D:74:0E",
                "port": 43057
            },
            "platform": "TuyaWebPlatform"
        }
```
 
 **Device Config**

Sorry, I cannot perform it, I don't use HomeAssistant, I use Homebridge to get it working on HomeKit.
 
 
 **Additional Context**

**Comment by milo526** [comment]
I cannot reproduce this behavior with my own lamps, sadly I will not be able to help you without the requested API output.
There is nothing home-assistant specific to the steps outlined, please try once more to see if you can get me this output.
