### ISSUE TITLE
[NEW DEVICE] dlq Device Type - Already supported in other forks and Tuya IoT Platform!

### ISSUE THREAD

**Issue by DanAykroyd256** [milo526/homebridge-tuya-web#402]
Hi,

Could you please add this device type to your plugin? Its a circuit breaker and the only function that should appear in Homebridge is its ability to function exactly similar as a switch.

It's already working in [other forks](https://github.com/tuya/tuya-homebridge/issues/166). Here you have additional information, in case it's needed, of when I originally requested its support, with all the logs, responses, etc.

[Device (dlq) not showing in Accesories, but detected in log and works in Tuya IoT Platform](https://github.com/tuya/tuya-homebridge/issues/208)
[deviceType clkg is not showing in homekit](https://github.com/tuya/tuya-homebridge/issues/166#issuecomment-1018273540)

Thanks in advance.

**Comment by milo526** [comment]
Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

Without this it is hard for me to help you with regards to this specific issue.

**Comment by DanAykroyd256** [comment]
Thanks for your reply @milo526.

Your plug-in was the first I've tried when I got my Tuya breaker and, since I couldn't get it to work, I started looking for others.

Running the test doesn't return any device from my account; yet the [official Tuya Plugin](https://github.com/tuya/tuya-homebridge) detects, adds and make my device available to Hombrebridge (and functional!), just by adding the device category I mentioned before.

How could it be possible that the device doesn't get picked up by the test; yet it works with that other one? Is it because they use the Tuya IoT Platform (I have to create a project, access id, etc.) vs. your plugin that tries ot call the API to interact with the announced device directly?

Thanks again for your help!

**Comment by milo526** [comment]
The official tuya plugin uses a different API than that this plugin uses, which means that for their plugin you will need to do a lot more setup work but also gain a lot more support.
I am unable to add support for new devices to their plugin.

I'm sorry but it seems like my plugin will not be able to help you, please look for another plugin that uses the full API instead of the home assistant API (such as the "other fork" you linked previously).
