### ISSUE TITLE
XMCOSY+ RGBW String Lights 

### ISSUE THREAD

**Issue by chrispalka** [milo526/homebridge-tuya-web#404]
Hello,

I've read your README and followed instructions in regards to emailing support@tuya.com with the information received from running the python script.

They replied with the below:

1) If you want to connect your device to home assistant, please refer to the following methods:

1. Please confirm that Tuya Smart or Smart Life App is the one recommended in the device manual;
2. Currently supported product categories:
https://github.com/tuya/tuya-home-assistant/blob/main/docs/supported_devices.md
3. The category code set by the product developer during product development is correct, and the product function is a standard function of Tuya (see point 2)
4. Please refer to the specific plugin usage tutorial:
https://developer.tuya.com/cn/docs/iot/HA_HB_Bestpractice?id=Kamfbszoffjmw

2) If it is related to IoT development, it is recommended that you directly log in to the following link to ask questions:
https://service.console.tuya.com/
If you still have questions, please contact us.
Thank you for your support and understanding.

Below is also some information on the specific product I have.

Do you happen to know if these are supported within your plugin?

Many thanks!

**Brand**: ‎XMCOSY+
**‎Part Number**: YJ-SC15A

**Comment by milo526** [comment]
Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

Without this it is hard for me to help you with regards to this specific issue.

**Comment by chrispalka** [comment]
Whoops, forgot to include!

```Getting credentials
Got credentials
{   'access_token': 'AZhaz1609617706788NxjasmGDDaA3TvP',
    'expires_in': 864000,
    'refresh_token': 'AZhaz1609617706788Nxjas24P0u9ljuj',
    'token_type': 'bearer'}
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/ay1509430484182dhmed/1566280292c90040df0c2.png',
                                      'id': 'ebaaf47723a55a67d6mrhe',
                                      'name': 'Back fire light'},
                                  {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/ay1509430484182dhmed/1566280292c90040df0c2.png',
                                      'id': 'ebec7584b738965b01b7az',
                                      'name': 'Front fire light'}],
                   'scenes': []}}```

**Comment by milo526** [comment]
Sadly there are only two tuya devices exposed to the API, the 'Front fire light' and the 'Back fire light'.
I cannot help you with this, you might have to switch to one of Tuya's official plugins.
