### ISSUE TITLE
Q: What is the minimum polling interval?

### ISSUE THREAD

**Issue by Paschalis** [milo526/homebridge-tuya-web#407]
Can we update the documentation a bit regarding the `pollingInterval` option?

Digging a little bit into this, looks like it doesn't let it go below 10 minutes
(`TUYA_DISCOVERY_TIMEOUT*1e3`)

Can't we set it to something like 10 seconds?
Is Tuya platform blocking requests if those happen at a higher frequency?

Cheers,
Paschalis

**Comment by milo526** [comment]
[The standard value is set at 600 seconds](https://github.com/milo526/homebridge-tuya-web/blob/master/src/settings.ts), this is the fast that Tuya will allow.
If you where to set it faster, all request will fail since tuya will block them.
