### ISSUE TITLE
Devices on Tuya Smartlife app show up on Homebridge but none of them show up in Apple homekit after the bridge has been added.

### ISSUE THREAD

**Issue by baxijay75** [milo526/homebridge-tuya-web#408]
**Describe the bug**

After adding the homebridge tuya web plugin to homebridge, I am able to see all the devices that are added to my smartlife app on the homebridge. However these devices are not showing up on Apple HomeKit.

**Steps To Reproduce**

I don't get any error on either the homebridge or Apple HomeKit. However I have tried multiple times by uninstalling and reinstalling homebridge and homebridge tuya web plugin on my QNAP NAS, but everytime it ends with same result i.e. the devices do not show up on Apple HomeKit.

1.) I followed steps in this article https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-QNAP to install homebridge on my QNAP
2) Logged into the homebridge console in QNAP. I then installed this plugin for tuya web (https://github.com/milo526/homebridge-tuya-web#readme) and  I was able to successfully connect homebridge to tuya web platform. All the devices in smartlife app is visible in homebridge.
3) Pair the homebridge with Apple Homekit.
4) After pairing, the devices are still not visible in Apple Homekit.

**Plugin Version**
 
 1.1.1
 **Homebridge Config**
 
 
 ```json
{
    "bridge": {
        "name": "Homebridge AA90",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": 53423,
        "pin": "XXX-XX-XXX"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "TuyaWebPlatform",
            "options": {
                "username": "REDACTED",
                "password": "REDACTED",
                "countryCode": "REDACTED",
                "platform": "smart_life",
                "pollingInterval": 300
            },
            "defaults": [
                {
                    "id": "REDACTED",
                    "device_type": "dimmer",
                    "min_brightness": "0",
                    "max_brightness": "240",
                    "dimmer_characteristics": [
                        "Brightness"
                    ]
                }
            ],
            "scenes": false,
            "_bridge": {
                "username": "YY:YY:YY:YY:YY:YY",
                "port": 32963
            },
            "platform": "TuyaWebPlatform"
        }
    ]
}
```
 
 **Device Config**
 
 Getting credentials
Got credentials
{   'access_token': 'EUheu1643670131283Imj88GMG1jq2Pyl',
    'expires_in': 864000,
    'refresh_token': 'EUheu1643670131283Imj88fXyWKAL4W9',
    'token_type': 'bearer'}
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/ay1536534747810ekKBj/15650573356c530dc2175.png',
                                      'id': '20500040c82b96e120e5',
                                      'name': 'Porch Light'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/ay1536534747810ekKBj/15650573356c530dc2175.png',
                                      'id': '20500040f4cfa2276502',
                                      'name': 'Eaves Lights'},
                                  {   'data': {   'brightness': '50',
                                                  'online': True,
                                                  'state': 'false'},
                                      'dev_type': 'light',
                                      'ha_type': 'light',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/ay1536534747810ekKBj/1577061028bf995f07bad.png',
                                      'id': 'bf72f33e4d096a9417gdwb',
                                      'name': 'Office Light'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/ay1536534747810ekKBj/15650573356c530dc2175.png',
                                      'id': '20500040c82b96e0f733',
                                      'name': 'Front Lights'},
                                  {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': '4SA8HW82p1iKRh6H',
                                      'name': 'Turn\xa0on\xa0the\xa0power\xa0'
                                              "when\xa0I'm back"}],
                   'scenes': []}}
!!! NOW REMOVE THIS FILE, !!!
 

[homebridge tuya web plugin debug.txt](https://github.com/milo526/homebridge-tuya-web/files/8020160/homebridge.tuya.web.plugin.debug.txt)

 **Additional Context**

**Comment by makgit** [comment]
me too, only light bulbs recive have a correct status, other device if i turn on manualy they don't update the state and remain off

**Comment by milo526** [comment]
Are you able to see the homebridge bridge in homekit? Are you able to see other devices from other plugins?

**Comment by iRonin** [comment]
Just installed this plugn and have exactly same issue - I can see Tuya devices in HB but not in HK. Other HB devices show up in HK.

**Comment by iRonin** [comment]
Same issue here.
