### ISSUE TITLE
PIR device support?

### ISSUE THREAD

**Issue by AssetBurned** [milo526/homebridge-tuya-web#409]
It would be great if the plugin would support human movement sensors.

**Device type**
PIR sensors (Human movement sensor)

**Device information**
general device support not an individual device

**Comment by milo526** [comment]
Sadly that device type is not supported by the API that this plugin uses. This is a choice made by Tuya that I have no influence over. It is therefor not possible to add this device type to this plugin at this time or in the foreseeable future.
