### ISSUE TITLE
Fan not adding from Smart Life

### ISSUE THREAD

**Issue by clinderwell** [milo526/homebridge-tuya-web#43]
Recently installed https://www.amazon.com/gp/product/B07YS5H7SM

I connected to it via the Smart_life app which controls it fine. However, it's not pulling through via the integration in this plugin. Is there an extra step or another way to do this?

**Comment by milo526** [comment]
Please [rtfm](https://www.explainxkcd.com/wiki/index.php/293:_RTFM): [How to check whether the API this library uses can control your device](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

**Comment by clinderwell** [comment]
Thanks. Not harsh - it's something obvious I missed. I did the test and the device is not pulling through in the API - I just sent an email to Tuyo. 

Thank you for maintaining this and for the prompt response.
