### ISSUE TITLE
Fan w/ Light Dimmer

### ISSUE THREAD

**Issue by derkaramma** [milo526/homebridge-tuya-web#430]
I have a fan switch that also has a light dimmer. Am I able to add both functions to one switch in homebridge? I'm only getting the fan controls

**Comment by milo526** [comment]
Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

Without this it is hard for me to help you with regards to this specific issue.

**Comment by derkaramma** [comment]
I tried but I have no idea how to run that script im using mac and tried the replit site but its not working and keeps saying snatax error in my username and password. The fan shows up (the switch is a dual fan and light ) the lights are connected to the fan, i have another switch with just lights. I used to be able to control both aspectecs of the ceiling fan with one switch

**Comment by kolobus** [comment]
Also got a ceiling fan with dimmable light, unfortunately, no signs of light in API. Maybe there is some other place to look for it?

 'data': {   'online': True,
                 'speed': '1',
                 'speed_level': 6,
                 'state': 'true'},
'dev_type': 'fan',
'ha_type': 'fan',
'icon': 'https://images.tuyaeu.com/smart/program_category_icon/fs.png',
'id': '...',
'name': 'Cabinet Fan'
