### ISSUE TITLE
This plugin slows down Homebridge. Devices response is slow.

### ISSUE THREAD

**Issue by renovatio118** [milo526/homebridge-tuya-web#433]
**Describe the bug**

**Plugin works but it's too slow to respond after pressing the button. 
I get the following comments in homebridge platform:**

- This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
- 
- This plugin slows down Homebridge. The read handler for the characteristic 'Hue' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
- 
- This plugin slows down Homebridge. The read handler for the characteristic 'Saturation' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
- 
- This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.

**Steps To Reproduce**

**Plugin Version**
 
 
@milo526/homebridge-tuya-web v1.1.1

 **Homebridge Config**
 
 
{
    "name": "TuyaWebPlatform",
    "options": {
        "username": "XXXXXXX",
        "password": "XXXXXXX",
        "countryCode": "30",
        "platform": "smart_life"
    },
    "defaults": [
        {
            "device_type": "form"
        }
    ],
    "scenes": false,
    "platform": "TuyaWebPlatform"
}
 
 **Device Config**
 
 
 **Additional Context**
 

Running homebridge on a Raspberry Pi 3 Model B

**Comment by gdotp01** [comment]
I’ve started to see this just recently. I agree that it’s also started being slow to respond to button presses
