### ISSUE TITLE
Roller shutter stop function not working

### ISSUE THREAD

**Issue by polinszkyb** [milo526/homebridge-tuya-web#435]
Hello, 
I have 2 shutters, which are working perfectly with the Smart Life app, but not in Home as a homekit accessory. 
I have added them and I can open/close them, but I cannot stop them in between these states. Also the status either showing "Opening..." or "Closing...".
I have googled it but just cannot seem to find a solution.

Any info needed please let me know, as I am not sure what to provide :)

THanks!

**Comment by milo526** [comment]
Stop functionality is supported by this plugin, however it seems not to be supported by HomeKit, please check out another HomeKit compatible app (such as the EVE home app) which does support this functionality.

The other bug is a known problem but I am consistently unable to reproduce this behavior on my own devices and therefore am unable to fix them sadly, PRs are very welcome!
