### ISSUE TITLE
Split Device Into Multiple Accessories

### ISSUE THREAD

**Issue by rowie1** [milo526/homebridge-tuya-web#44]
**Is your feature request related to a problem? Please describe.**
I just added a combination fan and light controller wifi smart switch to the Smart Life App and then installed this plugin to see it in homebridge, however it only sees it as a fan controller. The light switch function is not available as an accessory.

**Describe the solution you'd like**
I would like to be able to see and control both accessories in homebridge/homekit.

``` json
{
   "header":{
      "code":"SUCCESS",
      "payloadVersion":1
   },
   "payload":{
      "devices":[
         {
            "data":{
               "online":true,
               "speed":"2",
               "speed_level":3,
               "state":"true"
            },
            "dev_type":"fan",
            "ha_type":"fan",
            "icon":"https://images.tuyaeu.com/smart/program_category_icon/fs.png",
            "id":"87278822cc50e3ed1872",
            "name":"Fan Light-1872"
         }
      ],
      "scenes":[

      ]
   }
}
```

**Comment by milo526** [comment]
The device is only exposed via this API as a fan, it is therefor not feasible for me to support this. You might have better luck with `homebridge-tuya-lan` that plugin uses a different API, harder to setup initially but it does support more devices.

**Comment by rowie1** [comment]
Ok thanks for the suggestion, I’ll give it a go
