### ISSUE TITLE
Support for AC Cortina Silent 12K Smart Home 

### ISSUE THREAD

**Issue by mstendah** [milo526/homebridge-tuya-web#443]
Hi, is there a way to get an Air Conditioning unit (AC Cortina Silent 12K Smart Home) to show up in a way that it shows Cooling rather than Heating when set to cool?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by milo526** [comment]
Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

Without this it is hard for me to help you with regards to this specific issue.

**Comment by mstendah** [comment]
> Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)
> 
> 
> 
> Without this it is hard for me to help you with regards to this specific issue.

Sorry for not replying. I returned the unit as it was too loud for us so unable to contribute to this issue anymore.
