### ISSUE TITLE
Can't detect my outlet

### ISSUE THREAD

**Issue by Hugo1112** [milo526/homebridge-tuya-web#444]
[TuyaWebPlatform] Tried overwriting device config for: "50361166cc50e3d4d83a" which is not a valid device-id or device-name.

Getting credentials
Got credentials
{   'access_token': 'AZhaz1650453515723cxmx14BV2gctm5Q',
    'expires_in': 864000,
    'refresh_token': 'AZhaz1650453515723cxmx1sFolCPppNk',
    'token_type': 'bearer'}
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {'devices': [], 'scenes': []}}
!!! NOW REMOVE THIS FILE, SO YOUR CREDENTIALS (username, password) WON'T LEAK !!!


**Comment by milo526** [comment]
Sadly we can see that your devices list is empty.   
Therefor this plugin does not support your device.  
This is a limit imposed by Tuya that I cannot help you with.  
Please try one of the different Tuya plugins and see if that will help you.
