### ISSUE TITLE
Only 1 device showing up when adding to HomeKit (also in cache in Hoobs)

### ISSUE THREAD

**Issue by recoi1er** [milo526/homebridge-tuya-web#454]
**Describe the bug**

Adding your plugin to HomeKit, I want to expose a fan and ceiling light that I have in the Smart Life app

**Steps To Reproduce**

1. Install your plugin to Hoobs
2. Add bridge to HomeKit 
3. Go through walk through in Home app 
4. Only adds ceiling light, no fan to be found
5. Same thing in Hoobs, under cached accessories it only see's the ceiling light. Doesn't matter if I change polling to 600 or leave blank (how do you manually poll? I see no options)

Plugin Version**
 1.1.2
 
 **Homebridge Config**
 
 
 ```json

```
 
 **Device Config**
 

{
    "platform": "TuyaWebPlatform",
    "name": "TuyaWebPlatform",
    "options": {
        "username": "redacted",
        "password": "redacted",
        "countryCode": "1",
        "platform": "smart_life",
        "pollingInterval": 600
    }
}
 
 **Additional Context**

**Comment by recoi1er** [comment]
Did you give up on this project @milo526 ?

**Comment by milo526** [comment]
Nope just crazy busy with higher priority stuff, but as always, MRs are welcomed!

**Comment by recoi1er** [comment]
MR?

**Comment by edgaragr** [comment]
Merge Request = MR

**Comment by recoi1er** [comment]
Merge with what exactly in this regard?

**Comment by edgaragr** [comment]
What @milo526 say is we can try fix it and send him a Pull Request  (Merge Request) to include it in the next library version. 

@milo526 I could try that, do you know if the issue is a limitation from tuya API?

**Comment by recoi1er** [comment]
I also have a ticket open with Tuya IOT support at the moment, let’s see if it’s something on their end first - someone else at Tuya told me it might be the device type itself might need to be added to their API since it’s a different brand - both devices are from Atomi Smart. Both were added to Tuya IOT and show online just the light shows up in the plugin though

**Comment by edgaragr** [comment]
I'm case only the ceiling is exposed. I can change speed, turn on/off but can't even see the light switch.

**Comment by recoi1er** [comment]
Ah ok, Tuya also got back to me and said they don’t support ceiling fans yet  “fsd”
