### ISSUE TITLE
Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined  at LightAccessory.updateState 

### ISSUE THREAD

**Issue by marksthomas** [milo526/homebridge-tuya-web#46]
I'm using several LED strips in scenes. I get logs full of the below when the light is used in a scene, but NOT when used on its own.

[8/5/2020, 10:03:22] [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
    at LightAccessory.updateState (C:\Users\marks\AppData\Roaming\npm\node_modules\homebridge-tuya-web\lib\light_accessory.js:227:39)
    at LightAccessory.updateAccessory (C:\Users\marks\AppData\Roaming\npm\node_modules\homebridge-tuya-web\lib\base_accessory.js:103:14)
    at C:\Users\marks\AppData\Roaming\npm\node_modules\homebridge-tuya-web\index.js:96:52
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

The scene triggers correctly, the only issue seems to be this junk filling the logs.

Any ideas?

Timezone | GMT+0100
-- | --
Microsoft Windows 10 Pro
Plex
192.168.86.63
fe80::cd70:ad18:b7bc:cc89
v12.18.0
SYSTEM
C:\Users\marks\.homebridge
C:\Users\marks\.homebridge\config.json
Yes

HB version 1.1.1

**Comment by serenacloos** [comment]
I have the exact same problem.

**Comment by milo526** [comment]
Hello, could the both of you please try installing the beta tag and see if that solves your issues?

**Comment by marksthomas** [comment]
> Hello, could the both of you please try installing the beta tag and see if that solves your issues?

Sure, can you confirm the command line to use please?

**Comment by milo526** [comment]
```npm i @milo526/homebridge-tuya-web@beta``` depending on your installation method you might have to add a `-g` flag there.

However you installed the ```@milo526/homebridge-tuya-web``` package originally, add ```@beta``` to the end of it.

This can't be done through the UI and has to be done via the/a command line.

**Comment by serenacloos** [comment]
It works now, but I still keep getting this message.

`Requesting too quickly`

**Comment by serenacloos** [comment]
As soon as I open Home or Home+ I get this:

`RatelimitError: Requesting too quickly.
    at TuyaWebApi.discoverDevices (/usr/local/lib/node_modules/@milo526/homebridge-tuya-web/src/TuyaWebApi.ts:159:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
`

**Comment by milo526** [comment]
That is a known problem; Please try not opening your home apps for a hour or 2, after that, with normal usage, you should receive this error less often.

Working on a fix for this but since Tuya is giving very little information here it is hard.

**Comment by serenacloos** [comment]
Ik hoop het, dit is niet normaal. 



Groetjes Serena
