### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by plainjosh99** [milo526/homebridge-tuya-web#460]
Maybe I'm lost here.
In the Configurations, you list this:

> username Required. The username for the account that is registered in the Android/iOS App. *Due to a bug in the API the username can't contain dots.

Exactly how does one create an account without an email (which has a dot)?

**Comment by milo526** [comment]
Hmm that could have been slightly clearer.
The dot cannot not be before the '@' in the email.

**Comment by plainjosh99** [comment]
Gotcha, thanks. I got it to work. At first, it would not work with my Smart Life account. After linking it with Tuya IoT, all devices would immediately go offline.
So I created a Tuya Smart account and linked it; this worked. (I unlinked the Smart Life account first). Hope this helps someone.
