### ISSUE TITLE
Lamp Characteristics

### ISSUE THREAD

**Issue by ariknil** [milo526/homebridge-tuya-web#461]
**Describe the bug**

The Homebridge Log shows Two warnings about Brightness and Color characteristics of a bulb lamp. Also the color and brightness arent very acurate.

**Steps To Reproduce**

Logs de Homebridge
[22/07/2022,
17:39:03] [TuyaWebPlatform] [Lámpara] Characteristic.Brightness
- Characteristic
'Brightness
will receive value higher than allowed (1100) since provided Tuya value (1000) ex
ceeds configured maximum Tuya value (100). Please update your configuration!
[22/07/2022, 17:39:05] [@milo526/homebridge-tuya-web] This plugin generated a warning from the
characteristic
'Brightness
": characteristic was supplied illegal
value: number 1100 exceeded
maximum of 100.
Se https://homebridge.io/w/JtMGR for more info.
[22/07/2022, 17:39:05] [TuyaWebPlatform] [Lámpara] Characteristic.ColorTemperature
- Character
istic
"'ColorTemperature
will receive value higher than allowed mired (570) since provided Tuy
a kelvin value (1000) is lower then configured minimum Tuya kelvin value (7142.857142857143)
Please update your configuration!

**Plugin Version**
 
 
V 1.1.2

 **Homebridge Config**
 
 

{
"name": "TuyaWebPlatform",            "options": {                "username": "",                "password": "",                "countryCode": "52",                "platform": "tuya",                "pollingInterval": 1800            },            "defaults": [                {                    "id": "026361472cf432b69358",                    "device_type": "switch"                },                {                    "id": "51100381483fda14ef05",                    "device_type": "light"                }            ],            "scenes": false,            "platform": "TuyaWebPlatform"        },

 
 **Device Config**
 
 
 **Additional Context**

**Comment by milo526** [comment]
Please read the following wiki article to find out how to configure your devices to solve this problem.

https://github.com/milo526/homebridge-tuya-web/wiki/Something-will-receive-higher-or-lower-value-than-allowed
