### ISSUE TITLE
Inventor Dark AC (Tuya compatible, Greek brand) small feature set

### ISSUE THREAD

**Issue by flareman** [milo526/homebridge-tuya-web#462]
Thanks for you hard work:)

I'm using an Inventor AC split unit at home, which uses the Tuya framework. Their own app (Inventor Control) handles in large like Tuya's own with some added or removed bells and whistles. I had to compromise and set up the device through the Tuya app (I would like to keep the original one, but I can't link it with Tuya IoT so I can't get the key needed to use a LAN control plugin), and it does work, but there are a couple of features missing, most importantly the fan speed (which is exposed as a native HomeKit control and is available in the instruction and status set for this particular device). Moreover, the °C/°F control in HomeKit does nothing for the device, while the corresponding control in the Tuya app and the online debugging interface works normally.

Could you please update the plugin to allow for fan speed control, and maybe fix the Celsius/Farenheit issue? If it would help, I could fork the project and try to work something out and issue a pull request, but in my experience, the original developer usually keeps things tidier :)

Thank you again,
Spyros

**Comment by milo526** [comment]
Hey! Feel free to try and work something out yourself.

You might first want to try and see if the API is exposing the desired values (the API that this plugin is using is different from the Tuya cloud API)
Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device) to see if these values are available in this API.

**Comment by flareman** [comment]
Thanks for the speedy reply.

I didn't know the tyuaha API is different from Tuya's own IoT cloud API; indeed, there are no speed controls available using the Python script. Oh well, it was worth a try.

Keep up the good work! :)
