### ISSUE TITLE
Dimmer Brightness Value Error

### ISSUE THREAD

**Issue by Marcus235** [milo526/homebridge-tuya-web#466]
**Describe the bug**
 I have connected two EcoDim Zigbee dimmers through a Zigbee router to Smart Life. Everything works fine, dimmers are exposed to Homekit and respond. However the Hoobs lof shows error messages for both dimmers. I have tried changing the configuration file by adding the dimmer, expose as dimmer and max value 100. The error messages disappears but now the dimmer is exposed to Homekit as a switch instead of dimmer. I've tried to leave expose field blank or expose as switch but then the error messages reappear. 

**Steps To Reproduce**

**Plugin Version**
 1.1.2
 
 **Homebridge Config**
 
 
 ```json

{
    "accessories": [],
    "platforms": [
        {
            "platform": "TuyaWebPlatform",
            "name": "TuyaWebPlatform",
            "options": {
                "username": "l",
                "password": "!",
                "countryCode": "31",
                "platform": "smart_life"
            },
"defaults": [
                {
                    "id": "VW Bijkeuken",
                    "device_type": "climate",
                    "min_temper": "5.0",
                    "max_temper": "35.0",
                    "current_temperature_factor": "0.1",
                    "target_temperature_factor": "0.1"
                },
{
                    "id": "VW Badkamer",
                    "device_type": "climate",
                    "min_temper": "5.0",
                    "max_temper": "35.0",
                    "current_temperature_factor": "0.1",
                    "target_temperature_factor": "0.1"
                },
{
                    "id": "VW Douche",
                    "device_type": "climate",
                    "min_temper": "5.0",
                    "max_temper": "35.0",
                    "current_temperature_factor": "0.1",
                    "target_temperature_factor": "0.1"
                },
{
                    "id": "Dimmer",
                   "device_type": "dimmer",
                    "max_brightness": "100"
                },
                {
                    "id": "Dimmer Koen",
                    "device_type": "dimmer",
                    "max_brightness": "100"
                }
],
            "scenes": true,
            "scenesWhitelist": [
                "Eco Badkamer",
                "Program Badkamer",
                "Eco Douche",
                "Program Douche",
                "BuitenLamp",
                "Douche 18°",
                "Deken 30m OFF"
            ],
"hiddenAccessories": [
                "BuitenLamp"
            ]
        }
    ]
}
```
 
 **Device Config**
 
 
 **Additional Context**
 

![Foto 16-08-2022 om 21 13](https://user-images.githubusercontent.com/61418593/184973962-852007c8-9a8a-4880-bb96-b0285246af72.jpg)

**Comment by mpreissner** [comment]
I'm having a similar issue, but with Feit Electric dimmer switches.  Added them fine to the SmartLife app, was able to add them to Homebridge as a simple on/off switch without issue; but when enabling the dimmer option in the device settings, (using min 0, max 100) I get the following error, and dimming via Homekit doesn't work:

```
[30/08/2022, 08:24:25] [TuyaWebPlatform] [Deck lights] Characteristic.Brightness - Tried to set brightness but failed to parse data. 
 { online: true, state: false }
```

No issues dimming from the SmartLife app.

This is on Homebridge v1.5.0 with the latest Tuya Web Platform plugin.

**Comment by milo526** [comment]
@Marcus235 
1. Set your dimmer to 100% brightness via the tuya app (or smart life, or a physical device, just not using homebridge/hoobs)

2. Note the "provided tuya value" in the error logs. For @Marcus235 this will probably be 1000 for Dimmer Koen and 255 for Dimmer.
3. Input the number you wrote down in step 2 as the max_brightness.

@mpreissner 

This is a different issue, your device does not expose the required information (see the complete lack of any brightness information in the data that is logged). Your device cannot and will not be able to as a dimmer using the API that this plugin uses. Please try tuya's official plugin instead of this one.

**Comment by mpreissner** [comment]
@milo526 man that's disappointing.  These are such great little dimmers - and really cheap at Costco!

**Comment by Marcus235** [comment]
Hi,Thanks for your answer but that doesn’t solve the problem when you expose the device as dimmer which is what you have to do to fill out the max value, HomeKit sees the the device no longer as dimmer but a normal on/off switch..Kind regards,Met vriendelijke groet, Marcus BitterlingOp 30 aug. 2022 om 14:46 heeft Milo Cesar ***@***.***> het volgende geschreven:﻿
@Marcus235


Set your dimmer to 100% brightness via the tuya app (or smart life, or a physical device, just not using homebridge/hoobs)


Note the "provided tuya value" in the error logs. For @Marcus235 this will probably be 1000 for Dimmer Koen and 255 for Dimmer.


Input the number you wrote down in step 2 as the max_brightness.


@mpreissner
This is a different issue, your device does not expose the required information (see the complete lack of any brightness information in the data that is logged). Your device cannot and will not be able to as a dimmer using the API that this plugin uses. Please try tuya's official plugin instead of this one.

**Comment by Marcus235** [comment]
Hi Milo

Once again. I have tried your solution and it does solve the error log but it exposes the dimmers as a switch to homekit instead of an dimmable device. I hope you have a solution for this as well. 
kind regards, Marcus

**Comment by milo526** [comment]
@Marcus235 can you show me the config file that setting the `max_brightness` generated for you (be sure to remove any sensitive information)

**Comment by Marcus235** [comment]
Hi Milo, 

See hereunder. 
This is the config value generated when I change it for Dimmer Gijs and Dimmer Koen.
As said before, the warning in the log ceases but now the dimmer is exposed as a switch instead of a dimmer in Homekit. 

Thanks, Marcus


ConfigFile



{
    "platform": "TuyaWebPlatform",
    "name": "TuyaWebPlatform",
    "options": {
        "username": “xxx”,
        "password": “xxx”,
        "countryCode": "31",
        "platform": "smart_life"
    },
    "defaults": [
        {
            "id": "VW Bijkeuken",
            "device_type": "climate",
            "min_temper": "5.0",
            "max_temper": "35.0",
            "current_temperature_factor": "0.1",
            "target_temperature_factor": "0.1"
        },
        {
            "id": "VW Badkamer",
            "max_temper": "35.0",
            "current_temperature_factor": "0.1",
            "target_temperature_factor": "0.1"
        },
        {
            "id": "Dimmer Gijs",
            "device_type": "dimmer",
            "max_brightness": "1096"
        },
        {
            "id": "Dimmer Koen",
            "device_type": "dimmer",
            "max_brightness": "399"
        }

    ],
    "scenes": true,
    "scenesWhitelist": [
        "Eco Badkamer",
        "Program Badkamer",
        "Eco Douche",
        "Program Douche",
        "BuitenLamp",
        "Douche 18°",
        "Deken 30m OFF"
    ],
"hiddenAccessories": [
        "BuitenLamp"
    ]
}

**Comment by Marcus235** [comment]
Issue still not resolved!
