### ISSUE TITLE
Type Overruling 

### ISSUE THREAD

**Issue by mbierman** [milo526/homebridge-tuya-web#47]
**Describe the bug**
I'm trying to use the new Overruling feature and I'm not having luck. 

**To Reproduce**
1. Go to Config
2. Add 
```
{
            "platform": "TuyaWebPlatform",
            "name": "Smart Life",
            "scenes": false,
            "options": {
                "username": "",
                "password": "",
                "countryCode": "1",
                "platform": "smart_life",
                "pollingInterval": 120
            },
            "defaults": [
                {
                    "id": "77374801840d8e96073b",
                    "device_type": "light"
                }
            ]
        },
```
Note the "id" provided comes from what the Smart Life app calls the Virtual ID. I also tried the text of the name of the device in the Smart Life app. Neither seems to work. 

**Expected behavior**
Device should appear as a light not an outlet.

**Screenshots**

**Device**
 - Plugin: 
 - Version: v0.4.2 
 - Model : [See model in your homekit device]
 - Device-config: [Follow the steps as described [here](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device) and post the output]

**Additional context**

**Comment by milo526** [comment]
You might want to change that password 🙈

Will look at the issue soon, thanks for reporting

**Comment by mbierman** [comment]
I think I found the right ids from the homebridge logs. Maybe the smart life app was giving some different ids. I guess we can close. :)

**Comment by milo526** [comment]
Could you help me a tad more here so I can improve the documentation on this?

In my own logs I see

    Existing Accessory found [Name: Kerstboom] [Tuya ID: 08207108600194cd944f] [HomeBridge ID: 3d1786e3-3db2-429c-aebd-1691881476b9]

The Tuya ID here matches the virtual ID I see in the Tuya App, is this also the case for you?
If I enter this ID into the defaults section everything works as expected for me.

Could it be that the Smart Life app is using different IDs for the same products?
