### ISSUE TITLE
Temperature detector

### ISSUE THREAD

**Issue by jsvasta** [milo526/homebridge-tuya-web#471]
Hi I bought new device Thermometer / temperature detector

I added device into smart life app (tuya app) but is not possible to use it in the home bridge and in the HomeKit

thanks for your help
Jiri

**Device type**

**Device information**

```json

```

**Comment by jsvasta** [comment]
![image](https://user-images.githubusercontent.com/113471807/190233858-21b649bb-57d1-4bf2-8990-080dcc206167.jpg)

wifi temperature&humidity Alarm

**Comment by milo526** [comment]
Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

Without this it is hard for me to help you with regards to this specific issue.

**Comment by jsvasta** [comment]
the result is without this device :-(

Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/ay1531739836474naEnL/15971272246d598076d13.png',
                                      'id': '03016338dc4f22eafd98',
                                      'name': 'Raspberry'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/ay1531739836474naEnL/15971272246d598076d13.png',
                                      'id': '03016338dc4f22f1126b',
                                      'name': 'Router patro'},
                                  {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1547622003btfen97bbnp_0.jpg',
                                      'id': '07033406483fda55a9bc',
                                      'name': 'Mereni spotreby'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/ay1531122507771gALCb/1652666052356fa71002b.png',
                                      'id': 'bf6346f971f88eee32fssf',
                                      'name': 'Smart Swith'},
                                  {   'data': {'online': False, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/ay1531739836474naEnL/158825108502d9ff5345d.png',
                                      'id': '27035466c44f33cbfc5b',
                                      'name': '3D printer'}],
                   'scenes': []}}

**Comment by jsvasta** [comment]
![IMG_0059](https://user-images.githubusercontent.com/113471807/190471437-7db31378-c378-41e4-b028-de512f90bbfb.jpeg)

**Comment by milo526** [comment]
Sadly, this plugin cannot help you if the device is not exposed.
