### ISSUE TITLE
The new update isn't working on Hoobs after updating

### ISSUE THREAD

**Issue by SpcFilho** [milo526/homebridge-tuya-web#49]
I'm new here. I used the 0.3.3 for a long time, it worked flawlessly. But i was excited for this new release since i saw the awesome release notes from the pre-releases. I updated it today right after the release and all my accessories dissappeared. I tryed to unninstall the plugin completelly and try to install it again from the "Hoobs Plugin Search". Didn't work.

So I went to my log and saw this never-saw-before-message:

`"TuyaWebPlatform" which has not been published by any installed plugins.`

I went back to the 0.3.3 version (by restoring my saved hoobs backup made before updating the plugin) to make all work again.

Hope you can help me.

**Comment by mbierman** [comment]
I saw that too. 

I uninstalled the configured and the plugin and all the cached devices and that sort of worked. See my bug.

**Comment by SpcFilho** [comment]
Tried to update from the 0.3.3 to 0.4.2 version again and the log showed:

`11/08/2020 21:26:17 The requested platform "TuyaWebPlatform" was not registered by any plugin.`

`11/08/2020 21:26:17 Your config.json is requesting the platform "TuyaWebPlatform" which has not been published by any installed plugins.`

`11/08/2020 21:26:17 Failed to find plugin to handle accessory Light`

`11/08/2020 21:26:17 Removing orphaned accessory Light`

**Comment by tetanus** [comment]
I’m having the same issue.

**Comment by motogon** [comment]
After update stopped working.

log :

12.08.2020, 10:35:07 The requested platform "TuyaWebPlatform" was not registered by any plugin.
12.08.2020, 10:35:07 Your config.json is requesting the platform "TuyaWebPlatform" which has not been published by any installed plugins.

**Comment by milo526** [comment]
Thank you all for reporting, sorry for the inconvenience. I am currently investigating; Could you please post the relevant part of your `config.json` here (remove your password! and if desired your username!? My own instances don't seem to have this problem 🙈 

Could you furthermore please enable debugging and paste your full logs here? This will help me tremendously (and speed up the time it will take you to get a new plugin 😉)

**Comment by motogon** [comment]
my config

{
            "platform": "TuyaWebPlatform",
            "plugin_map": {
                "plugin_name": "homebridge-tuya-web"
            },
            "name": "TuyaWebPlatform",
            "options": {
                "platform": "tuya",
                "pollingInterval": 10,
                "username": "xxxxxx",
                "password": "xxxxxx",
                "countryCode": "+7"
            },
            "scenes": false,
            "defaults": [],
            "scenesWhitelist": []
        },

ps 

how to enable debug mode?

**Comment by milo526** [comment]
Could it maybe be that some of you still have the old version of this package installed? That one could be conflicting.

Please run ```npm uninstall -g homebridge-tuya-web```

**Comment by motogon** [comment]
did :

npm uninstall -g homebridge-tuya-web

later :

npm install -g homebridge-tuya-web

problem remained, log below:

12.08.2020, 10:56:43 The requested platform "TuyaWebPlatform" was not registered by any plugin.
12.08.2020, 10:56:43 Your config.json is requesting the platform "TuyaWebPlatform" which has not been published by any installed plugins.

**Comment by milo526** [comment]
Yeah so you should not install `homebridge-tuya-web` afterwards.

```
npm uninstall -g homebridge-tuya-web
npm install -g @milo525/homebridge-tuya-web
```

If you are indeed installing` homebridge-tuya-web` instead of the `@milo526` scoped version, you also should not be able to be using v0.4.2, that version has not been pushed to the un-scoped package.

**Comment by motogon** [comment]
/hoobs/etc # npm install -g @milo525/homebridge-tuya-web
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@milo525%2fhomebridge-tuya-web - Not found
npm ERR! 404 
npm ERR! 404  '@milo525/homebridge-tuya-web@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by milo526** [comment]
Look at my username and see if you can spot where I made the mistake 😛 

```npm install -g @milo526/homebridge-tuya-web```

**Comment by bwp91** [comment]
I might be wrong but I do believe with HOOBS you don't use the -g flag, so try
`npm uninstall homebridge-tuya-web`
`npm install @milo526/homebridge-tuya-web`

**Comment by motogon** [comment]
installed via web HOOBS

screenshot https://yadi.sk/i/veZRg72wRVgqRQ

12.08.2020, 11:14:28 The requested platform "TuyaWebPlatform" was not registered by any plugin.
12.08.2020, 11:14:28 Your config.json is requesting the platform "TuyaWebPlatform" which has not been published by any installed plugins.

**Comment by milo526** [comment]
@mbierman Are you by any chance also using hoobs? What about @SpcFilho?

**Comment by milo526** [comment]
@motogon you will probably need to change 

```
"plugin_map": {
    "plugin_name": "homebridge-tuya-web"
  },
```

to

```
"plugin_map": {
    "plugin_name": "@milo526/homebridge-tuya-web"
  },
```

Source: https://github.com/hoobs-org/HOOBS/wiki/4.0-Plugins#installing-plugins-manually

**Comment by motogon** [comment]
{
            "platform": "TuyaWebPlatform",
            "plugin_map": {
                "plugin_name": "@milo526/homebridge-tuya-web"
            },
            "name": "TuyaWebPlatform",
            "scenes": false,
            "options": {
                "platform": "tuya",
                "username": "xxxxx",
                "password": "xxxxx",
                "countryCode": "+7",
                "pollingInterval": 5
            },
            "defaults": [],
            "scenesWhitelist": []
        }

log 

12.08.2020, 11:35:35 The requested platform "TuyaWebPlatform" was not registered by any plugin.
12.08.2020, 11:35:35 Your config.json is requesting the platform "TuyaWebPlatform" which has not been published by any installed plugins.

**Comment by mbierman** [comment]
@milo526 I’m not using HOOBS, but I am using docker and plugins are not to be installed globally.

**Comment by milo526** [comment]
@motogon I don't know hoobs as you might have noticed, can you use some sort of UI to install the plugin and see if that helps? Otherwise you might have to ask the Hoobs team since it seems like it might be an issue with their plugin discovery.

**Comment by motogon** [comment]
@milo526 I used to install the user interface to install the plugin - the result is in the screenshot above.
the plugin installation went without errors.
But the plugin does not work, there are errors in the logs

**Comment by milo526** [comment]
So for me, when I start homebridge I see

> [8/12/2020, 2:01:31 PM] Loaded config.json with 0 accessories and 3 platforms.
>[8/12/2020, 2:01:31 PM] ---
>[8/12/2020, 2:01:31 PM] Loaded plugin: homebridge-dummy@0.4.1
>[8/12/2020, 2:01:31 PM] Registering accessory 'homebridge-dummy.DummySwitch'
>[8/12/2020, 2:01:31 PM] ---
>[8/12/2020, 2:01:32 PM] Loaded plugin: homebridge-hue@0.11.73
>[8/12/2020, 2:01:32 PM] Registering platform 'homebridge-hue.Hue'
>[8/12/2020, 2:01:32 PM] ---
>**[8/12/2020, 2:01:32 PM] Loaded plugin: homebridge-tuya-web@0.4.3**
>**[8/12/2020, 2:01:32 PM] Registering platform '@milo526/homebridge-tuya-web.TuyaWebPlatform'**
>[8/12/2020, 2:01:32 PM] ---
>[8/12/2020, 2:01:32 PM] Loaded plugin: homebridge-config-ui-x@4.25.1
>[8/12/2020, 2:01:32 PM] Registering platform 'homebridge-config-ui-x.config'
>[8/12/2020, 2:01:32 PM] ---
>[8/12/2020, 2:01:32 PM] Loading 3 platforms...

Do you also see that output? Or what other plugins do you see there?

**Comment by motogon** [comment]
12.08.2020, 15:32:43 Got SIGINT, shutting down Bridge...
12.08.2020, 15:32:48 Loaded plugin "homebridge-ewelink-sonoff".
12.08.2020, 15:32:49 Loaded plugin "homebridge-mqtt".
12.08.2020, 15:32:49 homebridge API version: 2.5
12.08.2020, 15:32:49 Loaded plugin "homebridge-plex-v2".
12.08.2020, 15:32:49 Loaded plugin "homebridge-unifi-occupancy-sensor".
12.08.2020, 15:32:50 Loaded plugin "homebridge-xiaomi-roborock-vacuum".
12.08.2020, 15:32:50 Loaded plugin "homebridge-tuya-web".
12.08.2020, 15:32:50 [mqtt] homebridge-mqtt v0.6.2
12.08.2020, 15:32:50 The requested platform "TuyaWebPlatform" was not registered by any plugin.
12.08.2020, 15:32:50 Your config.json is requesting the platform "TuyaWebPlatform" which has not been published by any installed plugins.
12.08.2020, 15:32:50 HAP Warning: Characteristic 000000AC-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
12.08.2020, 15:32:50 HAP Warning: Characteristic 000000AB-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
12.08.2020, 15:32:51 [eWeLink] Plugin has finished initialising. Starting synchronisation with eWeLink account.
12.08.2020, 15:32:51 [mqtt] Number of cached Accessories: 3

**Comment by SpcFilho** [comment]
> @mbierman Are you by any chance also using hoobs? What about @SpcFilho?
> 
> Edit:
> Obviously @SpcFilho is using hoobs 🙈

Hahaha, yes, I'm using Hoobs 😆 

I updated again from 0.3.3 to the 0.4.3 (newer version). But i still can't make it work.

So I removed all my plugins and tried to install the newer version following the hoobs-native-instalation-steps (went to hoobs plugins page, searched for "tuya" and found milo526 version to install)

I recorded my "instalation-journey" on video, hope it can help you:

https://streamable.com/m895pj

**Comment by tetanus** [comment]
{
            "platform": "TuyaWebPlatform",
            "name": "TuyaWebPlatform",
            "options": {
                "username": "xxxxxxxxx",
                "password": "xxxxxxxxx",
                "countryCode": "65",
                "platform": "smart_life",
                "pollingInterval": 10
            },
            "plugin_map": {
                "plugin_name": "homebridge-tuya-web"
            },
            "scenes": true,
            "defaults": [],
            "scenesWhitelist": []
        },

**Comment by motogon** [comment]
@milo526 how can I help you localize the problem?

**Comment by milo526** [comment]
@motogon thank you for asking, I hope to get some insights on this from the hoobs maintainers.

If you want to help me, you would do so by filing an issue at their repository.

I believe the best course of action is to fill out [this issue template](https://github.com/hoobs-org/HOOBS/issues/new?assignees=&labels=discovery%2C+plugins&template=plugin-issue.md&title=Homebridge%20Tuya%20Web%20not%20working)

**Comment by motogon** [comment]
@milo526 done

**Comment by motogon** [comment]
14.08.2020, 20:38:29 + @milo526/homebridge-tuya-web@0.4.4
updated 1 package in 7.177s
14.08.2020, 20:38:29 
34 packages are looking for funding
  run `npm fund` for details
14.08.2020, 20:38:29 Plugin "@milo526/homebridge-tuya-web" updated.
14.08.2020, 20:38:29 Got SIGINT, shutting down Bridge...
14.08.2020, 20:38:33 Loaded plugin "homebridge-ewelink-sonoff".
14.08.2020, 20:38:34 Loaded plugin "homebridge-mqtt".
14.08.2020, 20:38:34 homebridge API version: 2.5
14.08.2020, 20:38:34 Loaded plugin "homebridge-plex-v2".
14.08.2020, 20:38:35 Loaded plugin "homebridge-unifi-occupancy-sensor".
14.08.2020, 20:38:36 Loaded plugin "homebridge-xiaomi-roborock-vacuum".
14.08.2020, 20:38:36 [mqtt] homebridge-mqtt v0.6.2
14.08.2020, 20:38:36 The requested platform "TuyaWebPlatform" was not registered by any plugin.
14.08.2020, 20:38:36 Your config.json is requesting the platform "TuyaWebPlatform" which has not been published by any installed plugins.

**Comment by costispavlou** [comment]
also having the same issues. Nothing shows up in home.app and same error as above, 
TuyaWebPlatform was not registered by any plugin. 
the sad thing is that just a couple of weeks ago, the (now rip) plugin worked with my shutters (set as cover) in the config.json 
also I've changed the "plugin_name": "@milo526/homebridge-tuya-web". same result.

**Comment by johnhmccauley** [comment]
Other plugins have had the same issue with HOOBS. Suggest taking a look at the changes HomeSeer made.
https://www.reddit.com/user/dragon_myass

See post.

**Comment by Kokorone** [comment]
Chiming in to say I have the same problem with my hoobs and this plugin

**Comment by milo526** [comment]
Oops auto closed this already due to the merge, can somebody please confirm that v0.4.6 is working for them under hoobs?

**Comment by Kokorone** [comment]
> Oops auto closed this already due to the merge, can somebody please confirm that v0.4.6 is working for them under hoobs?

hoobs hasnt refreshed yet, so its not showing an update. I'll test once its available

**Comment by Kokorone** [comment]
Confirmed working after 0.4.6 with hoobs.

Thanks for your work on the plugin

**Comment by milo526** [comment]
Thanks for the confirmation, please direct your praise for this change to @bwp91, he figured out what the issue was and solved it!

**Comment by bwp91** [comment]
> Other plugins have had the same issue with HOOBS. Suggest taking a look at the changes HomeSeer made.
> https://www.reddit.com/user/dragon_myass
> 
> See post.

The credit is due here to @johnhmccauley for his post!

**Comment by motogon** [comment]
Version 0.4.6 does not work for me. The error is the same.

18.08.2020, 09:40:44 + @milo526/homebridge-tuya-web@0.4.6
updated 1 package in 8.849s
18.08.2020, 09:40:44 
34 packages are looking for funding  run `npm fund` for details
18.08.2020, 09:40:44 Plugin "@milo526/homebridge-tuya-web" updated.
18.08.2020, 09:40:44 Got SIGINT, shutting down Bridge...
18.08.2020, 09:40:49 Loaded plugin "homebridge-ewelink-sonoff".
18.08.2020, 09:40:50 Loaded plugin "homebridge-mqtt".
18.08.2020, 09:40:50 homebridge API version: 2.5
18.08.2020, 09:40:51 Loaded plugin "homebridge-plex-v2".
18.08.2020, 09:40:51 Loaded plugin "homebridge-unifi-occupancy-sensor".
18.08.2020, 09:40:52 Loaded plugin "homebridge-xiaomi-roborock-vacuum".
18.08.2020, 09:40:52 [mqtt] homebridge-mqtt v0.6.2
18.08.2020, 09:40:52 The requested platform "TuyaWebPlatform" was not registered by any plugin.
18.08.2020, 09:40:52 Your config.json is requesting the platform "TuyaWebPlatform" which has not been published by any installed plugins.

**Comment by milo526** [comment]
@motogon im sorry to hear that. Since it works for others I'd like to exclude the possibility that something is wrong with your config. Could you maybe fully remove/uninstall the plugin (also remove it from the config). Restart your Hoobs instance. And then install the plugin again.

Please let me know if that helped for you; if it did not, please let me know what your new config looks like. I'm especially interested in how the Hoobs specific plugin map is populated.￼

**Comment by motogon** [comment]
After reinstall - everything worked.
Thanks for your plagin

**Comment by motogon** [comment]
Plugin is working.

But some of the accessories in the Home application are in the status of no response

18.08.2020, 10:20:53 [TuyaWebPlatform] [Полив клапан 1] Characteristic.On - [GET] true
18.08.2020, 10:20:53 [TuyaWebPlatform] [Клапан 4] Characteristic.On - [GET] true
18.08.2020, 10:20:53 [TuyaWebPlatform] [Гостевая спальня] Characteristic.On - [GET] false
18.08.2020, 10:20:53 [TuyaWebPlatform] [Гостевая спальня] Characteristic.Brightness - [GET] 32
18.08.2020, 10:20:53 [TuyaWebPlatform] [Smart Plug2] Characteristic.On - [GET] false18.08.2020, 10:20:53 [TuyaWebPlatform] [Клапан 2] Characteristic.On - [GET] true
18.08.2020, 10:20:53 [TuyaWebPlatform] [GET] Requesting too quickly. - you can query once in 60 seconds
18.08.2020, 10:20:53 [TuyaWebPlatform] [GET] Requesting too quickly. - you can query once in 60 seconds
18.08.2020, 10:20:53 [TuyaWebPlatform] [GET] Requesting too quickly. - you can query once in 60 seconds
18.08.2020, 10:20:53 [TuyaWebPlatform] [GET] Requesting too quickly. - you can query once in 60 seconds
18.08.2020, 10:20:53 [TuyaWebPlatform] [GET] Requesting too quickly. - you can query once in 60 seconds
18.08.2020, 10:20:53 [TuyaWebPlatform] [GET] Requesting too quickly. - you can query once in 60 seconds
18.08.2020, 10:20:53 [TuyaWebPlatform] [GET] Requesting too quickly. - you can query once in 60 seconds
18.08.2020, 10:20:53 [TuyaWebPlatform] [GET] Requesting too quickly. - you can query once in 60 seconds
18.08.2020, 10:20:53 [TuyaWebPlatform] [GET] Requesting too quickly. - you can query once in 60 seconds

**Comment by motogon** [comment]
![изображение](https://user-images.githubusercontent.com/12997195/90483442-63181a00-e13d-11ea-941b-826a92eefcea.png)

**Comment by costispavlou** [comment]
Hi everyone and @milo526. Problem is indeed fixed but only one out of the 3 accessories (boiler switch) is showing.
My two shutter covers are not. Any chance I'm doing anything wrong? 
Here's my log:
[TuyaWebPlatform] Existing Accessory found [Name: Boiler Switch] [Tuya ID: ***] [HomeBridge ID: **]
[TuyaWebPlatform] [Boiler Switch] Characteristic.On - Enabled
[TuyaWebPlatform] Could not init class for device type [cover]

and config:

"defaults": [
                {
                    "id": "606020702cf4323eb64b",
                    "device_type": "Cover"
                },
                {
                    "id": "606020702cf4323e73fa",
                    "device_type": "Cover"
                }
            ],

Is cover not yet supported? I used an other plugin for them before I switched to yours and everything was working and cover was supported.

**Comment by costispavlou** [comment]
> Plugin is working.
> 
> But some of the accessories in the Home application are in the status of no response
> 
> 18.08.2020, 10:20:53 [TuyaWebPlatform] [Полив клапан 1] Characteristic.On - [GET] true
> 18.08.2020, 10:20:53 [TuyaWebPlatform] [Клапан 4] Characteristic.On - [GET] true
> 18.08.2020, 10:20:53 [TuyaWebPlatform] [Гостевая спальня] Characteristic.On - [GET] false
> 18.08.2020, 10:20:53 [TuyaWebPlatform] [Гостевая спальня] Characteristic.Brightness - [GET] 32
> 18.08.2020, 10:20:53 [TuyaWebPlatform] [Smart Plug2] Characteristic.On - [GET] false18.08.2020, 10:20:53 [TuyaWebPlatform] [Клапан 2] Characteristic.On - [GET] true
> 18.08.2020, 10:20:53 [TuyaWebPlatform] [GET] Requesting too quickly. - you can query once in 60 seconds
> 18.08.2020, 10:20:53 [TuyaWebPlatform] [GET] Requesting too quickly. - you can query once in 60 seconds
> 18.08.2020, 10:20:53 [TuyaWebPlatform] [GET] Requesting too quickly. - you can query once in 60 seconds
> 18.08.2020, 10:20:53 [TuyaWebPlatform] [GET] Requesting too quickly. - you can query once in 60 seconds
> 18.08.2020, 10:20:53 [TuyaWebPlatform] [GET] Requesting too quickly. - you can query once in 60 seconds
> 18.08.2020, 10:20:53 [TuyaWebPlatform] [GET] Requesting too quickly. - you can query once in 60 seconds
> 18.08.2020, 10:20:53 [TuyaWebPlatform] [GET] Requesting too quickly. - you can query once in 60 seconds
> 18.08.2020, 10:20:53 [TuyaWebPlatform] [GET] Requesting too quickly. - you can query once in 60 seconds
> 18.08.2020, 10:20:53 [TuyaWebPlatform] [GET] Requesting too quickly. - you can query once in 60 seconds

same here
