### ISSUE TITLE
Fan/Lisht Switch Treatlife DS03 shows only as Fan

### ISSUE THREAD

**Issue by carlosdesedas** [milo526/homebridge-tuya-web#490]
Hi..
after adding all of my devices from my SmartLife app to Homebridge, the DS03 Fan/Light Switch which is recognized correctly in the SmartLife App only show as "Fan" in Homebridge.  I tried to manually override this by getting the device id and trying to configure it as a fan/light controller but there is no such option.

Plugin version homebridge-tuya-web v1.1.2 (2022-05-06)

**Comment by milo526** [comment]
These devices are not properly exposed by Tuya to the API that this plugin uses.

You might be better served by the plugin that Tuya themselves maintain (https://github.com/tuya/tuya-homebridge), this uses a different API which is harder to configure for users but has more options.
