### ISSUE TITLE
Fan controller not showing in devices

### ISSUE THREAD

**Issue by daanniey** [milo526/homebridge-tuya-web#494]
Hi I able to link all the devices except Fan controller. kindly help me out. 

its showing as below

Tried overwriting device config for: "d762a556ace7800f90tsen" which is not a valid device-id or device-name.

**Comment by tomernation** [comment]
Same here

**Comment by milo526** [comment]
Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

Without this it is hard for me to help you with regards to this specific issue.
