### ISSUE TITLE
Air conditioner shows 150 degrees when its 24.0, logs show "exceeded maximum of 150". weird?

### ISSUE THREAD

**Issue by edento** [milo526/homebridge-tuya-web#496]
I tried to look at the code because I suspected its something related to parsing the number but i couldnt find anything (i am just a js developer, not yet familiar with iot stuff)

**Describe the bug**
I added the credentials to the plugin so it can add our air conditioner to homebridge. (i did not add it manually)
the pairing is successfull.

The issue: the current temperature shown is 150, regardless of the real value.
Expected: be able to see the real value.

the logs show:
```
[11/16/2022, 10:06:45 PM] [@milo526/homebridge-tuya-web] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 240 exceeded maximum of 150. See https://homebridge.io/w/JtMGR for more info.
```

The current temp in tuya app is 24.0, so maybe theres an issue with x10?

**Steps To Reproduce**

1. go to tuya app - the current temp is 24.0 celcius
2. open homebridge
3. go to accessories
4. the AC accessory shows 150 (screenshot attached)
<img width="786" alt="image" src="https://user-images.githubusercontent.com/12493042/202286574-415dab0d-fadb-4bcb-8673-81ce277d4b26.png">

**Plugin Version**
1.1.2 (latest)

 **Homebridge Config**
 
 ```json
{
    "name": "TuyaWebPlatform",
    "options": {
        "username": "*****",
        "password": "*****",
        "countryCode": "972",
        "platform": "tuya"
    },
    "defaults": [
        {
            "device_type": "form"
        }
    ],
    "scenes": false,
    "platform": "TuyaWebPlatform"
}
 ```
 
 **Device Config**
 
 
 **Additional Context**
The plugin DOES control the on/off state and temperature of the AC, but it just shows WRONG the current temperature

Thanks in advance.

**Comment by acharris76** [comment]
Hi, I've got the same issue with some Tuya controlled radiators. They are showing the current temperature of 150 C and that they are set to 220 C. The actual numbers are that the room is 22 C and the radiators are set to 22 C. The Tuya app shows the correct information. Please help!

**Comment by milo526** [comment]
Please try setting the `temperature_factor` to `0.1` in your config files for the respective devices.

**Comment by acharris76** [comment]
Done and works! Thanks!

**Comment by edento** [comment]
@milo526 its me again. i have an issue with the target temperature now. I get the following error:

```
[7/14/2023, 8:51:07 PM] [@milo526/homebridge-tuya-web] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 2 exceeded minimum of 16. See https://homebridge.io/w/JtMGR for more info.
```

The current temperature (AC) is correct, but the target always shows 16.0

<img width="779" alt="image" src="https://github.com/milo526/homebridge-tuya-web/assets/12493042/46ad8780-536c-45a8-8c96-dad841d8ba3a">

Plugin verssion: `1.1.3`

this is my plugin config:

```json
{
    "name": "TuyaWebPlatform (for AC)",
    "options": {
        "username": "***",
        "password": "****",
        "countryCode": "972",
        "platform": "tuya"
    },
    "defaults": [
        {
            "id": "****",
            "device_type": "climate",
            "min_temper": "16.0",
            "max_temper": "35.0",
            "current_temperature_factor": "0.1",
            "target_temperature_factor": "0.1"
        }
    ],
    "scenes": false,
    "platform": "TuyaWebPlatform"
}
```

I tried googling this issue but i can't understand what is wrong in my configuration... thanks!
