### ISSUE TITLE
Two Switches UI for Every Outlet After Updating

### ISSUE THREAD

**Issue by ahmadnazirafiq** [milo526/homebridge-tuya-web#51]
**Describe the bug**
After installing 0.4.3, all of my Smart Life outlets has two switches (used to be just one) appeared in the Home app. Its kind of redundant and unnecessary, and I had to separate each tile manually to quickly turn the outlet on/off. Is there a way to disable this additional switches? I even have tried to add device_type manually for each outlet yet the issue persists.

On top of that, it also caused my other plugins to load slowly as well, with the Homebridge keep showing "Requesting too quickly" error despite setting the polling to 0. This used to be instantaneous before updating and has never affected other plugins :(

![IMG_4504](https://user-images.githubusercontent.com/66505845/90016084-11eecd00-dcdc-11ea-9def-fbfd5b92005e.PNG)

![IMG_4505](https://user-images.githubusercontent.com/66505845/90016071-0ac7bf00-dcdc-11ea-8857-78c07024c059.PNG)

**Comment by milo526** [comment]
Please clear your accessory cache to remove the redundant switches.

The other problem is a known issue but does not have an easy solution. I'm still working on it.

Thanks for reporting these issues.

**Comment by milo526** [comment]
Where you able to reset your accessory cache? Did that solve your issue?

If so please close this Github issue.

For the other problem please take a look at #50

**Comment by ahmadnazirafiq** [comment]
Hi, thank you for your swift response! This has fixes the issue. Appreciate it 👍
