### ISSUE TITLE
Rgb and temp lamp

### ISSUE THREAD

**Issue by Mathias2500** [milo526/homebridge-tuya-web#511]
**Describe the bug**
After I changed my router everything disappeared. I got the three sockets/outlets back, but one bulb/lamp can’t be found again.
I tried both using the name and I’d, but no luck

**Steps To Reproduce**
The device appears and the state in HomeKit can be changed, but it doesn’t respond at all.

**Plugin Version**
1.1.2
Current
 
 
 **Homebridge Config**
 
 
 ```json

 {
            "name": "TuyaWebPlatform",
            "options": {
                "username": "xxxxxxxx",
                "password": "xxxxxxxx",
                "countryCode": "45",
                "platform": "tuya"
            },
            "defaults": [
                {
                    "id": "B",
                    "device_type": "outlet"
                },
                {
                    "id": "C",
                    "device_type": "outlet"
                },
                {
                    "id": "A",
                    "device_type": "outlet"
                },
                {
                    "id": "Kretalampen",
                    "device_type": "light",
                    "min_brightness": "8",
                    "max_brightness": "100",
                    "light_characteristics": [
                        "Brightness",
                        "Color"
                    ]
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatformi"
        }
    ]
}

```
 
 **Device Config**
 
 
 **Additional Context**

**Comment by milo526** [comment]
Can you control the light from the Tuya app?

**Comment by Mathias2500** [comment]
YesVenlig hilsenMathias RolDen 31. dec. 2022 kl. 11.17 skrev Milo Cesar ***@***.***>:﻿
Can you control the light from the Tuya app?

**Comment by Mathias2500** [comment]
And it worked just fine on the old router 🤷🏻‍♂️Venlig hilsenMathias RolDen 31. dec. 2022 kl. 20.40 skrev Mathias Rol ***@***.***>:﻿YesVenlig hilsenMathias RolDen 31. dec. 2022 kl. 11.17 skrev Milo Cesar ***@***.***>:﻿
Can you control the light from the Tuya app?
