### ISSUE TITLE
Option to toggle debug on/off

### ISSUE THREAD

**Issue by psycoticninja** [milo526/homebridge-tuya-web#513]
**Is your feature request related to a problem? Please describe.**

I have lights that I only turn on once a year (Christmas Lights) via Tuya. 

When it is not in use for the other 11 months of the year, every ~20mins (or whatever polling period is) it will log debug in Homebridge that these are lights are offline which will fill the debug view up.

**Describe the solution you'd like**

A toggle switch in the plugin settings to Enable/Disable debug so it can be invoked only during a debug session.

I don't believe this option currently exists.

**Describe alternatives you've considered**

None at this stage.

**Additional context**

N/A.

**Comment by milo526** [comment]
Hey!

There is an option hide accessories.

This removes them from homebridge.

Would it work for you to move the outlet to that list once every year?

**Comment by psycoticninja** [comment]
This worked a treat - thanks @milo526. Closing off.
