### ISSUE TITLE
Error when loading not a valid device-id or device-name

### ISSUE THREAD

**Issue by livefeed** [milo526/homebridge-tuya-web#514]
Hello, I know I am using the correct ID but I can't get a garage door to show up, I receive the following;

[TuyaWebPlatform] Tried overwriting device config for: "ytqsem3wehsnd7hs3hvc" which is not a valid device-id or device-name.

Any ideas?

**Comment by milo526** [comment]
Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

Without this it is hard for me to help you with regards to this specific issue.
