### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by modkeyIT** [milo526/homebridge-tuya-web#517]
Saw comments that this was resolved in 2021 but I am getting the error again:

[TuyaWebPlatform] Authentication error: you cannot auth exceed once in 180 seconds

**Comment by milo526** [comment]
Don't know where you saw that comment but this is an issue on Tuya's side, not something I/this plugin can change.

You get this error if you restart sooner than every 3 minutes or also use another Tuya integration.

**Comment by modkeyIT** [comment]
I had to just add the devices under Device Settings - Previously it was pulling up devices from existing cache.  Once I readded them in device settings and rebooted, it worked.  Thanks.

**Comment by korskantevin** [comment]
i'm getting message [TuyaWebPlatform] Authentication error: Get accesstoken failed. Username or password error!

username is "iolaus@mail.ru"? try as iolaus but this is nickname in the app
