### ISSUE TITLE
After update still updating all homebridge accessory in homekit

### ISSUE THREAD

**Issue by Martinx64** [milo526/homebridge-tuya-web#52]
After update still updating all homebridge accessory in homekit. Devices sometimes working, but most of time are in status “no response”. In homebridge logs every few seconds appears: “Tuya Web Platform [Requesting too quickly].
When i uninstall homebridge-tuya-web, all accessory working perfect. Previous version of homebridge-tuya-web worked great. Could you please fux this issues in new version?

Thx

**Comment by milo526** [comment]
Hello and thank you for taking the time to respond to this issue. It is much appreciated.

If you look at the issues tab you can see that there is already another issue opened in which we discuss this problem, please read the reaction I posted there. Any further reactions and solutions with regards to this issue will also be discussed there.

**Comment by milo526** [comment]
Would be very nice of me to actually place a link to #50 so you don't have to search for it 😄

**Comment by Martinx64** [comment]
Plese can you help me, how can i downgrade your plugin to v0.3.3 via
terminal? I tried runed npm -E -n install
@milo526/homebridge-tuya-web@v0.3.3

under root user, but it doesnt work. Should i run it under another user
maybe?

Thank you

Dňa st 12. 8. 2020 o 17:40 Milo Cesar <notifications@github.com>
napísala(a):

**Comment by mbierman** [comment]
npm uninstall @milo526/homebridge-tuya-web
npm install @milo526/homebridge-tuya-web@0.3.3
 
Add “-g” if the plugin is installed globally (Not homebridge UI or HOOBS)

**Comment by Martinx64** [comment]
Thank you. Can i run it in terminal under root?

Dňa pi 14. 8. 2020 o 0:03 Michael Bierman <notifications@github.com>
napísala(a):

**Comment by mbierman** [comment]
Terminal yes! I think y
U have to run it as the same user that is running homebridge. If that’s root then yes.

**Comment by Martinx64** [comment]
This is the problem. I installed it from homebridge UI and this is
installed via user “homebeidge”. When i try to connect to terminal under
user “homebridge” it says “Access denied”. Can you help me?

Dňa pi 14. 8. 2020 o 0:09 Michael Bierman <notifications@github.com>
napísala(a):

**Comment by mbierman** [comment]
In Homebridge UI go to the terminal and use the commands.

**Comment by Martinx64** [comment]
How can i accessterminal in homebridge?

Dňa pi 14. 8. 2020 o 0:32 Michael Bierman <notifications@github.com>
napísala(a):

**Comment by mbierman** [comment]
![Untitled](https://user-images.githubusercontent.com/1205471/90194338-ef13f580-dd7b-11ea-91cf-c1dac2686d72.png)

**Comment by Martinx64** [comment]
I dont have this oprion, but i mean that in past it was there. Is som way
to enable/disable hhis future?

Dňa pi 14. 8. 2020 o 0:45 Michael Bierman <notifications@github.com>
napísala(a):
