### ISSUE TITLE
Recovering from power outage

### ISSUE THREAD

**Issue by shrubstabla** [milo526/homebridge-tuya-web#524]
This plugin for Tuya products is excellent, but there's a feature you should consider implementing as a backstop when a power outage occurs.  I use a Tuya-compatible line switch to control a garden water feature that is normally on a schedule to run at certain times during the daytime.  Just recently a power outage occurred that shut down the entire neighbourhood, but when the power was restored, my water feature which was off when the power outage occurred, switched on and began to run at night.  Had it run through the night and ran out of water, a fire could have occured if the motor roared on dry.  I realise that the behavour of this switch is not your responsibility, but perhaps you could build into the plugin the ability to restore the device affected by the power outage to its former state following a power outage or a manual setting to restore the device to an off state following a power outage

Thank you for your good work

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mbierman** [comment]
Please consider this feature!

**Comment by shrubstabla** [comment]
What feature?

**Comment by shrubstabla** [comment]
Why is this issue stale?  I am seeking a response to my feedback

**Comment by mbierman** [comment]
@shrubstabla the issue you raised here. 

It was marked stale because no one acted on it.

**Comment by shrubstabla** [comment]
It would be useful if someone acted on my suggestion.  It’s a good one, and one that could be easily implemented - a simple switch option in Settings that either leaves the device in a power-off status when power is returned, or restoring the pre power outage state

**Comment by milo526** [comment]
Go for it! This is opensource software. You at free and more than welcome to help improve it!

**Comment by mbierman** [comment]
Would still love to have this added at some point. Does tuya have a status indicator after a device is powered off or powered back on?
