### ISSUE TITLE
Plugin not found using web UI search

### ISSUE THREAD

**Issue by TeslaOwnerTips** [milo526/homebridge-tuya-web#527]
![image](https://user-images.githubusercontent.com/78335749/215315634-a369d174-349b-4890-8421-ae46ec553a97.png)

**Describe the bug**

**Steps To Reproduce**

**Plugin Version**
 
 
 **Homebridge Config**
 
 
 ```json

```
 
 **Device Config**
 
 
 **Additional Context**

**Comment by TeslaOwnerTips** [comment]
?

**Comment by milo526** [comment]
Fixed via #531
