### ISSUE TITLE
Thermostat Reporting Incorrect Temps

### ISSUE THREAD

**Issue by Clayton1212** [milo526/homebridge-tuya-web#533]
Please see details here. I added the issue to the incorrect page
https://github.com/homebridge/homebridge/issues/3319#issuecomment-1433121751

**Comment by milo526** [comment]
Please find the answer to your problem in the wiki.

https://github.com/milo526/homebridge-tuya-web/wiki/Something-will-receive-higher-or-lower-value-than-allowed

**Comment by Clayton1212** [comment]
Hi, thank you very much for the quick response and the wiki.
This has worked perfectly. I really appreciate your work on this.
Do you by any chance know if or how I could add a robot vacuum here?
