### ISSUE TITLE
 The write handler for the characteristic 'On' on the accessory '(accessory name)' was slow to respond!

### ISSUE THREAD

**Issue by khammo01** [milo526/homebridge-tuya-web#545]
Since about one week before this issue reporting, have been seeing very slow response for all Tuya  switches devices, with this entry in the home bridge log: 

 The write handler for the characteristic 'On' on the accessory '(accessory name)' was slow to respond! 
 The write handler for the characteristic 'Off' on the accessory '(accessory name)' was slow to respond!
 
 Light eventually responds about 5-10 seconds later. Response is immediate when controlled from Tuya Smart Life app. 
 
 This is a simple on/off switch. 
 
 version 1.1.3

**Comment by khammo01** [comment]
This behavior continues to persist  for any Tuya switches.

**Comment by milo526** [comment]
Prs are welcome
