### ISSUE TITLE
Is this plugin now maintained? 

### ISSUE THREAD

**Issue by gdotp01** [milo526/homebridge-tuya-web#546]
I’d guess that this plug-in should now be marked as Not Maintained. There are plenty of issues that go stale without any progress and a number that cause issues with the rest of homebridge. I’ve had to disable it to prevent
to wider Homebridge issues and the issue that I reported was marked as stale.

**Comment by milo526** [comment]
You are more than welcome to send in Pull requests to fix the issues you are experiencing 😄 I'll gladly review them.

I am actively fixing security issues for this plugin but it is hard for me to find the time to fix bugs and introduce new features.
