### ISSUE TITLE
I have a Pro Breeze AC unit, and there are a couple of missing options that would be super useful to control in HomeKit

### ISSUE THREAD

**Issue by KE55ARD** [milo526/homebridge-tuya-web#562]
**Is your feature request related to a problem? Please describe.**

I have a Pro Breeze AC unit, and if I want to use Sleep Mode, Fan Only Mode or change the fan speed I still have to use the Tuya app.

**Describe the solution you'd like**

I believe it should be possible to show "Sleep" and "Fan" as a mode in the list within homeKit (which currently shows Auto/Off).
I also think fan speed is an option, although I'm not 100% sure if compatible with the device type my unit currently appears as.

**Describe alternatives you've considered**

**Additional context**

Thanks for any help you can provide.

**Comment by milo526** [comment]
Hey; 

Could you please post the output of the script as linked in https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device 
I need that to figure out what options are available.

**Comment by KE55ARD** [comment]
Here it is (minus the credentials it outputs)

`Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {   'current_temperature': 20,
                                                  'max_temper': 86,
                                                  'min_temper': 16,
                                                  'online': True,
                                                  'state': 'false',
                                                  'temp_unit': 'CELSIUS',
                                                  'temperature': 22},
                                      'dev_type': 'climate',
                                      'ha_type': 'climate',
                                      'icon': 'https://images.tuyaeu.com/smart/product_icon/kt.png',
                                      'id': 'bf568af9a85612e95dzgne',
                                      'name': 'Master Aircon'},
                                  {   'data': {   'current_temperature': 21,
                                                  'max_temper': 86,
                                                  'min_temper': 16,
                                                  'online': True,
                                                  'state': 'false',
                                                  'temp_unit': 'CELSIUS',
                                                  'temperature': 20},
                                      'dev_type': 'climate',
                                      'ha_type': 'climate',
                                      'icon': 'https://images.tuyaeu.com/smart/product_icon/kt.png',
                                      'id': 'bf81ca209738da5449f25y',
                                      'name': 'Lounge Aircon'}],
                   'scenes': []}}
`

**Comment by milo526** [comment]
It does not seem to expose any information regarding this state so I expect I won't be able to help you with this :/

You might be able to use scenes to set the proper status, you can whitelist scenes so they show up as switches in homekit.

**Comment by KE55ARD** [comment]
Ah annoying thanks for looking.I’ve tried the scene trick, thanks for the tip. But it’s not working it seems. Tried both adding the ones I want by name and ID but neither show in my Home app.James KennardOn 6 Oct 2023, at 15:42, Milo Cesar ***@***.***> wrote:﻿
It does not seem to expose any information regarding this state so I expect I won't be able to help you with this :/
You might be able to use scenes to set the proper status, you can whitelist scenes so they show up as switches in homekit.
