### ISSUE TITLE
[NEW DEVICE] 

### ISSUE THREAD

**Issue by Ralf-Th** [milo526/homebridge-tuya-web#563]
**Device type**

it is the thermostat for a koenighaus infrared heater
the device id is not accepted, so i think, you have to add this?

**Device information**

```json

```

on https://eu.iot.tuya.com i found this information

Device Name | Device ID | Product | Device Status | Device Type | Activation Time | Device Permission | Operation
-- | -- | -- | -- | -- | -- | -- | --
InfrarotHeizung | bf890dffa269551912pqna | WBR3-HY02TPWIFI-带制冷 | Online | Real Device | 2023-10-01 12:14:24 | Read, write, and Manage | Unlink

**Comment by milo526** [comment]
Please check [the README](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device) on what to do if the device is currently not supported.
