### ISSUE TITLE
no devices showing

### ISSUE THREAD

**Issue by bwp91** [milo526/homebridge-tuya-web#57]
hello i was getting this error with version 0.3.3 so i upgraded to 0.4 and now i am getting a different error but the error is not showing in the log files since i installed the beta version of homebridge so i don't know what the error is but the logs show "frequentlyinvoke" so i installed hoobs with your scoped package and that worked for a few minutes but then i enjoyed the sun for two hours and then when i opened home app i got a different error in the homebridge log it didn't let me log in after using sign in with apple which i think is due to the "frequentlyinvoke" error that didn't appear in the hoobs log so then i installed the unscoped package on hoobs and now no tuya devices are appearing on my homebridge with your plugin uninstalled which is sad because my tuya scenes were working well with 0.3.3 but now with the new version on hoobs my fan is no longer working i can't get it to 150% because in the alexa app the limit now seems to be 100% but it is still working in google in homebridge on my pi i hope all this makes sense and waiting eagerly for this to be working again as until then my boiler is on pause and i cannot have a hot shower thank you for your commitment to this plugin i would definitely use it if i had tuya any tuya devices as mine are sonoff.
😝

**Comment by milo526** [comment]
Closing since this issue is not following the required issue template 😄

**Comment by bwp91** [comment]
if i had waited another five minutes this issue wouldn't have been needed anyway as 0.4.4 seems to have fixed my shower so thank you and i've just also realised that no devices are showing because i don't have any tuya devices so that makes sense
