### ISSUE TITLE
Not a valid device ID

### ISSUE THREAD

**Issue by eastrockdev** [milo526/homebridge-tuya-web#586]
Getting error in HB log: "Tried overwriting device config for: "ebfa102d329839e3c9ns1f" which is not a valid device-id or device-name"

The device-id, username and password are all correct. Does not work.

**Comment by lucanaut** [comment]
Me too! Device ID not recognized and it doesn’t work even if I don’t enter anything. I’ve never had to enter any device IDs for my other devices, but this one I can’t get to show up on kit no matter what I do.

**Comment by tablatronix** [comment]
Same no longer finding my devices only cached ones.  Not sure what broke
