### ISSUE TITLE
2CH dimmer switch module doesn't work correctly 

### ISSUE THREAD

**Issue by chielbl** [milo526/homebridge-tuya-web#597]
**Describe the bug**
By adding a 2CH dimmer switch module I don't get the second switch dat is related on that module. 
I can toggle only one switch to put ON or OFF.

**Steps To Reproduce**
1. Add a 2CH dimmer switch module
2. You see only one buttons to switch 1 ON or OFF but the second one is missing

**Plugin Version**
1.1.5
 
 **Homebridge Config**
```
 {
     "name": "TuyaWebPlatform",
     "options": {
         "username": REDACTED,
         "password": REDACTED,
         "countryCode": REDACTED,
         "platform": "tuya",
     },
     "scenes": false,
     "platform": "TuyaWebPlatform"
 }
```
<img width="217" alt="Screenshot 2024-03-20 at 16 09 15" src="https://github.com/milo526/homebridge-tuya-web/assets/45933520/b90feb5e-228f-4870-8be6-e3e930ab35e1">
<img width="831" alt="Screenshot 2024-03-20 at 16 09 46" src="https://github.com/milo526/homebridge-tuya-web/assets/45933520/0f160e27-bce0-480b-811a-490fedfec66a">

**Comment by milo526** [comment]
This is a known problem; multiple outputs are not supported by the API that this plugin uses.

You can verify this yourself by executing the python script which is linked in the readme.

**Comment by milo526** [comment]
The header ["How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device) in t he readme

Should contain all the information that you need.
