### ISSUE TITLE
Smart WiFi Fan Switch Ceiling Fan and Light Universal Remote Control Kit

### ISSUE THREAD

**Issue by Dalexander12193** [milo526/homebridge-tuya-web#601]
Hello, 
I need help getting my fan/light controller added by Homebridge. I do not have the model number, but I have a photo of what it looks like. I will upload a picture and link it to Amazon. However, I would be very thankful if someone could give me the steps to connect my fan/light controller to Homebridge with this plugin or a different one. I tried all the device types on this plugin. None of them are working, but I think this is happening because it is a light and fan combo. 
Thanks 

[https://www.amazon.com/Ceiling-Controller-Compatible-Required-Universal/dp/B07Z948VY4/ref=asc_df_B07Z948VY4/?tag=hyprod-20&linkCode=df0&hvadid=385180347961&hvpos=&hvnetw=g&hvrand=15952053339921015072&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9028920&hvtargid=pla-865104233644&psc=1&mcid=a05b6393819831278e6373ba41dae98d&tag=&ref=&adgrpid=78829232296&hvpone=&hvptwo=&hvadid=385180347961&hvpos=&hvnetw=g&hvrand=15952053339921015072&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9028920&hvtargid=pla-865104233644&gclid=CjwKCAjwoa2xBhACEiwA1sb1BHvf3ByzvNwJdfLd5Zr0SF0LuCRKr_ss0vUraFo1WGwrU70zycZGPxoCxEUQAvD_BwE](url)

<img width="441" alt="Screenshot 2024-04-26 at 3 53 11 PM" src="https://github.com/milo526/homebridge-tuya-web/assets/168235751/8393b525-38fc-40fa-8b1f-d062e55fadac">

**Comment by isaiahfranco** [comment]
I am also unable to get this added to HomeKit. It works from the Tuya app as well as Alexa.
