### ISSUE TITLE
[Feature Request] Device command buffering

### ISSUE THREAD

**Issue by RFHold** [milo526/homebridge-tuya-web#604]
**Is your feature request related to a problem? Please describe.**

There is a common problem with some devices and the way scenes are set. When I activate scenes that change the color, the color doesn't always change. It seems like these devices do not handle concurrency very well and some commands overwrite the final setting of the light.

**Describe the solution you'd like**

I would like to be able to enable some sort of command buffering where commands to the same device are held in memory and sent one by one with a configurable delay.

**Describe alternatives you've considered**

It looks like I can achieve something similar with stateless devices but that would require more manual configuration than I'd like.

**Additional context**

Logs show 3 separate commands coming in for all 15 of my devices within the span of a second.

I am willing to do this if it would be a desired feature

**Comment by milo526** [comment]
Sounds like a good idea; I'm open to PRs
