### ISSUE TITLE
[Feature request] Air Conditioner Accessory with Turbo mode for UsbWifi

### ISSUE THREAD

**Issue by levankhelo** [milo526/homebridge-tuya-web#605]
**Is your feature request related to a problem? Please describe.**

New Accessory Class for Air Conditioner. Currently my Air Conditioner is controlled with external usb plugin shown on tuya platform as "UsbWifi". This device Allows me to use Air Conditioner with all of it's features. 
On homebridge plugibn you have made, i currently have it configured as `Thermostat` that allows me to switch between conditions and temperatures. This works Very well and Thanks for that! 
Is there a chance to add new class so we can control ACs?

**Describe the solution you'd like**

New class has been created for AC or thermostat class has additional attribute for turbo control. I will also look into it when i'll have time and try to contribute.

**Describe alternatives you've considered**

Alternative (i think even better and easier solution) would be adding optional boolean attribute to Thermostat class saying "allow turbo" which will add turbo trigger button on homekit accessory. 

**Additional context**

This are Configuration parameters for Smart Air Conditioner. 
Attribute `fan_speed_enum` should be set to `strong` for turbo mode

| Code               | Type    | Values                                                                                                                                              |
|--------------------|---------|-----------------------------------------------------------------------------------------------------------------------------------------------------|
| `switch`           | Boolean | `{true,false}`                                                                                                                                      |
| `temp_set`         | Integer | `{ "unit": "℃", "min": 16, "max": 90, "scale": 0, "step": 1 }`                                                                                       |
| `mode`             | Enum    | `{ "range": ["auto", "cold", "hot", "wet", "wind"] }`                                                                                               |
| `fan_speed_enum`   | Enum    | `{ "range": ["strong", "auto", "low", "middle", "high", "mute"] }`                                                                                  |
| `anion`            | Boolean | `{true,false}`                                                                                                                                      |
| `heat`             | Boolean | `{true,false}`                                                                                                                                      |
| `sleep`            | Boolean | `{true,false}`                                                                                                                                      |
| `gear_vertical`    | Enum    | `{ "range": ["off", "same", "vane_1", "vane_2", "vane_3", "vane_4", "vane_5"] }`                                                                    |
| `switch_horizontal`| Boolean | `{true,false}`                                                                                                                                      |
| `display`          | Boolean | `{true,false}`                                                                                                                                      |

**Comment by milo526** [comment]
Thanks for the extensive feature request, however, before being able to help I'll need the output of the tuya HomeAssistant api endpoint.

Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)
