### ISSUE TITLE
SmartLife don't work

### ISSUE THREAD

**Issue by DavidOsornio98** [milo526/homebridge-tuya-web#608]
**Describe the bug**

I'm trying to connect my account but this error appears in the terminal: "[TuyaWebPlatform] Authentication error: Get accesstoken failed. Username or password error!"
My username and password are not bad because in the Smarlife app I can connect without problems.

Each time it restarts, this message appears:: "[TuyaWebPlatform] Cannot acquire token, waiting 185 seconds."

**Steps To Reproduce**

**Plugin Version**
 
 1.1.5
 **Homebridge Config**
 
 
 ```json
  {
            "name": "TuyaWebPlatform",
            "options": {
                "username": "deividdg6273@gmail.com",
                "password": "",
                "countryCode": "52",
                "platform": "smart_life"
            },
            "defaults": [
                {
                    "device_type": "form"
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        }
```
 
 **Device Config**
 
 
 **Additional Context**
 
I have HomeBridge version 1.8.3 installed.
It's my first time installing this plugin

**Comment by corvel** [comment]
Are you sure you created account using username and password, not Apple or Google SSO? Account with linked Apple or Google does not work with this API.

**Comment by milo526** [comment]
Please also check the wiki: https://github.com/milo526/homebridge-tuya-web/wiki/Authentication-Error that has some extra steps you can take to check your credentials.

**Comment by DavidOsornio98** [comment]
It's true, third-party accounts are not supported, I've already created a new account but now I'm getting the following error:
[TuyaWebPlatform] Missing required `id` property on device configuration, received:
{
  "device_type": "form"
}
Any idea how I can solve it?  :D

this is my json:
{
            "name": "TuyaWebPlatform",
            "options": {
                "username": "divadaicrag98@live.com",
                "password": "",
                "countryCode": "52",
                "platform": "smart_life"
            },
            "defaults": [
                {
                    "device_type": "form"
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
}

**Comment by DavidOsornio98** [comment]
sorry, my bad.
The error is caused because there is no device on the account.
Before adding the Pluggin to HomeBridge it is important to already have the Tuya account configured with devices.
tys
