### ISSUE TITLE
[TuyaWebPlatform] Cannot acquire token, waiting 185 seconds.

### ISSUE THREAD

**Issue by Kaydeno113** [milo526/homebridge-tuya-web#609]
**Describe the bug**

When Starting tuya web platform get error   [TuyaWebPlatform] Cannot acquire token, waiting 185 seconds.
After 185 seconds get error [TuyaWebPlatform] Authentication error: Get accesstoken failed. Username or password error!
I have checked that username and password are correct

**Steps To Reproduce**
I dont know how to reproduce I have deleted the plugin and reinstalled, even created a new tuya account

**Plugin Version**
1.1.5

 **Homebridge Config**
{
    "platform": "TuyaWebPlatform",
    "name": "TuyaWebPlatform",
    "options": {
        "username": "kaydxxx@xxxxxd.com",
        "password": "mypasswordgoeshere",
        "countryCode": "1",
        "platform": "tuya"
    }
}

Plugin Log

[@milo526_homebridge-tuya-web.log.txt](https://github.com/user-attachments/files/16046110/%40milo526_homebridge-tuya-web.log.txt)

Thanks in advance for any help

**Comment by robt5017** [comment]
Having the same problem as well. Tried uninstalling the plugin and adding it back, but now I it won’t even add it back to HomeKit when I scan the QR code for the child bridge.

**Comment by Mario1322** [comment]
Have you managed to fix the error?

**Comment by TheClyk** [comment]
Same error for me sadly, previously has been working fine for years.

**Comment by lawiltshire** [comment]
Same issue here
