### ISSUE TITLE
cannot change temperature on iOS 18

### ISSUE THREAD

**Issue by Catta1997** [milo526/homebridge-tuya-web#612]
On iOS/ iPadOS 18 you can't change temperature on an AirConditioner, on macOS Sonoma you can so it's not a config issue. Still trying to understand is its a bug of the beta or Apple changed something but since it happen since beta 1 I'm more for the second option

Screen iOS 18 vs macOS Sonoma 

macOS Sonoma:
<img width="281" alt="image" src="https://github.com/user-attachments/assets/cc6fc596-81c2-471f-a909-9a927715d70d">

iOS 18 dev beta 4:
![IMG_1999](https://github.com/user-attachments/assets/fba7abb0-0d19-49f0-9c14-94fc2b6c18fb)

**Comment by env-dxb** [comment]
Same thing w mine

**Comment by Catta1997** [comment]
No news?

**Comment by Catta1997** [comment]
UPDATE: Fixed on iOS 18 beta 6
