### ISSUE TITLE
Is it possible to set default device type to outlet?

### ISSUE THREAD

**Issue by ahwman** [milo526/homebridge-tuya-web#68]
All of my devices are shown as switches. I tried setting device type from “form” to “outlet” in the config file without success. Is there another way to accomplish this?

Thanks so much for all your hard work!

**Comment by ahwman** [comment]
> > All of my devices are shown as switches. I tried setting device type from “form” to “outlet” in the config file without success. Is there another way to accomplish this?
> > Thanks so much for all your hard work!
> 
> I had the same problem, but is my problem, you need check ID device + ID socket example
> My strip power socket have 4 sockets
> ID device 82849hdiqoru8264648
> ID socket 1
> You need add 82849hdiqoru8264648_1
> And this device now show as socket

The problem with using the “device overwrite” option is that I end up with duplicate devices and I can’t figure out how to remove the original device.

**Comment by cilianospina** [comment]
No problem, you need Remove Single Cached Accessory in homebridge Settings, reboot and work fine.

**Comment by ahwman** [comment]
> No problem, you need Remove Single Cached Accessory in homebridge Settings, reboot and work fine.

I tried that but only the original device is shown in Cached Accessories and I was worried that deleting that would remove both devices...

**Comment by cilianospina** [comment]
just do it, you won't have any problem

**Comment by ahwman** [comment]
> just do it, you won't have any problem

That did the trick!  Thanks so much everyone... 😀
