### ISSUE TITLE
Homebridge doesn't see my "Mini Smart Socket" with LED light, but Smartlife and Google do ... ???

### ISSUE THREAD

**Issue by aammerman** [milo526/homebridge-tuya-web#70]
This is a cross-post from Reddit, r/homebridge.  And this is probably operator error again, but I would appreciate any help here nonetheless: I bought a rather neat little smart wifi socket that has a ring of RGB LED's around the socket. What's particularly neat is that the LED ring essentially operates as a separate light -- in other words, Smartlife, and Google, see this item as two "separate" things to control: a smart switch, and also a light with controllable colors. Again, I can use the Smartlife app and/or Google to turn the light on/off, dim or brighten it, and change colors. Works great! And I can have these apps turn the switch on or off, no problem. But Homebridge (running TuyaWebPlatform) doesn't see this switch/light combo at all. I tried resetting the device and re-registering it with Smartlife, but that makes no difference. Ideas and suggestions much appreciated.

**Comment by milo526** [comment]
Hey,

We'll see what we can do about that.

Could you please follow the steps outlined in the readme under ["How to check whether the API this library uses can control your device?"](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device).

If only the socket is listed there - there is no "nice" way to do it.

You could however always add 2 scenes to Tuya. 1 scene that turns on the light and another that turns off the light. You could then expose these scenes to HomeKit (once again read the readme on how to do this).

If the light is also listed (next to the socket) then there is a problem with the plugin and I'll be happy to fix it 😄

**Comment by aammerman** [comment]
I do not think the API controls this pesky device: While the Smartlife app shows six devices, with the device in question, "RGB Smart Plug", at the top, when I run your script at https://repl.it/ , the results seem (as best I can read it) to just show the last five :

(Now, I guess I will try adding the scenes to Tuya, as you suggest.)

Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {   'brightness': '123',
                                                  'color_mode': 'colour',
                                                  'online': True,
                                                  'state': 'true'},
                                      'dev_type': 'light',
                                      'ha_type': 'light',
                                      'icon': 'https://images.tuyaus.com/smart/program_category_icon/dj.png',
                                      'id': '77226320d8bfc0d1988a',
                                      'name': 'AirLux Bulb'},
                                  {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/1493798894_0.png',
                                      'id': '04200091b4e62d13a123',
                                      'name': 'Stained glass window'},
                                  {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/1493798894_0.png',
                                      'id': '04200091b4e62d139d6d',
                                      'name': 'TV Room'},
                                  {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/1493798894_0.png',
                                      'id': '0520001668c63abf350d',
                                      'name': 'floor lamp'},
                                  {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/1493798894_0.png',
                                      'id': '042000916001947f766d',
                                      'name': 'Hallway light'}],
                   'scenes': []}}

**Comment by aammerman** [comment]
I added four scenes to Smart Life: one to turn the switch on, one to turn the switch off; one to turn the LED light on, one to turn the LED off. Homebridge shows each of these scenes as an accessory. So does HomeKit now: I combined the two switch scenes into a Group for the switch, and combined the two LED light scenes into another group for the light.  Now I can turn the light on and off independently of the switch, but I cannot control its color or brightness from HomeKit. So, does this development mean that the plug-in can be tweaked in some way to perhaps more correctly control the switch and LED light combination?

**Comment by milo526** [comment]
No sorry, since the light is not showing up in the list, there is nothing I can do.

If you would like to finely control the status of the led you will either need to create more scenes; one for every state you want the led to be changeable to.

Or, arguably the better option, switch to @iRayanKhan 's amazing plugin [homebridge-tuya](https://github.com/iRayanKhan/homebridge-tuya). That one would probably support your specific device better.
