### ISSUE TITLE
pooling interval

### ISSUE THREAD

**Issue by janodms** [milo526/homebridge-tuya-web#71]
Hi, have a problem whit the pooling interval.
if I don't put the number of pooling interval Homebridge regonize the change of the state 3 minutes after the state change.

how I can change this, I want a pooling interval of low seconds, like 5 sec. and the last update say the next:

''pollingInterval Optional. Defaults to empty which entails no polling. The frequency in seconds that the plugin polls the cloud to get device updates. When you exclusively control the devices through Homebridge, you can set this to a low frequency (high interval number, e.g. 1800 = 30 minutes).``

the minimum number its 300... on the config of Homebridge.

please can help me whit that.

thnx.

**Comment by milo526** [comment]
Hello,

I get quite some questions regarding this. Therefor I just wrote a wiki-page regarding this.

Please read [this wiki page](https://github.com/milo526/homebridge-tuya-web/wiki/Rate-Limiting). It explains why going any faster is not possible, and why there is nothing I can do about that.
