### ISSUE TITLE
What is all this noise, and can I disable it?

### ISSUE THREAD

**Issue by marksthomas** [milo526/homebridge-tuya-web#72]
<img width="1040" alt="Screenshot 2020-09-02 at 12 44 27" src="https://user-images.githubusercontent.com/32539594/91977164-1e35db00-ed1a-11ea-958f-3ebb05fa2e28.png">

Subject. A bit too noisy - this in the logs every few minutes. Can it be disabled?

**Comment by milo526** [comment]
Please disable debug mode.

**Comment by marksthomas** [comment]
Sorry, lamer but how do I do that? Can't see anything in settings?

**Comment by milo526** [comment]
Seems like I was to quick here in my judgement; This issue is now correctly tracked in #79
