### ISSUE TITLE
Duplicated devices after override its default type

### ISSUE THREAD

**Issue by rhumbertgz** [milo526/homebridge-tuya-web#76]
Hello,

First, thanks for this integration 👍🏻

After I override the type of my Teckin smart plugs from _switch_ to _outlet_ the old switches remain. Now, when I click in the tab "Accessories" of the homebridge UI I see the same device as  _switch_ and _outlet_ (e.g., Humberto's Desktop). On the other hand, the home app shows one device but with two controls like a double switch.

I restarted homebridge several times but the issue persists 😞

Thanks in advance
Humberto

Here you can see some screenshots

![image](https://user-images.githubusercontent.com/10393245/92175719-6f8abb00-ee3d-11ea-967f-8370d9ead589.png)

![image](https://user-images.githubusercontent.com/10393245/92175793-85987b80-ee3d-11ea-97bb-f475be2a43c0.png)

![image](https://user-images.githubusercontent.com/10393245/92175980-e1630480-ee3d-11ea-8dd0-734e40be6754.png)

**Comment by cilianospina** [comment]
Is easy, homebridge settings, Remove Single Cached Accessory, remove device, restart and work fine now :)

**Comment by rhumbertgz** [comment]
@cilianospina thanks for your help, problem solved 👍🏻
