### ISSUE TITLE
I cant get Tuya/SmartLife connected

### ISSUE THREAD

**Issue by malikramires** [milo526/homebridge-tuya-web#78]
Hello,

i cant activite/connect the Service to my Homebridge,the Username and password is correct !
Error in Log
[9/6/2020, 12:20:52 AM] [TuyaWebPlatform] Authentication error: Get accesstoken failed. Username or password error!

config.json
  {
            "name": "TuyaWebPlatform",
            "options": {
                "username": "xxxx",
                "password": "xxxx",
                "countryCode": "49",
                "platform": "smart_life"
            },

**Comment by milo526** [comment]
I checked the tuya servers and they did not have any issues the last few hours.

I verified the working of the plugin and the plugin is able to get tokens.

I strongly suspect there is an issue on your side. Do you use Sign In with Apple by any chance? Cause that won't work.
