### ISSUE TITLE
[Accessory Request] Scenes

### ISSUE THREAD

**Issue by motogon** [milo526/homebridge-tuya-web#8]
please add Smart Universal IR device

**Comment by fratton** [comment]
I use 3 "Scene" switch with my Smart Life IR Gateway to control air-conditioner and my fork https://github.com/fratton/homebridge-tuya-web/

**Comment by mbierman** [comment]
> I use 3 "Scene" switch with my Smart Life IR Gateway to control air-conditioner and my fork https://github.com/fratton/homebridge-tuya-web/

I can definitely see that some people may want scenes to import into Home. What is weird to me is they aren't converted to Home automations, but are like elaborate switches. 

So this might be a big ask, but perhaps the plugin could have a configuration for importing Tuya scenes or not.  I suppose people could simply delete them all from their Tuya app, but there may be good reasons for being able to keep them there and not see them in Home.

**Comment by milo526** [comment]
@fratton I am trying to understand how you use the switches, am I correct to understand that you

1) Created a scene in the Tuya app that triggers a specific action (i.e. turn off your air-conditioning)
2) Use this library to trigger said scene (and in turn, turn off your air-conditioning)

That seems like a great idea and a method that would enable us to support even more functionality!

To get this to work we would probably indeed expose Tuya scenes as homebridge switches which will enable you to trigger them through Home.app and Siri.

@mbierman would that also work for your implementation of scenes? They would *not* be imported as scenes in Homekit.

**Comment by fratton** [comment]
@milo526 Exactly
[https://github.com/fratton/homebridge-tuya-web/raw/master/homebridge-tuya-scene.jpg](url)

**Comment by mbierman** [comment]
@milo526 that seems very reasonable to me. Bonus points if Tuya scenes > homekit switches could be turned off with a config setting for those that find it useless or confusing.

**Comment by Faisalthe01** [comment]
> @milo526 Exactly
> https://github.com/fratton/homebridge-tuya-web/raw/master/homebridge-tuya-scene.jpg

Hey Mate, can i use my garage door opener with your plugin? I have a scene for it in SmartLife, can it be imported as Garage Door Opener?

**Comment by mbierman** [comment]
@milo526 that makes sense to me. Might be nice to have an "include all" and "include none" if possible but not critical.

**Comment by Faisalthe01** [comment]
> Will working on this I discovered a few things for which I'd like some input.
> 
> 1. How do we handle removal of scenes,  currently when you remove a device from your Tuya app it will stay visible in homebridge. Scenes are more volatile and I expect them to be removed more often but I'd hate to break users' automations by removing random accessories (such as switches for the scenes) once they are removed from Tuya.
> 2. What to do with automations, Tuya supports 2 types of scenes, first of "Tap-to-Run" which we want to use in this case to trigger properties of our devices; and second "smart" scenes which trigger based on pre-defined triggers such as location, time or weather. I don't think these are useful and the API does not seem to support triggering them from homebridge.
>    The ugly thing here is that we are unable to differentiate between them, both are identified as "Scenes".
> 
> I think a solution to both of them would be to include a "white-list" in the configuration in which you can provide a list of scenes that you want to expose to homebridge by name or id.
> 
> Currently I'm looking to implement stateless switches which you can tap in homekit to trigger the scene, these switches will turn off after 1 second so you can trigger the scene again.

Hi @milo526 , I noticed you closed my Brightness and Hue issue. Just wondering have you seen Vitramir fork? He has more code in his lib .js files plus he asked me to put more code in my config file, he said he will add that code in his src files so i can get remove it from my config file but then he disappeared and it took him some time to fix brightness and temperature for bulbs plus he added cover support. I want to use your plugin, as you are going to maintain it and planning to add scenes support in future . My question is are you confident that your code has everything like his code? It takes long time to fix my automation one accessories reset in HomeKit so want to make sure. Thanks

**Comment by milo526** [comment]
> > Will working on this I discovered a few things for which I'd like some input.
> > 
> > 1. How do we handle removal of scenes,  currently when you remove a device from your Tuya app it will stay visible in homebridge. Scenes are more volatile and I expect them to be removed more often but I'd hate to break users' automations by removing random accessories (such as switches for the scenes) once they are removed from Tuya.
> > 2. What to do with automations, Tuya supports 2 types of scenes, first of "Tap-to-Run" which we want to use in this case to trigger properties of our devices; and second "smart" scenes which trigger based on pre-defined triggers such as location, time or weather. I don't think these are useful and the API does not seem to support triggering them from homebridge.
> >    The ugly thing here is that we are unable to differentiate between them, both are identified as "Scenes".
> > 
> > I think a solution to both of them would be to include a "white-list" in the configuration in which you can provide a list of scenes that you want to expose to homebridge by name or id.
> > Currently I'm looking to implement stateless switches which you can tap in homekit to trigger the scene, these switches will turn off after 1 second so you can trigger the scene again.
> 
> Hi @milo526 , I noticed you closed my Brightness and Hue issue. Just wondering have you seen Vitramir fork? He has more code in his lib .js files plus he asked me to put more code in my config file, he said he will add that code in his src files so i can get remove it from my config file but then he disappeared and it took him some time to fix brightness and temperature for bulbs plus he added cover support. I want to use your plugin, as you are going to maintain it and planning to add scenes support in future . My question is are you confident that your code has everything like his code? It takes long time to fix my automation one accessories reset in HomeKit so want to make sure. Thanks

With regards to my confidence:
Nope not at all; I'm confidently giving 0 garanties on the working on the library. 
Of all the devices in this library I only own a Tuya fan which I can test, all other devices are either take over from older versions of this library, other forks, or updates from other people who I hope have the devices to test them with.

I you'd like more garanties feel free to gift me one of the devices such that I can test with them 😉 

I have seen Vitramir's fork, it has however move on quite a bit from the original library, this makes it hard to compare the two libraries.

**Comment by mbierman** [comment]
I thought there was some action planned on this. Should it be reopened?

**Comment by milo526** [comment]
The current beta ([v0.4.1](https://github.com/milo526/homebridge-tuya-web/releases/tag/v0.4.1)) which can be installed by installing `@milo526/homebridge-tuya-web@beta` contains support for scenes 🎉 .

Could you please check to see if this works for you?

Please not that you will need to explicitly enable scenes support, check the README on how to do that.

**Comment by Mimomaj** [comment]
I have a Tuya smart life vacuum cleaner and I have created a simple Tap-to-run scene in the Smart life app consisting of two tasks: auto-mode and recharging mode of the v. cleaner. So when I run the scene via SmartLife app, it starts cleaning, when I tap on it again it goes back to the base. However the behavior in the Home app is different: when I turn on the switch, it starts cleaning but then it becomes unresponsive and I can't park the v. cleaner using the Home app. I believe that this should work somehow and my setup is wrong. Could someone help me or explain how should I get this to work? I apologize if this is the wrong place to discuss this, if that's the case I will delete my comment. Thx in advance.

**Comment by milo526** [comment]
> I have a Tuya smart life vacuum cleaner and I have created a simple Tap-to-run scene in the Smart life app consisting of two tasks: auto-mode and recharging mode of the v. cleaner. So when I run the scene via SmartLife app, it starts cleaning, when I tap on it again it goes back to the base. However the behavior in the Home app is different: when I turn on the switch, it starts cleaning but then it becomes unresponsive and I can't park the v. cleaner using the Home app. I believe that this should work somehow and my setup is wrong. Could someone help me or explain how should I get this to work? I apologize if this is the wrong place to discuss this, if that's the case I will delete my comment. Thx in advance.

Scènes can only be triggered and can't have alternate states, could you try making a different scene that sends the cleaner back to its base? So 1 scene for go clean, another for return to base

**Comment by Mimomaj** [comment]
> Scènes can only be triggered and can't have alternate states, could you try making a different scene that sends the cleaner back to its base? So 1 scene for go clean, another for return to base

I see. So the only solution for now is to have 2 swithes in the Home app, one will do the first task and the other the second task. Correct?

**Comment by milo526** [comment]
> I see. So the only solution for now is to have 2 swithes in the Home app, one will do the first task and the other the second task. Correct?

Correct

**Comment by Mimomaj** [comment]
> Correct
Thanks for the support

**Comment by milo526** [comment]
This issue has been fixed in the [v0.4.2 release](https://github.com/milo526/homebridge-tuya-web/releases/tag/v0.4.2) if you are still experiencing this issue, or are experiencing other issues, please open a new bug report.

Thank you once again for this bug report, reports like these help make the plugin better!

**Comment by milo526** [comment]
Please note that the config variable for whitelists has changed between the beta and the public release (due too issues with config-ui-x). Please read the documentation on how set a scene whitelist.
