### ISSUE TITLE
Adding a diffuser

### ISSUE THREAD

**Issue by vladcristian1993** [milo526/homebridge-tuya-web#82]
Hi,

i'm trying to add a diffuser from SmartHome with the plugin
I tried adding it as a fan.
Ofc its the real virtual id instead of the text between the quotes.

If you have any ideas, it'll be greatly appreciated.

[9/16/2020, 12:50:31 AM] [TuyaWebPlatform] Tried adding default for device: "*virtual id*" which is not a valid device-id or device-name.

**Comment by milo526** [comment]
Hello could you please provide me with a full log and your homebridge configuration (redact your username and password). This is too little information to help you.
