### ISSUE TITLE
Switch Shutter Tuya

### ISSUE THREAD

**Issue by cinaxx** [milo526/homebridge-tuya-web#86]
**Describe the bug**
I just install the fresh install of homebridge 1.2.3 with the plugin milo526/homebridge-tuya-web v0.4.7
Actually, wallplug & Bulb work very well and Switch Shutter not

**To Reproduce**
I reboot my homebridge after install, i uninstall & reinstall the plugin, finally for the same thing

**Screenshots**
Smartlife side > https://ibb.co/hDQfdXB
HomeBridge side > https://ibb.co/g6vCLpb

**Device**
 - Plugin Version:  v0.4.7
 - Homebridge config: 
```json
{
    "bridge": {
        "name": "Homebridge 5258",
        "username": "xx:97:xx:B5:52:xx",
        "port": 51694,
        "pin": "xxx-xx-xxx"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "TuyaWebPlatform",
            "options": {
                "username": "xxx@gmail.com",
                "password": "xxx",
                "countryCode": "FR",
                "platform": "smart_life"
            },
            "defaults": [
                {
                    "device_type": "form"
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        }
    ]
}
```
Thank you for your Help

**Comment by milo526** [comment]
Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

Without this it is hard for me to help you with regards to this specific issue.# #

**Comment by cinaxx** [comment]
Hello @milo526 
I don't know if it's the expected result

_Traceback (most recent call last):
  File "C:\Users\cinaxx\Desktop\tuya.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'_

if I live in France,  informations bellow are correct ? 

REGION = "fr" # cn, eu, us
COUNTRY_CODE = "33" # Your account country code, e.g., 1 for USA or 86 for China

**Comment by milo526** [comment]
Thank you for that information, you are indeed using cover accessories that are not yet supported as you already discovered.

I'm going to close this in favour of #18 Please read up on that issue. You can also follow that issue for notifications on future changes.
