### ISSUE TITLE
Error on checking too often

### ISSUE THREAD

**Issue by mbierman** [milo526/homebridge-tuya-web#89]
**Describe the bug**
I see the error below which says not to check more often than 600 seconds. 
![CE5DB65D-BB39-4FE2-8777-04513EECECBE](https://user-images.githubusercontent.com/1205471/94649700-1120f300-02aa-11eb-924b-e745f60fffcc.png)

The plugin settings say, `300 seconds`. 
![902EF68A-4748-454B-9257-B64D1709E92E](https://user-images.githubusercontent.com/1205471/94649893-783ea780-02aa-11eb-83f7-d3890df780c2.png)

**Steps To Reproduce**

1. Set   `"pollingInterval": 300` as the Plug-ins Settings interface suggests.
2. Restart
3. Watch logs

**Plugin Version**
 @milo526/homebridge-tuya-web v0.4.7

 
 **Homebridge Config**

 ```json
         {
            "name": "Smart Life",
            "options": {
                "username": "",
                "password": "",
                "countryCode": "1",
                "platform": "smart_life",
                "pollingInterval": 300
            },
            "defaults": [
                {
                    "id": "36802558cc50e3cfc0ae",
                    "device_type": "switch"
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        },
```

**Environment:**

* **Node.js Version**: 12.18.4
* **NPM Version**: 6.14.8
* **Homebridge Version**: 1.2.3
* **Homebridge Config UI X Version**: v4.27.2
* **Operating System**: Docker
* **Process Supervisor**: Docker

**Comment by milo526** [comment]
Thank you for this report;
I was not yet aware of this change.

Tuya changed some settings on their end that made this plugin slightly incompatible with their servers.
v0.4.8 has just been pushed to NPM and should be available shortly.
It pushes the minimal polling interval to just over 600.

**Comment by mbierman** [comment]
@milo526 You are amazing. Thank you.
