### ISSUE TITLE
Can we add "contact sensor" to devices supported?

### ISSUE THREAD

**Issue by cjastennett** [milo526/homebridge-tuya-web#90]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like contact sensors (sensors in the smart life app) to be included in the devices support. I don't know if there is any kind of "push" capability via the smartlife API.

These are the sensors in question:

WiFi   Door and Window Smart Sensor Alarm, App Control Wireless Security System with   Push Notification, Universal Installation, Compatible with Amazon Alexa,   Google Home, IFTTT  

The seem to be pretty generic.. but work well.

**Describe alternatives you've considered**
I have used a work around where my contact sensors switch on/off a switch (plug socket) in smartlife, but because of the 600s refresh rate, events often go unnoticed by homebridge/homekit. 

**Additional context**
Thanks for your help on this - much appreciated.

**Comment by milo526** [comment]
Hello and thank you for your request,

Sadly this is not possible due to tuya limitations. Such a push capability for the utilised API does not exist.

Please take a look at one of the other tuya homebridge plugins. some of them do support sensors.
