### ISSUE TITLE
Device reset after electric cutoff

### ISSUE THREAD

**Issue by AAG97** [milo526/homebridge-tuya-web#92]
**Describe the bug**
Im using a basic switch to control a light and customize it for automation and as a light in the homeapp.. when the electricity goes off the device return to the way it was at first installation being displayed as a switch not light and removed from automations for some reason and I have to re do the changes every time the electricity goes off (living in a country where 24/7 electricity is a miracle) 
Im using devices from other manufacturers with different plugins and didn't have this issue before

**Steps To Reproduce**
Literally Just turn off the electricity and turn it on

**Plugin Version**
 0.4.8
 
 **Homebridge Config**
```json
 name" : "TuyaWebPlatform",
      "options" : {
        "countryCode" : "86",
        "password" : ",
        "platform" : "smart_life",
        "username" : "the "
      },
      "platform" : "TuyaWebPlatform",
      "plugin_map" : {
        "plugin_name" : "homebridge-tuya-web"
      },
      "scenes" : false
    }
  ],
  "ports" : {

  },
  "server" : {
    "autostart" : 0,
    "home_setup_id" : "X-HM://0023ISYWY125N",
    "origin" : "*",
    "polling_seconds" : 1,
    "port" : 80
  },
  "system" : "hoobs"
}
```
 **Device Config**
 
 
 **Additional Context**

**Comment by imtitanic** [comment]
Same here, after restart homebridge the device returns to defaults config.

**Plugin Version**
_v0.4.8_

**Homebridge Config**

```
         {
             "name": "TuyaWebPlatform",
             "options": {
                 "username": "xxx@xxx.com",
                 "password": "xx",
                 "countryCode": "52",
                 "platform": "smart_life"
             },
             "scenes": false,
             "platform": "TuyaWebPlatform"
         },
```

**Additional Context**

> [2020-10-3 20:26:43] [TuyaWebPlatform] Initializing TuyaWebPlatform platform...
> [2020-10-3 20:26:43] [TuyaWebPlatform] Loading accessory from cache: Smart Bulb RGBCW
> [2020-10-3 20:26:48] [TuyaWebPlatform] Existing Accessory found [Name: Smart Bulb RGBCW] [Tuya ID: eb8989bb2299397949jzop] [HomeBridge ID: 0f589792-2356-44a0-a37c-bb66c8a3af5d]
> [2020-10-3 20:26:48] [TuyaWebPlatform] [Smart Bulb RGBCW] Characteristic.On - Enabled
> [2020-10-3 20:26:48] [TuyaWebPlatform] [Smart Bulb RGBCW] Characteristic.Brightness - Enabled
> [2020-10-3 20:26:48] [TuyaWebPlatform] [Smart Bulb RGBCW] Characteristic.ColorTemperature - Enabled
> [2020-10-3 20:26:48] [TuyaWebPlatform] [Smart Bulb RGBCW] Characteristic.Hue - Enabled
> [2020-10-3 20:26:48] [TuyaWebPlatform] [Smart Bulb RGBCW] Characteristic.Saturation - Enabled
> [2020-10-3 20:26:54] [TuyaWebPlatform] [Smart Bulb RGBCW] - Requesting device state
> [2020-10-3 20:26:54] [TuyaWebPlatform] [Smart Bulb RGBCW] - Creating new debounced promise
> [2020-10-3 20:26:54] [TuyaWebPlatform] [Smart Bulb RGBCW] - Triggering debouncedDeviceStateRequest
> [2020-10-3 20:26:54] [TuyaWebPlatform] [Smart Bulb RGBCW] - Requesting device state
> [2020-10-3 20:26:54] [TuyaWebPlatform] [Smart Bulb RGBCW] - Triggering debouncedDeviceStateRequest
> [2020-10-3 20:26:54] [TuyaWebPlatform] [Smart Bulb RGBCW] - Requesting device state
> [2020-10-3 20:26:54] [TuyaWebPlatform] [Smart Bulb RGBCW] - Triggering debouncedDeviceStateRequest
> [2020-10-3 20:26:54] [TuyaWebPlatform] [Smart Bulb RGBCW] - Requesting device state
> [2020-10-3 20:26:54] [TuyaWebPlatform] [Smart Bulb RGBCW] - Triggering debouncedDeviceStateRequest
> [2020-10-3 20:26:54] [TuyaWebPlatform] [Smart Bulb RGBCW] - Requesting device state
> [2020-10-3 20:26:54] [TuyaWebPlatform] [Smart Bulb RGBCW] - Triggering debouncedDeviceStateRequest
> [2020-10-3 20:26:54] [TuyaWebPlatform] [Smart Bulb RGBCW] - Unsetting debouncedDeviceStateRequestPromise
> [2020-10-3 20:26:54] [TuyaWebPlatform] [Smart Bulb RGBCW] - Resolving resolveDeviceStateRequest from cache

**Comment by milo526** [comment]
Hello and thank you for opening a bug report!

My first instinct would be that there is a problem with your device and the storage; are you by any chance running on a raspberry pi? (Or did you buy the hoobs package, that package normally runs on a raspberry pi)

Could you try starting the homebridge (or hoobs) server, and then gracefully shutting it down to see if that keeps the settings.

**Comment by AAG97** [comment]
Im using a raspberrypi 4 with hoobs software 
When restarting it, it keeps the setting
Only restore when the switch electricity goes off

**Comment by milo526** [comment]
Unfortunately it is rather hard for me to control when data gets written to the storage of your Pi.
The issue here seems to be that the Pi has changes in memory but they do not get written back to the system in time.

I will leave this issue open to collect more reports and possibly look into this at a later time.
