### ISSUE TITLE
delay response

### ISSUE THREAD

**Issue by chetoile98** [milo526/homebridge-tuya-web#93]
**Describe the bug**

hello,

a few days ago I installed this plugin, everything is working fine with some module switches but I have a delay of about 1-2secs when I click on the "switch" on the home app and the lights really turn on, but on the Tuya app is instantaneous.
Is anyone facing the same thing? 
I'm using the country code 86 (on homebridge setup and Tuya app), but I am in Portugal, could it be the problem, or is the device_type the wrong one ?

I'm using the last version of the plugin and last version of homebridge

 
 **Homebridge Config**
My setup
 
 ```json
 {
     "name": "TuyaWebPlatform",
     "options": {
         "username": myaccountemail,
         "password": mypassword,
         "countryCode": 86,
         "platform": "tuya",
         "pollingInterval": 600
     },
     "defaults": [
         {
             "device_type": "form"
         }
     ],
     "scenes": false,
     "platform": "TuyaWebPlatform"
 }
 ```
 thanks a lot for your help

**Comment by milo526** [comment]
Thank you for opening this issue;
I have not heard about this issue before and I am also not experiencing this myself.

I do suspect that this has something to do with the country code that you are using (china if I'm not mistaken) while being in Portugal. Using the Chinese country could means that you are also using the Chinese tuya servers. You might want to look into switching this country code (this could mean setting up a new account) and see if that helps you.

**Comment by chetoile98** [comment]
Thanks a lot @milo526 

I will try your suggestion, the funny thing is even on homebridge it works just fine, I only have the delay on home app

**Comment by chetoile98** [comment]
hello @milo526 

I just did what you propose and it works just fine :) changing the country code to 351 (Portugal) made it very responsive 

thanks a lot for your help

**Comment by milo526** [comment]
Great to hear!
