### ISSUE TITLE
When Device offline, HomeKit always show device on 

### ISSUE THREAD

**Issue by jujinfu** [milo526/homebridge-tuya-web#94]
have couple llight bulbs
When cut the power, Apple HomeKit always shows the lights as ON

**Comment by bwp91** [comment]
Is the status correct if you turn them off via homekit before you cut the power?

**Comment by stigganOne** [comment]
Experience same thing. Having a wifi lamp that's offline until I turn on the fan since they share the physical button. When turning the power off it stays and shows light ON.

**Comment by milo526** [comment]
Yeah this is a known problem. I could probably report every device as off when they are offline. I'd rather be able to report that a device is offline but there does not seem to be a proper way to do that currently

**Comment by nullyn** [comment]
@fratton's fork at [fratton/homebridge-tuya-web](https://github.com/fratton/homebridge-tuya-web#readme) works really well with OFF / ON states. In the last update, I see this:

_Device State Caching. State of devices is cached in memory, every time a HomeKit app request status updates from the devices this results in a very fast and responsive response. State cache is updated every 10 seconds and when controled from a HomeKit app._ 

He seems to be polling every 10 seconds by default (can be changed). Unfortunately, the light bulb's colours are wonky when changing them from the Homekit app, hence I am using your Plugin.

**Comment by milo526** [comment]
Sorry for the delayed reply @nullyn I was under the impression that I already replied.

I did not try, but I suspect that fraction's fork does not work anymore (it is also archived). This due to some changes made by Tuya to their API. They severely reduced how often these plugins can update their states. This is limited to once every 5 minutes 😢
This is not something I can change or work-around (believe me, I have tried 😛)

**Comment by milo526** [comment]
Version 0.6.3 has just been released as a pre-release version of the library.

When a device is offline, it will now be shown as "non-responding" (cause that is what is actually happening 😄)

If you have devices that are offline more permanently, add them to your ignored device list to, well, ignore the device. This will remove it from homekit and thus not show the error.
