### ISSUE TITLE
Smart Thermostat

### ISSUE THREAD

**Issue by karnas99** [milo526/homebridge-tuya-web#95]
Hi,

as far as I understand smart thermostat is not supported. At least I can not see them in homekit after plugin installation.
Supporting these thermostats would be awesome. I believe all tuya thermostats are similar.

I have these https://www.aliexpress.com/item/1005001506048421.html?spm=a2g0o.productlist.0.0.37ba179asQMVgK&s=p&ad_pvid=202010190549555255994818997240003264712_22&algo_pvid=7f295026-40c2-4415-89d4-60d1ff94e253&algo_expid=7f295026-40c2-4415-89d4-60d1ff94e253-21&btsid=0b0a187916031117953648829e2a3e&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

Thanks
Jan

**Device type**

**Device information**

```json

```

**Comment by karnas99** [comment]
I just found this in logs
[10/19/2020, 13:42:46] [TuyaWebPlatform] Missing required `id` property on device type overwrite, received:
{
  "device_type": "form"
}
[10/19/2020, 13:42:46] [TuyaWebPlatform] Could not init class for device type [climate]

**Comment by milo526** [comment]
Hello and thank you for opening this issue.

As of yet there is indeed no support for smart thermostats.

Please follow #63 for updates regarding this topic.
