### ISSUE TITLE
When used the physical button, Homekit/Homebridge does not update.

### ISSUE THREAD

**Issue by biosim500** [milo526/homebridge-tuya-web#97]
**Describe the bug**

Hi! First of all thanks for this plugin! It's amazing what one developer can do!

I got a strange issue. I have 2 smartlife devices, one power socket and a smart switch (like sonoff). When i press the button on the power socket, it does not update on homekit and homebridge it state. Like if u turned on with the button on the device, it will show as off on homekit/homebridge. Or if i turn'm on via homekit and press the physical button to turn it off, it'll show still as on via homekit.

I've already changed the pool option but didn't work.

Is this issue common? Is something that i did? When i press the button nothing appears on the log.

Thanks for the attention! I've already tried to search some other pools but didn't find something similar.

**Steps To Reproduce**

Pushed the button on the device and on homekit/homebridge did not update.
**Plugin Version**
 
 0,4,8
 **Homebridge Config**
 
 
 ```json

```
         {
            "name": "TuyaWebPlatform",
            "options": {
                "username": "xxxxxx",
                "password": "xxxxxxx",
                "countryCode": "xx",
                "platform": "smart_life"
            },
            "scenes": false,
            "platform": "TuyaWebPlatform"
        }
 **Device Config**
 
 
 **Additional Context**

**Comment by milo526** [comment]
Hello,

This is expected albeit undesired behaviour. Sadly this is a limitation imposed by Tuya which I cannot work around. If you set a polling interval in your config, the state should update eventually. This should take +/- 5 minutes (with a polling interval of `610`).
When you change the state via HomeKit it should always update immediately.
