### ISSUE TITLE
Not Wifi Devices like ZigBee Gateway

### ISSUE THREAD

**Issue by Oggymator** [milo526/homebridge-tuya-web#99]
Hi,

what about the support of non Wifi devices like the Tuya ZigBee Gateway?

thanks
Oggy

**Comment by milo526** [comment]
Hello, thank you for taking the time to open this issue.

Please check the steps in the readme under "How to check whether the API this library uses can control your device?"

Sadly I strongly suspect that they will not be supported.

Please check with one of the other plentiful tuya homebridge plugins (not other versions of Tuya-web) if they can support your device.

If the steps outlined above indeed do not show your device there is nothing this plugin can do to help you.

**Comment by Oggymator** [comment]
Thanks for your response, I did found it in the Tuya-Web API.
Also I saw on the Home Assistant Website, that ZigBee is not supported.

Tuya has a API for ZigBee, so why nobody use it.
https://github.com/TuyaInc/tuya_zigbee_gw_ext_sdk

**Comment by milo526** [comment]
I'm sorry, I'm not familiar with that API.

Please feel free to submit a PR to switch the API over! That might benefit more people?

Or you might want to create your own homebridge plugin that supports this API?
